### ISSUE TITLE
Les mails (workflow) ne sont pas envoyé par le bon expéditeur

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1003]
L'expéditeur des mails est Rubedo, il faudrait que ce soit le nom du site

**Comment by Alexandru-Dobre** [comment]
Les contenus sont transverses aux sites
En attente jusqu'à la conception des params de mail en BO

**Comment by 3AD** [comment]
Dans System settings ajouter un champ Expéditeur et utiliser par défaut ce nom pour les envois de mails
