### ISSUE TITLE
Improve "Profile" block (mailing list)

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#1030]
Improve "Profile" block by adding the a 'Mailing list' field in the settings, to select which mailing lists will be displayed in the profile page (same way as "Sign-up" & "Checkout" blocks).
This way, users will be able to modify their newsletter settings on their profile.

**Comment by 3AD** [comment]
Ajouter une phrase de type : Mes abonnements aux newsletters :

**Comment by goncalvesm** [comment]
fait
