### ISSUE TITLE
Include user converter

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#1032]
Include a user converter in Rubedo to be able to convert a user from one user type to another.

**Comment by dfanchon** [comment]
Only for user type = email

**Comment by 3AD** [comment]
Si le nom d'utilisateur saisi lors de l'inscription n'est pas le même que le nom saisi pour l'abonnement à la newsletter, alors l'erreur suivante est affichée en FO: Error ! {"found":false,"_index":"rubedo-user","_type":"55acd4d68f28deb4010000ff","_id":"55d1ae158f28de9014000055","_version":1}
