### ISSUE TITLE
Pas de prise en compte des ancres sous IE et Firefox

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1033]
Voir Gestion des ancres dans le texte riche - Issue #961

Bon fonctionnement sous Chrome

**Comment by nicolasrhone** [comment]
Dans rubedo.js, il suffit de remplacer :
angular.element("body").animate({scrollTop: target.offset().top}, "slow");

par :
angular.element("body,html").animate({scrollTop: target.offset().top}, "slow");

**Comment by Alexandru-Dobre** [comment]
Merci !
La crorrection a été intégrée aux soures (branche v3-dev) et sera disponible dans la prochaine release 3.2
