### ISSUE TITLE
Recherche par facettes pour requête manuelle

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1044]
Dans un bloc liste de contenus, la requête manuelle est assez compliquée dès qu'on a beaucoup de contenus... Il serait très pratique de pouvoir filtrer les contenus aussi par facettes.
Ou au moins de pouvoir rechercher un contenu par son nom... Pour le moment on peut seulement filtrer par état de publication et type de contenu.

**Comment by 3AD** [comment]
une colonne affichant la date de création des contenus à été ajoutée pour simplifier la recherche
