### ISSUE TITLE
Augmenter la hauteur de l'éditeur de texte riche

### ISSUE THREAD

**Issue by amorillon** [WebTales/rubedo#1052]
Lorsque l'on passe l'éditeur de texte riche en plein écran, la zone effective d'édition du texte reste restreinte 

![image](https://cloud.githubusercontent.com/assets/3852904/7231318/e3a3848e-e774-11e4-92b2-0265da16cea3.png)

**Comment by 3AD** [comment]
Il suffit de cliquer sur le bouton pour l'agrandir:
http://docs.rubedo-project.org/fr/documentation/construire-site/autres-fonctionnalites/553f8482adb3c5f655970a9c/guide-utilisateur-de-l-editeur-wysiwyg
