### ISSUE TITLE
Etendre la durée de la variable session

### ISSUE THREAD

**Issue by amorillon** [WebTales/rubedo#1053]
Lors de l'intégration de contenu (texte & image) sur des pages assez complexes il arrive régulièrement que je sois déconnecté alors que je suis pourtant en train d'éditer ma page (péremption de la variable session ?). Je perds alors tout mon travail d'intégration (parfois 15 à 20 minutes de travail).

Est-il possible d'étendre cette durée ?

**Comment by 3AD** [comment]
La durée des sessions et de 3600 secondes par défaut. Dans tous les cas, cette durée de session est paramétrable.
