### ISSUE TITLE
issue on installing Rubedo

### ISSUE THREAD

**Issue by ashishcsc** [WebTales/rubedo#1059]
Hi,

I am new to rubedo and tried to install it on windows but at step 4 it shows error. I have followed the steps mentioned on the rubedo official website, I am able to installed successfully upto step 3 but I got error on step 4 (Installation Guide for Windows - Step 4).

I have entered the text which was mentioned on the installation step 4 in rubedo.local and restarted the services and then tried to run the localhost, it shows "Internal Server Error" on the browser. I am not sure what is missing and not able to figure it out.

Could anyone please help to setup rubedo on my machine?

Thanks,
Ashish

**Comment by 3AD** [comment]
Thank you for your questions. Feel free to use the community forum.  
You have an answer to the forum : http://forum.rubedo-project.org/viewtopic.php?f=19&t=301
