### ISSUE TITLE
DB Import/Export BO module

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#1066]
EXPORT
The user can select the mongoDB collections to export (ex : contents + page masks + pages + media)
The export generates a zipfile with the different collections stored in json + binary files for documents

IMPORT
After uploading the zip file the user can choose which collections he wants to import and set the import mode to INSERT (new items are created) or UPSERT (new items are created & existing ones are updated)

**Comment by cney** [comment]
It would be nice to have an API endpoint to perform import/export since those operations are often done on a regular basis with crontabs.
