### ISSUE TITLE
Simple query with id

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1070]
Les types de contenus sont remplacés par l'id 
![requetes simples](https://cloud.githubusercontent.com/assets/3063195/8432397/17bb6612-1f40-11e5-9692-fa97edfbe747.png)

**Comment by dfanchon** [comment]
Non reproductible à l'instant. Revoir sur quel environnement cela se produit.

**Comment by 3AD** [comment]
![requete manuelle](https://cloud.githubusercontent.com/assets/3063195/8980741/3f0fe3ca-36b3-11e5-8d30-0baebf277346.png)
A l'édition d'une requête manuelle

**Comment by 3AD** [comment]
Sur firefox

**Comment by Alexandru-Dobre** [comment]
non reproduit sur firefox
