### ISSUE TITLE
Contents with pending validation status

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1072]
Les contenus en mode brouillon sont indiqué ont un statut online. Il devraient être offline.

**Comment by dfanchon** [comment]
Les deux statuts sont indépendants. Tu peux très bien travailler sur le brouillon d'un contenu déjà en ligne, c'est même le cas générique en cas de modification d'un article déjà publié.

**Comment by 3AD** [comment]
Ok, mais là c'est lors de la création d'un contenu qui est enregistré en brouillon. Il n'a jamais été soumis à validation

**Comment by dfanchon** [comment]
Wording actif/inactif ?
