### ISSUE TITLE
Protected media download block

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1075]
Lorsqu'un utilisateur à inséré son mail il doit visualiser les indications suivantes :

Succès : Un email avec votre lien de téléchargement vous a été envoyé
Erreur : Adresse e-mail invalide

Le document PDF ne s'affiche pas sur Chrome

**Comment by goncalvesm** [comment]
Les notifications s'affichent désormais

**Comment by 3AD** [comment]
Phrase ok pour le français. Merci d'ajouter la phrase aussi pour les autres langues.

**Comment by goncalvesm** [comment]
J'ai ajouté un label par défaut en anglais.
