### ISSUE TITLE
Loss the current language on the fallback

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1083]
Perte de la langue courante sur le fallback
Cas d'usage:
- le site est en 2 langues EN+FR. La langue par défaut est l'anglais
- Une page du site n'existe qu'en anglais
- L'utilisateur consulte le site en FR. Il consulte la page en EN. Il perd sa navigation en FR, le site est passé en EN sans conserver sa langue de navigation.

**Comment by goncalvesm** [comment]
Fix vanity url on content detail language switch and bad redirection

**Comment by goncalvesm** [comment]
Fixed
