### ISSUE TITLE
Progressive page construction

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#1093]
Sur des sites un peu chargés cela peut dégrader l'expérience utilisateur, notamment en mobile ou la surface d'affichage est petite et ou va voir plusieurs blocs se succéder avant le chargement final.
A voir si on pourrait charger la structure (page, blocs) avant de charger les données (contenus et médias).

**Comment by cney** [comment]
Quelques commentaires : 
- Les éléments principaux tels que le header/menu et le footer ne devraient pas être rechargés. Si ils doivent l'être, ils pourraient faire partie du masque de page (choix des developpeurs) et être mis en cache, 
- Un chargement de la structure avec une préservation de la taille minimale des blocs (via css) serait adaptée. Une solution pourrait-être d'ajouter des blocs "d'attente" (que l'on pourrait charter) dans les masques de page, sachant que ces blocs d'attente serait remplacés par les blocs chargés dans le masque.

**Comment by Alexandru-Dobre** [comment]
added min height in advanced properties
