### ISSUE TITLE
GA integration

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#1100]
pageview should be sent for each navigation action

**Comment by Alexandru-Dobre** [comment]
correctif effectué

**Comment by cney** [comment]
a few additional comments:
- could you please use the new universal analytics marker
  - be careull not to send the event twice when a new page is loaded
- see https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

Hope this helps 
Christophe
