### ISSUE TITLE
Commerce facets are available in search bloc

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1107]
Sur un site qui propose des produits et des contenus, dans le bloc page de recherche en FO je sélectionne le type de contenu Article. Les facettes Prix et en stock restent affichées

**Comment by Alexandru-Dobre** [comment]
disable ranged facets in general when count 0

**Comment by dfanchon** [comment]
Price et stock sont des facettes système et ne doivent pas être renvoyées comme des taxonomies par le front. A intercepter dans le controller.

**Comment by Alexandru-Dobre** [comment]
done
