### ISSUE TITLE
Resizing image FO

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1108]
Il est possible de redimensionner manuellement les images depuis un champs texte riche en FO et en Back, mais le redimensionnement n'est pas persisté lors de l'enregistrement lorsque le redimensionnement est fait en front. Obligation de saisir les dimensions dans les propriétés de l'image.

Fonction possible depuis IE et Firefox.
Fonction non présente depuis Chrome.

**Comment by Alexandru-Dobre** [comment]
Limitation CKE
