### ISSUE TITLE
add publication date for manual query

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1110]
Ajouter une colonne avec la date de publication dans l'interface permettant de sélectionner les contenus dans le cas d'une requête manuelle.
Le top serait d'avoir une recherche

**Comment by nicolasrhone** [comment]
Tout à fait... dès qu'on a plus d'une 50aine de contenus de même type, une recherche texte + taxonomie devient presque indispensable !

**Comment by 3AD** [comment]
Add Last update for content
