### ISSUE TITLE
taxonomy is not available in the form for adding content (FO)

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1115]
Un valideur de contenus crée un nouveau contenu depuis le front. Ce type de contenu a une taxonomie obligatoire. Le formulaire d'ajout de contenu en front n'affiche pas les taxonomies.

**Comment by goncalvesm** [comment]
non reproduis avec un admin et un valideur (seul la taxonomie de navigation n'est pas affichée car elle est auto-appliquée suivant la page en cours)
