### ISSUE TITLE
Change email alert for FO contributors

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1116]
L'email envoyé aux personnes ayant le droit "contribution FO" contient un lien vers le BO. Ils n'ont pas accès au BO

Good morning,

The content "Ma contribution front" has been published by admin.
You can find this content in back-office by following this link

Best regards

**Comment by dfanchon** [comment]
Ajouter les liens en front et en back en précisant "Regarding your rights you can access this content in the back-office (lien 1) or/and directly on the site (lien 2)"
