### ISSUE TITLE
the tooltip remain in the default language

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1119]
Les tooltips des champs des types d'utilisateurs restent en anglais et leur traduction ne s'affiche pas dans les autres langues en FO.

**Comment by goncalvesm** [comment]
Corrigé

**Comment by 3AD** [comment]
Seul le champ "Name" n'est pas traduit dans les autres langues disponibles

**Comment by goncalvesm** [comment]
corrigé

**Comment by 3AD** [comment]
toujours en anglais chez moi
