### ISSUE TITLE
search block and facets

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1123]
recherche en FO.
Si je sélectionne une facette date, les résultats ne sont pas mis à jour.
Si une facette date est sélectionnée en premier, alors les autres facettes sélectionnées ne s'affichent pas dans les critères de recherche.

**Comment by goncalvesm** [comment]
Il y a deux problèmes : 
- nous utilisons des timestamps pour filtrer sur la date alors qu'il faut utiliser le format de date renvoyé par elasticsearch `2015-08-04T22:00:00.000Z-*` (utiliser la clé "key" et non "from" dans les templates front)
- Les filtres ne sont pas appliqués sur les résultats et les facettes. La recherche annonce n résultats sur la facette x pourtant tous les résultats remontent quand cette facette est appliquée et les autres facettes ne sont pas impactées (je n'ai pas testé avec d'autres facettes fonctionnelles en même temps).
