### ISSUE TITLE
Add Traduction keys - newsletter subscribtion

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1125]
Le message affiché après inscription à la newsletter n'est qu'en anglais. Succès ! You have successfully subscribed to the selected newsletter(s)

**Comment by goncalvesm** [comment]
corrigé

**Comment by 3AD** [comment]
Tjrs en anglais

**Comment by goncalvesm** [comment]
Chez moi c'est fonctionnel : 
![image](https://cloud.githubusercontent.com/assets/2509924/9384975/11811b16-4754-11e5-9ec5-c45fed9921e3.png)
