### ISSUE TITLE
Add traduction keys - sign up

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1126]
Message de refus d'inscription uniquement en anglais: Erreur ! Usertype not authorised 
Message lorsque le mail est déjà utilisé: Erreur ! "user" must be back.

**Comment by goncalvesm** [comment]
Erreur ! Usertype not authorised -> traduis
Erreur ! "user" must be back -> ce message n'est pas censé remonter car il indique une erreur dans l'API. C'est maintenant corrigé.

**Comment by 3AD** [comment]
L'utilisateur n'a plus de norification pour lui indiquer que l'email est déjà utilisé

**Comment by goncalvesm** [comment]
Maintenant il y en a une (avant il n'y en avait pas non plus)
