### ISSUE TITLE
Add traduction keys - content contribution

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1137]
Sur le front : 
- titre du type de contenu
- title et  summary
- "Select some options" pour les taxonomies
- boutons de contribution

**Comment by goncalvesm** [comment]
Corrigé

**Comment by 3AD** [comment]
Les champs systèmes sont en anglais: Title / summary

**Comment by goncalvesm** [comment]
![image](https://cloud.githubusercontent.com/assets/2509924/9387437/c9b3b728-4760-11e5-810f-5bfac36818a2.png)
