### ISSUE TITLE
Spelling and traduction key - Supervision

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1143]
en BO sur l'interface de Supervision. Sur la notification de Succès, mettre l'accent dans le bon sens "Succés" par "Succès".
Ajouter les clés de traduction pour les textes de type "cache cleared"

**Comment by Alexandru-Dobre** [comment]
tous les libellés de cette interface ont maintenant des clés de trad

**Comment by goncalvesm** [comment]
mis à jour dans crowdin
