### ISSUE TITLE
Add blocks description 

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1144]
Ajouter la description des blocs suivants dans l'interface BO (liste des blocs):
- category: "Category" block provides quick access to product categories. Various display options are available. 
- User orders: The "User orders" block shows to the logged customer his orders list. 
- Order detail: The "Order detail" block allows you to display the order summary. The page in which this block is included will be displayed once an order is validated and when the customer wants to check the details of an order from the orders list. 
- Product list: The "Product List" block is a default list view that displays products in a grid with access to product detail and adding to cart. 
- Shopping Cart: The "Shopping Cart" block offers two display modes:
  The button mode allows access to cart detail and proceed to checkout.
  The detail mode allows access to checkout.
- Product search: The "Product Search" block displays a product search page with a default layout.
- Checkout: The "Checkout" block displays a one-page checkout form. 
- Dévelopment:  The "Development block" is a container for writing your own AngularJS template code.
  The code can mix regular HTML5 combined with AngularJS directives. 

Et ajouter les clés de traduction.

**Comment by Alexandru-Dobre** [comment]
A rajouter par les clés de trad sur le JSON de définition des blocs

**Comment by goncalvesm** [comment]
Clés de traduction ajoutées (voir dans crowdin)

**Comment by 3AD** [comment]
Le nom des blocs dans la liste des blocs sont ils traduits ?

**Comment by goncalvesm** [comment]
Product list et product search n'étaient pas traduis, maintenant c'est fait.
