### ISSUE TITLE
Add traduction key- FO contribution

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1147]
Lors d'une contribution en front la notification d'enregistrement du contenu est en anglais

**Comment by goncalvesm** [comment]
corrigé

**Comment by 3AD** [comment]
ça ne fonctionne pas chez moi

**Comment by goncalvesm** [comment]
J'ai bien les notifications de mon coté (elles apparaissent quelques secondes en haut à droite de l'écran). J'ai retiré la notification qui apparaissait au dessus des bouton de publication car elle portait à confusion.

![image](https://cloud.githubusercontent.com/assets/2509924/9388712/8b160db6-4767-11e5-844e-784edb9e775a.png)
