### ISSUE TITLE
multivalued image and carrousel

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1150]
Lorsqu'un carrousel de contenu est réalisé à partir d'un type de contenu proposant un champ média multivalué, les images des contenus qui sont multivaluées ne s'affichent pas dans le carrousel.
Soit le carrousel doit utiliser la première image du contenu, soit afficher toutes les images du contenu

**Comment by Alexandru-Dobre** [comment]
fait pour première image
