### ISSUE TITLE
Include user converter

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1169]
Si le nom d'utilisateur saisi lors de l'inscription (bloc inscription) n'est pas le même que le nom saisi pour l'abonnement à la newsletter, alors l'erreur suivante est affichée en FO: Error ! {"found":false,"_index":"rubedo-user","_type":"55acd4d68f28deb4010000ff","_id":"55d1ae158f28de9014000055","_version":1}

**Comment by Alexandru-Dobre** [comment]
A retester. J'ai testé sur la v3-dev actuelle et ça ne se reproduit pas.

**Comment by 3AD** [comment]
Merci !
