### ISSUE TITLE
Rubedo for Beginners

### ISSUE THREAD

**Issue by logeshsundara** [WebTales/rubedo#1176]
Hi, Rubedo Stack seems to be an excellent one. As a developer I want to perform the following operations,
1. Add a JQuery Plugin to Rubedo and ability to use it from Rubedo BackOffice.
2. Customize AngularJS templates.

Is there any documentation/tutorial for a developer? 

I am confused, How can I extend / write new modules for Rubedo?

**Comment by goncalvesm** [comment]
Hi @logeshsundara,

Please do not open issues to ask a question. I answered you on the forum (http://forum.rubedo-project.org/viewtopic.php?f=32&t=350&p=1209#p1209)
