### ISSUE TITLE
Users are not filtered by workspace in the BO

### ISSUE THREAD

**Issue by goncalvesm** [WebTales/rubedo#1178]
I've created an admin in an isolated workspace and this admin can edit an another admin in the Global workspace. By default, the users that aren't in the workspace of the admin shouldn't be visible : 

![image](https://cloud.githubusercontent.com/assets/2509924/9633132/72eb76a8-518b-11e5-8741-e5da2f216705.png)

In this exemple i'm loged with adminsite3 (associated to the "site3" workspace) and i can edit admin and adminsite2 that are respectively in Global and site2 workspaces. Note that the groups are well filtered ...

**Comment by nicolasrhone** [comment]
In fact we can't modify the workspace of the users ! But only their groups... so they are always in the workspace of the user that created them...
It should be possible to modify the worskpace of users as for the contents.

**Comment by dfanchon** [comment]
#1179
