### ISSUE TITLE
it seems there is a display error in Content List block

### ISSUE THREAD

**Issue by iapsekian** [WebTales/rubedo#1180]
After upgrading to 3.2.x, I found there is a display error in Content List block. This problem happens during paging. Please see pic1 as below.
![pic1](https://cloud.githubusercontent.com/assets/8391917/9654636/a419f398-525e-11e5-890b-9a2413624ee4.png)
This is the data in page 1. After we switched to page 6 (in fact whatever page you switched), the title of content changed but the summary didn't. Please see pic2 as below.
![pic2](https://cloud.githubusercontent.com/assets/8391917/9654703/ff9e174e-525e-11e5-819b-2514e8600cf2.png)
You can compare pic1 and pic2 then found at the same position of the page, the title changed as expected but the summary was remaining the one of page 1. 
In the Rubedo Issue List, I found version 3.2 included an enhancement (#897). I'm wondering if this display problem is related to #897? Or this problem is independent? Or it happened just because of my setting problem?

**Comment by 3AD** [comment]
Thanks yeshijian.

complement: The summary is "attached" to the pagination of content list block and not its content.

**Comment by Alexandru-Dobre** [comment]
fixed in 3.3 and 3.2

**Comment by yeshijian** [comment]
I'm so sorry for bothering you again and just wondering how I can get those fixed codes for this issue?
