### ISSUE TITLE
Number of results to be displayed in Carousel Not working

### ISSUE THREAD

**Issue by gugan-mohan** [WebTales/rubedo#1198]
I have 42 contents and I select Number of results to be displayed  as 1 but still all the 42 results keep popping up. What went wrong???

**Comment by 3AD** [comment]
Hi gugan-mohan,
have you looked at the documentation ? we do not reproduce your bug.
http://docs.rubedo-project.org/en/homepage/build-rubedo-website/website/blocks-list-rubedo/546606da323f7912203dcca1/carousel
