### ISSUE TITLE
Une URL unique pour un contenu

### ISSUE THREAD

**Issue by ecuziat** [WebTales/rubedo#120]
Serait-il possible de pouvoir définir une URL unique pour un contenu par site.

Actuellement, en ouvrant un contenu depuis certaines listes, il ne s'ouvre pas dans son contexte d'origine mais dans le contexte depuis lequel il a été appelé.
Par exemple :
- à l'issue d'une recherche ;
- depuis un carrousel (le détail s'affiche en dessous du carrousel).

**Comment by jbourdin** [comment]
Pour cela, il faut attribuer le contenu à une page par la taxonomy de navigation. S'il est associé à une page du site courant, il s'affichera dans le contexte de cette page.

**Comment by ecuziat** [comment]
Merci Julien pour ce retour.
J'ai beau affecter le contenu à une page... Rien y fait.
J'ai du louper quelque chose !!!

![image](https://f.cloud.github.com/assets/3943473/293729/b70e93b8-93a8-11e2-81b3-bb0c883ed32f.png)

**Comment by jbourdin** [comment]
J'ai retesté, il y a bien un bug. :)

**Comment by jbourdin** [comment]
Corrigé dans la version 1.1.0.
Attention, il faut bien définir une colonne principale dans chaque masque pour éviter des cas où un contenu ne saurait pas où s'afficher.
