### ISSUE TITLE
Améliorations recherche par facettes

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1226]
Dans la recherche dans la BackOffice, si un champ de type Date est utilisé comme facette, c'est le timestamp qui s'affiche dans la recherche par facettes (et non la date lisible). De même si un champ lien vers contenu est utilisé comme facette, c'est l'ID du contenu qui est affiché (au lieu du titre du contenu par exemple)

**Comment by nicolasrhone** [comment]
Idem for combobox field (list of choice) : when used as facet, in the search (BO and FO), the value of the field is displayed instead of the name.

**Comment by dfanchon** [comment]
Done for date facet. Content Link duplicates #1341
