### ISSUE TITLE
add traduction keys - Status of Content contribution

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1235]
Le statut des contenus affichés en front sont uniquement en anglais (publish, draft)

**Comment by goncalvesm** [comment]
Fait

**Comment by 3AD** [comment]
le statut brouillon est toujours en anglais

**Comment by goncalvesm** [comment]
Non reproduit : 
![image](https://cloud.githubusercontent.com/assets/2509924/12138527/e821bc44-b459-11e5-9267-2b040c2afc61.png)

**Comment by 3AD** [comment]
![fireshot screen capture 248 - mes demandes - calais_rubedo-project_org_fr_ville-de-calais_mon-compte_mes-demandes](https://cloud.githubusercontent.com/assets/3063195/12138543/1f20cfaa-b45a-11e5-8f45-0e2be5c29c20.png)
Hum, peut être seulement sur ce site ?

**Comment by goncalvesm** [comment]
Il y a un gabarit personnalisé pour ce block, je vais le modifier mais il peut y en avoir d'autres.

**Comment by goncalvesm** [comment]
C'est fait.

Voici la ligne à remplacer au cas où j'en aurais oublié quelques uns : 
{{content.fields.text }} ( {{content.status}} ) :heavy_multiplication_x: 
{{content.fields.text }} ( {{rubedo.translate("Label." + content.status.toLowerCase())}} ) :heavy_check_mark:

**Comment by 3AD** [comment]
Merci !
