### ISSUE TITLE
Autentication block

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1244]
Le lien s'inscrire ne s'affiche pas en front-office sur le bloc d'authentification même si la page d'inscription est renseignée en bo sur le bloc

**Comment by Alexandru-Dobre** [comment]
done

**Comment by 3AD** [comment]
ok
Changer le wording Inscription

**Comment by Alexandru-Dobre** [comment]
done

**Comment by 3AD** [comment]
Merci !
