### ISSUE TITLE
Erreur modification de contenus avec champs multivalués en FO

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1246]
Dans le ContentDetailController.js à la ligne 90, il y a une erreur : il manque un transformForFront dans le cas de types de contenus avec un code. Du coup, les champs multivalués sont mal enregistrés lors de modifications

$http.get(themePath+'/templates/blocks/contentDetail/'+me.content.type.code+".html").then(
                                function (response){                                    me.detailTemplate=themePath+'/templates/blocks/contentDetail/'+me.content.type.code+".html";
                                },
                                function (response){
                                    me.detailTemplate=themePath+'/templates/blocks/contentDetail/default.html';
                                    $scope.fields=me.transformForFront(me.content.type.fields);
                                }
                            );

Il faut ajouter  $scope.fields=me.transformForFront(me.content.type.fields); dans la première function(response)

**Comment by Alexandru-Dobre** [comment]
corrigé
