### ISSUE TITLE
Delete a content from the detail view

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#1247]
For the moment, the only way to delete a specific content is by clicking on the checkbox on the row and then the Delete button, in the Contents application.
The problem is, when you have thousands of contents, finding a specific content in the content list is impossible (no search option in the Contents application)
You have to search for it, but you can't delete a content from the detail view.

Solution : add a "Delete" button on the detail view.

**Comment by Alexandru-Dobre** [comment]
Done
Same for media

**Comment by 3AD** [comment]
ok
