### ISSUE TITLE
[Multivalue][API Contents][Update] Delete a value of multivalue field 

### ISSUE THREAD

**Issue by akossentini** [WebTales/rubedo#1254]
When I try to update content by removing value of a MultiValue field, the content is outdated, because in the patchEntintyAction of Contents API , there is
https://github.com/WebTales/rubedo/blob/3.2.x/module/RubedoAPI/src/RubedoAPI/Rest/V1/ContentsResource.php#L589

<pre>
 $ content = array_replace_recursive ( $ content , $ data ) ;
 </pre>

It's add to my data that I wanted to remove

**Comment by Alexandru-Dobre** [comment]
fixed

**Comment by 3AD** [comment]
ok
