### ISSUE TITLE
Fix multivalued fields persistence

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#1258]

**Comment by 3AD** [comment]
Le champ url ne s'affiche pas en front si aucun titre n'est indiqué.
Si ce champ est multivalué :
-Saisie en back du champs url
-  Ajout du même champ avec la fonction multivaluée, puis saisie d'une url
- Publish, en front les 2 champs s'affichent
- Edition de ce contenu depuis le back, le contenu des 2 champs url ont disparus. L'url est remplacée par [object Object]

**Comment by Alexandru-Dobre** [comment]
fixed
