### ISSUE TITLE
Add hour/minute/second settings for all date fields in BO

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#1260]

**Comment by 3AD** [comment]
Pas d'affichage du champ en back sur Firefox
![fireshot screen capture 279 - rubedo - rubedo_local_backoffice](https://cloud.githubusercontent.com/assets/3063195/12452357/4ebe552c-bf8e-11e5-92ad-e3bf95f7ab3f.png).

Si ces éléments doivent être affichés en front, dans ce cas ce n'est pas le cas par défaut

**Comment by Alexandru-Dobre** [comment]
fixed for firefox
