### ISSUE TITLE
Bug taxonomie de navigation

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1268]
Lors de la création de requêtes ou dans l'onglet de taxonomie d'un contenu, la taxonomie de navigation n'est plus accessible.
De même en FO, dans CKEditor, pour le plugin rubedo-link

**Comment by 3AD** [comment]
Bonjour Nicolas, sur quelle version de Rubedo constatez-vous ce problème ?

**Comment by nicolasrhone** [comment]
Sur la 3.3.

**Comment by 3AD** [comment]
Nous ne reproduisons pas cette erreur sur la 3.3. êtes-vous sûr que la taxonomie de navigation est bien activée sur les types de contenu concernés ?

**Comment by nicolasrhone** [comment]
Oui, tout est OK de ce côté, d'ailleurs ce problème n'est arrivé que depuis moins d'une semaine.
En console j'ai une erreur qui vient de l'appel à : /backoffice/taxonomy-terms/navigation-tree?....
Mais si cela vient de mon côté, il faut peut-être plutôt m'adresser au support ?

**Comment by nicolasrhone** [comment]
Après quelques tests, il semble que l'appel à /backoffice/taxonomy-terms/navigation-tree fonctionne bien... mais met plus de 30s à répondre ! Du coup dans le backoffice rien ne s'affiche.

**Comment by nicolasrhone** [comment]
Réglé avec la dernière migration
