### ISSUE TITLE
Synchronise pages taxonomies when a new taxonomy is created

### ISSUE THREAD

**Issue by goncalvesm** [WebTales/rubedo#1269]
When i create a new taxonomy, i have to close and reopen pages window because the first time my new taxonomy is not displayed.

**Comment by Alexandru-Dobre** [comment]
Doing a form rebuild on store sync is very heavy and can cause render errors as well as loss of page taxonomy data. Current open/close workaround is not exactly gracious but it poses no threat to data integrity
