### ISSUE TITLE
Preview queries results

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1278]
Dans un bloc liste de contenus, un utilisateur qui a bien les droits d'édition et de visualisation des requêtes, mais pas d'administration de la plateforme, ne peut pas visualiser les resultats de la requête. 
On obtient l'erreur : "Impossible d'accéder à execute.controller.queries.simulate-result.backoffice"

**Comment by 3AD** [comment]
Impossible d'accéder à execute.controller.queries.simulate-result.backoffice s'affiche lors de la prévisualisation

**Comment by 3AD** [comment]
ok
