### ISSUE TITLE
Droits éditeur d'images

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1279]
Si l'utilisateur n'a pas les droits d'administration de la plateforme, il ne peut pas utiliser l'éditeur d'images : lorsque l'image est enregistrée, lors de la sortie de l'éditeur, il obtient le message : Impossible d'accéder à execute.controller.file.update.backoffice

Les modifications ne sont pas prises en compte.

**Comment by 3AD** [comment]
corrigé en 3.3.1
