### ISSUE TITLE
Rights for delete pages

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1281]
Pour le moment un utilisateur sans droits d'administration de la plateforme, mais avec droits d'édition des pages, peut créer des pages mais pas les supprimer. 
Le message d'erreur obtenu est : "Erreur dans la détermination du statut supprimable de la page"
Il faudrait soit lui donner le droit de les supprimer, soit créer un nouveau droit de suppression de pages.

**Comment by 3AD** [comment]
ok
