### ISSUE TITLE
Add Traduction keys rCommerce

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1284]
Détail de produit pour l'affichage des stocks sur le Product box en front: In stock : sent before 1 day

Expédition dans le checkout: Dans l'étape 5 pour la sélection de la livraison le nombre de jours affiché est en anglais.  Livraison sous 1 days pour 0 € 
Idem dans l'étape 6 le nombre de jours en en anglais.

**Comment by goncalvesm** [comment]
Corrigé
