### ISSUE TITLE
Content taxonomy and function copy content

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1309]
Les contenus copiés ne conservent pas la taxonomie

**Comment by 3AD** [comment]
Perte des termes de taxonomie lorsque l’on copie un contenu:

• Je rédige le Contenu 1. Il est taggué.
• Je copie le Contenu 1 pour créer un contenu 2. Les tags sont copiés en même temps.
• Je copie le Contenu 2.  Les tags conservés sont ceux du contenu 1 et non ceux du contenu 2

**Comment by Alexandru-Dobre** [comment]
fixed

**Comment by nicolastrenti** [comment]
Retesté de mon côté Audrey suite aux dernières corrections d'Alexandru et cette fois-ci ça semble effectivement bon

**Comment by 3AD** [comment]
ok
