### ISSUE TITLE
Problème d'import export de masque entre deux sites de nom différents

### ISSUE THREAD

**Issue by akhesaCaro** [WebTales/rubedo#1317]
Lorsqu'on fait un dump des masques et que l'on veut les réimporter dans rubedo il n'y a pas de problème, à condition que le nom du site soit le même entre le rubedo source et le rubedo cible..

Piste : j'ai remarqué que dans le json de dump du masque, il y a des éléments propres au site (exemple : "site":"56e83e6a48177e43108b4567") ce qui n'est pas le cas dans les dumps de type de contenu et de taxonomy qui fonctionnent très bien entre deux rubedos de nom différents.Toutefois, changer la valeur "site" dans le fichier ne suffit pas... j'ai essayé

Version du produit : 3.3.1
![mask_pweet](https://cloud.githubusercontent.com/assets/17886931/13828844/038d23d2-ebc4-11e5-98d4-f09362b653e1.png)

Il faut renommer le fichier mask_pweet.png en mask_pweet.zip (le zip ne passait pas)

**Comment by goncalvesm** [comment]
Bonjour Caroline,

Etant donné que les masques de page et les pages sont liés à un site, il est normal qu'a l'import celui-ci soit créé avec la référence de sont site. Dans votre cas les sites n'ont pas le même ID donc votre masque est bien importé mais n’apparaîtra pas dans l'interface du back-office car le site auquel il est associé n’existe pas.

**Comment by akhesaCaro** [comment]
Bonjour,

Merci pour la réponse rapide. Je vous explique notre problématique :

Nous avons notre client qui a son propre serveur de PROD.
Nous avons, pour nos développements, nos serveurs de développement.

Nous sommes donc dans une dynamique de dev->recette->livraison. Toutefois,
il ne nous est pas possible de livrer des masques de page à moins de le
faire directement en PROD (ce qui est exclue et trop risqué).

Bien que nous avons le même nom de site, à partir du moment où ce n'est pas
la même instance de Rubedo, l'import/export de masque ne fonctionne pas
(bien que celles de type de contenu et taxonomy fonctionnent).

Comment pouvons nous, faire les développements, les tester et ensuite les
livrer en production sans avoir d'intervention directement sur la prod?

Caroline GAUDREAU - Alyotech

2016-03-21 10:03 GMT+01:00 Goncalves Mickael notifications@github.com:

**Comment by goncalvesm** [comment]
Bonjour Caroline,

Rubedo est conçu pour gérer plusieurs sites à la fois. De ce fait, la majorité des éléments ne sont pas liés à un site et peuvent donc être réutilisé comme bon vous semble sur l'ensemble des sites de la plateforme (contenus, taxonomies, médias etc.). En revanche, les pages et les masques de page sont bien associées à un et un seul site, d'où votre problème.

Je pense que pour repartir sur de bonnes bases, vous devriez faire un dump (https://docs.mongodb.org/manual/reference/program/mongodump/) de votre base de données en production et la restaurer (https://docs.mongodb.org/manual/reference/program/mongorestore/) sur les environnements de dev/preprod afin que les ID des sites soient les mêmes sur les différents environnements. De ce fait, vous pourrez importer des pages et des masques de pages d'un environnement à l'autre sans problème.

**Comment by akhesaCaro** [comment]
Bonjour,

Votre solution n'est pas acceptable dans la mesure où je ne peux arrêter le
site en production de tourner entre le moment où je fais le dump , que je
crée les masques et que je refais le dump sur la PROD.

Je comprends que les pages soient liées au site, par contre je ne comprends
pas pourquoi les masques de page le sont forcément.

Je pense que c'est une feature intéressante à ajouter dans la mesure où je
ne suis pas la seule SSII à avoir cette procédure de livraison.

Caroline

2016-03-24 10:53 GMT+01:00 Goncalves Mickael notifications@github.com:

**Comment by goncalvesm** [comment]
Il est normal que les masques de page soient liés à un site. Par exemple, si vous créez un masque de page A que vous utilisez sur le site A et que vous y placez un bloc de menu configuré pour affichez les pages du site A, vous n'allez pas pouvoir réutiliser ce masque sur le site B qui ne possède pas la page configurée sur le bloc de menu. Vous allez donc devoir copier ce masque sur un autre site et modifier la configuration des blocs qu'il contient. Il serait logique de faire ce que vous demandez si les masques ne contenaient que des informations sur la structure de la page mais ce n'est pas le cas.

De plus, un dump de la base de données n’entraînera pas d'interruption de service. Je pense également qu'il y a eu une petite incompréhension sur le processus : 
- Dump de la PROD
- Restauration du dump sur les environnements de DEV/PREPROD
- Modifiez ou créez les masques de page sur DEV/PREPROD
- Utilisation de la fonction d'export dans le BO de DEV/PREPROD en sélectionnant la collection des masques de page
- Utilisation de la fonctionnalité d'import dans le BO de PROD en effectuant un UPSERT si il y a des mises à jour de masques de page existants ou INSERT si ce n'est que de la création

Notez que nous utilisons également le processus de livraison que vous décrivez ci-dessus (dev->recette->livraison) et nous n'avons pas de différences d'ID sur les sites entre les environnements car lors de la création d'un nouvel environnement, nous copions la base de données afin que les données soient cohérentes.
