### ISSUE TITLE
Users can not connect from the checkout block

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1319]
Dans la première étape du checkout il manque l'affichage en front du formulaire de connexion pour "Vous avez déjà un compte ?"

**Comment by goncalvesm** [comment]
Le fonctionnement du bloc était le suivant : 
- Le formulaire d'authentification ne s'affichait que si le champ "Texte d'inscription" était renseigné au niveau du bloc

Etant que le champ en question était utilisé pour la partie "Création de compte", j'ai retiré la condition sur le formulaire d'authentification et ajouté des dépendances manquantes au bloc.
