### ISSUE TITLE
Composite fields like the Free field are not returned in search

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#1332]

**Comment by dfanchon** [comment]
Did you check the "Return in Search" checkbox on back-office?

**Comment by Alexandru-Dobre** [comment]
Yes

**Comment by dfanchon** [comment]
The 'store' mapping configuration is visibly not taken into account on high level objects like composite fields. The only solution seems to get these fields directly from the _source field, but the 'return in search' option won't have any effect...
