### ISSUE TITLE
Add meta data og:image in page properties

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1334]

**Comment by dfanchon** [comment]
also add og:title and og:description

**Comment by 3AD** [comment]
Ajout d'un champ image Open Graph dans les pages et utilisation des metas des pages.
Pour les contenus, utilisation du champ image avec Open Graph activé. Utiliser le titre du contenu et son résumé pour la description.

**Comment by 3AD** [comment]
ok
