### ISSUE TITLE
RepeatedFieldController add buildFields() after moveUp() and moveDown()

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1335]

**Comment by Alexandru-Dobre** [comment]
Could you please elaborate ? I don't fully understand the what this issue is about

**Comment by nicolasrhone** [comment]
In a content contribution, edit mode, if you want to change the order of elements in a repeated field, you don't see the items changing the order, because there is no me.buildFields().

**Comment by Alexandru-Dobre** [comment]
Just tested with a repeated number field and it seems to work well. What type of field are you repeating ?

**Comment by Alexandru-Dobre** [comment]
This only seems to affect field types that have their own component scopes. Fixed by adding the me.buildFields() as you suggested. Thanks

**Comment by nicolasrhone** [comment]
Ok if I remember well it was as you said, with an embedded content field.
