### ISSUE TITLE
Checkout.html  bug in tCPageUrl link

### ISSUE THREAD

**Issue by EtienneLaval** [WebTales/rubedo#1340]
in line 577 of checkout.html

> ```
> <a ng-href="{{tCPageUrl}}" target="_blank">{{rubedo.translate('Blocks.Checkout.Label.TermsAndCondition')}} </a>
> ```

the link doesn't loads 'cause in CheckoutContrloller.js, this data is defined as me.tCPageUrl

> if (config.tCPage){
>         RubedoPagesService.getPageById(config.tCPage).then(function(response){
>             if (response.data.success){
>                 me.tCPageUrl=response.data.url;
>             }
>         });
>     }

i suggest you to call the controller instead of scope in the html file or define a $scope.tCPageUrl .
Thank you for your job !

**Comment by Alexandru-Dobre** [comment]
fixed in #1351
