### ISSUE TITLE
User with access to the backoffice can't change his own parameters

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1346]
Dans le menu "Paramètres" du BO, impossible de changer son propre mot de passe ou sa langue de travail !

**Comment by 3AD** [comment]
Bonjour Nicolas,

Je ne reproduis pas ce bug. Sur quelle version êtes-vous ?

**Comment by nicolasrhone** [comment]
Sur la v3-dev.
Avec un utilisateur qui a des droits spécifiques de création de contenus et d'édition des pages (pas de droits de modification des utilisateurs, ni d'administration de la plateforme).

**Comment by 3AD** [comment]
Bonjour Nicolas, je ne parviens pas à le reproduire.
J'ai testé avec un utilisateur ayant uniquement les droits suivants : accès parties publiques, accès BO, création de contenus, création de page. Pourriez-vous me préciser les rôles de votre groupe ?

**Comment by nicolasrhone** [comment]
Dans mon cas, les droits étaient ceux-là, avec d'autres en plus.
Je crois alors que le problème vient plutôt du fait de la gestion des espaces de travail sur les utilisateurs. J'ai créé l'utilisateur dans un espace spécifique (pas l'espace "public"). L'issue #1179 devrait sans doute régler ça.
