### ISSUE TITLE
Problème afficahege liste de contenu 

### ISSUE THREAD

**Issue by Nydareld** [WebTales/rubedo#1355]
La liste de contenu ne s'affiche pas pour les utilisateurs connectés du groupe public quand le paramètre "activer l'édition" du bloc "liste de contenu" est coché

**Comment by Alexandru-Dobre** [comment]
C'est normal : cette propriété passe la liste classique en une liste "mes contenus" destiné à la contribution de contenu en front.  Si l'utilisateur connecté n'a pas les droits nécessaires à la création de contenus la liste ne s'affiche donc pas
