### ISSUE TITLE
Checkbox mode on search page

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#1393]
Pour une recherche en mode checkbox, sur une facette en "OR", les termes non sélectionnés ne devraient pas disparaître.

**Comment by dfanchon** [comment]
Fixed. The bug was related to the "OR" condition on terms filters, not only in checkbox mode.

**Comment by nicolasrhone** [comment]
Same problem in the BO... In the facets configuration for search results or product search blocks, if you select 'OR' condition for a facet, and then select one of the facets, all non selected terms for this facet disappear.

**Comment by nicolastrenti** [comment]
OK pour le cas de test initial. La remarque de nicolasrhone a été reportée dans une nouvelle issue pour être traitée séparément : #1448
