### ISSUE TITLE
In contents interface, "Put Offline" button has no effect

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1402]
Si on sélectionne un contenu et qu'on clique sur le bouton "Mettre hors-ligne", le contenu est indiqué comme étant hors-ligne... mais est toujours visible sur le site !
Pour qu'il soit vraiment hors ligne il faut aller modifier les dates de publication...

**Comment by dfanchon** [comment]
Fixed in v3.4
