### ISSUE TITLE
Google Maps blocks - add API key

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1403]
Depuis le 22 juin 2016, l'utilisation de Google Maps API nécessite l'utilisation de la clé d'API. IL faut l'ajouter au script chargeant google maps : <script src="https://maps.googleapis.com/maps/api/js?key=yourKEYhere"></script>

Source  : http://googlegeodevelopers.blogspot.fr/2016/06/building-for-scale-updates-to-google.html

**Comment by Alexandru-Dobre** [comment]
fixed
