### ISSUE TITLE
Embedded content field

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#1407]
Cas de test : ajout d'un champ Embedded content (optionnel et sans multivaluation) dans un type de contenu existant.
- création d'un nouveau contenu depuis le BO et clic sur le champ Embedded content pour saisir des informations.
- le type de contenu Embedded ne s'affiche pas
- si l'on clique sur "Annuler" le back-office plante et doit être actualisé
- si l'on clique sur Draft, soumettre ou publier le contenu est créé, mais le back-office plante aussi

**Comment by Alexandru-Dobre** [comment]
Non reproduit

**Comment by 3AD** [comment]
Non reproduit
