### ISSUE TITLE
The order of the contents in a simple query isn't saved after its modification

### ISSUE THREAD

**Issue by goncalvesm** [WebTales/rubedo#142]
Si je change l'ordre d'un contenu dans la fenêtre d'édition de requête simple puis que je la ferme et la rouvre, l'ordre n'est pas pris en compte au niveau graphique mais l'est bien en base.

**Comment by Alexandru-Dobre** [comment]
lors d'un appel serveur avec filtre de type $in avec un tableau ordonné, l'ordre du tableau n'est pas pris en compte

**Comment by goncalvesm** [comment]
Fixed 82b23e3
