### ISSUE TITLE
Action SET invalide

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#1435]
Le philtre suivant ne fonctionne pas : 

`SET(USER.DATA.telechargement,1)`

On obtient une erreur 500 sur fingerprintdata, message : "property" is required

**Comment by nicolastrenti** [comment]
Il semble que : 
`SET('USER.DATA.telechargement',1)`
fonctionne (avec des guillemets)

**Comment by nicolastrenti** [comment]
Du coup, à l'heure actuelle, il faut écrire :  
`INC('USER.DATA.telechargement')`
(avec guillemets) mais
`INC(PAGE.NBVIEWS)`
(sans guillemets)

**Comment by Alexandru-Dobre** [comment]
Normalisé
