### ISSUE TITLE
Ajouter la variable TIME accessible dans les Philters

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#1439]
Ajouter une variable TIME qui renvoie le timestamp courant.
Objectif : pouvoir l'utiliser dans des philters du type : 

`IF USER.LASTVISIT AND (TIME - USER.LASTVISIT) > 24*3600*30 THEN SHOWMODAL('blockToDisplay')`

**Comment by Alexandru-Dobre** [comment]
TIME retourne la date courante en timestamp
