### ISSUE TITLE
Connexion back-office

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#144]
Bonjour,
J'ai installé Rubedo. Après une installation réussie et donc un account créé lors de l'une des étapes, j'arrive sur le formulaire de connexion au back-office. Seul problème la connexion ne marche pas, m'indiquant à chaque fois que le compte ou le mot de passe est erroné. Pourtant, après vérification, l'utilisateur est bien inscrit en base de données.
Y a-t-il une manipulation à faire ?
Merci d'avance.

**Comment by jbourdin** [comment]
A priori, il n'y a pas d'autre action à mener. 
Toutefois, j'ai oublié de faire un champ de confirmation de mot de passe, aussi il y a un risque de ne pas détecter une coquille en tapant le mot de passe à la création. (cf #103 )

Pouvez essayer de repasser dans l'install tool et créer un second compte en vérifiant bien votre mot de passe ? 

Cordialement

**Comment by jerem77** [comment]
Merci de votre réponse.
J'ai tenté de créer plusieurs comptes, mais le résultat est le même. Par contre, je n'ai pas rempli les formulaires pour les étapes "Mailer" et "Local domains", est-ce que cela a une importance ?
Cordialement.

**Comment by jbourdin** [comment]
Normalement, les étapes citées ne sont pas utiles pour une connexion au backoffice.

Le problème est soit lié à une absence de session PHP (cookie autorisé par le navigateur ?) soit à un souci de login/password.
c'est bien ce qui a été saisie dans "login" ou dans "email" qui doit être mis dans compte utilisateur, pas le nom complet.

**Comment by jerem77** [comment]
Les cookies sont bien autorisés et j'ai bien rentré le "login" et non pas le nom complet.
Le problème peut-il venir d'un problème au moment de l'installation de Rubedo ? Je pense notamment au fait qu'en utilisant la commande phing install-dev, les commandes pour composer.install-dev et composer.front.install-dev ne marchaient pas, j'ai donc récupéré les commandes du fichier xml, et les ai exécutés moi-même dans le dossier principal, et dans le dossier /public (en remplaçant composer par php composer.phar). Tout a bien marché et l'installation s'est déroulée par la suite correctement...

**Comment by jbourdin** [comment]
Le dialogue avec le server se fait par une requête sur .../backoffice/xhr-authentication/login avec en POST le login et le password.
La réponse est un JSON. Pouvez vous regarder si ce dialogue est conforme dans votre cas ? (réponse {'success':false} en cas de refus par le serveur).

Cordialement

**Comment by jerem77** [comment]
Les informations sont bien passées en POST, et j'obtiens bien en réponse {"success":false}

**Comment by jbourdin** [comment]
bizarre autant qu'étrange. :(

Les comptes apparaissent-ils bien dans la section Accounts de l'install tool ? (/install/index/set-admin)
Zone verte "Admin accounts exist :"

**Comment by jerem77** [comment]
Oui les comptes apparaissent bien dans un encart vert, même chose quand je créé un compte. Et tout est bien stocké dans "Users" dans la base de données.
Y a-t-il, sinon, un moyen de "contourner" cette authentification pour quand même accéder au back-office ?

**Comment by jbourdin** [comment]
non, il n'y a pas de contournement. (heureusement ?)

Pouvez vous créer un compte avec un mot de passe non confidentiel et me copier-coller le json de l'enregistrement créer en base ainsi que le mot de passe ? (le but est de vérifier que le hachage stocké est bien conforme).

**Comment by jerem77** [comment]
login   test
password    test

login=test&password=test

Réponse : {"success":false}

En base de données :
{ "_id" : ObjectId("515d4bae86c7477108000000"), "name" : "Test", "login" : "test", "password" : "287e0a4458054d44bde1185c075773dbac7c1c0307bb506e6e524801ca2aaf49811eef324f31779ce809e19bcdf78af7a4199eafe2efef6138fd54e2747fa54b", "email" : "xxxxx@free.fr", "salt" : "JdlF3e79KE", "defaultGroup" : "515d2bad86c747cd02000016", "groups" : null, "workspace" : [ "global" ], "version" : 1, "lastUpdateUser" : { "fullName" : "Rubedo", "id" : "rubedo", "login" : "rubedo" }, "createUser" : { "fullName" : "Rubedo", "id" : "rubedo", "login" : "rubedo" },

**Comment by jbourdin** [comment]
Re Bonjour,

Le hachage est bien valide en base.

Pouvez vous faire un `git checkout develop` et un `git pull`

Puis jouer les composer update. Cela vous mettra sur la dernière version de développement.
J'y ai ajouté un champ "msg" dans la réponse à l'authentification, cela pourra, je l'espère, nous mettre sur la piste du pourquoi la connexion est rejetée.

Merci de votre patience.

**Comment by jerem77** [comment]
Merci de votre réponse.
J'ai effectué l'ensemble des étapes que vous avez décrites, voici ce que me donne la réponse après soumission du formulaire :

{"success":false,"msg":"A record with the supplied identity could not be found.","exceptionClass":"Rubedo\Exceptions\User"}

**Comment by jbourdin** [comment]
Cela montre que le processus échoue au moment de trouver l'utilisateur en base, avant même de valider son mot de passe. 
cf https://github.com/WebTales/rubedo/blob/develop/Core/Rubedo/User/AuthAdapter.php#L87

Cela devient réellement étonnant si les données sont bien en base, dans la bonne collection, ce qui semble être le cas puisqu'elles sont vues par l'install tool.

Je suis démuni en ne pouvant que faire des conjectures à travers des commentaires. Je ne peux, à ce stade, que vous demandez de regarder ce qui se produit au long de cette fonction. :(

**Comment by jerem77** [comment]
Bonjour,
Je reviens vers vous après la résolution de mes problèmes, afin de vous faire part des solutions. Le problème venait en fait de la version de MongoDB que j'avais installée (trop ancienne). J'ai réinstallé la dernière version de MongoDB et tout fonctionne bien.
J'ai également eu un souci avec magic_quotes_gpc qui était initiallement et par défaut défini à On dans PHP (peut-être dû à Zend Server), ce qui provoquait des erreurs au moment de l'accès au back-office.
Merci en tout cas de votre accompagnement et du temps que vous m'avez accordé.

**Comment by jbourdin** [comment]
Bonjour,

Avec plaisir pour l'aide.
Concernant la version de MongoDB, pouvez-vous me dire quelle était celle-ci, je mettrai à jour les prérequis.

Pour magic_quotes_gpc, cela m'étonne que cela soit à On par défaut vu que ce paramètre est 'obsolete' en version 5.3 et a complètement été supprimé en version 5.4. En tout cas, merci pour le retour.

Bon usage de notre outil.

**Comment by jerem77** [comment]
La version que j'avais installée au début était la 1.4.4 il me semble. A l'installation de la version 2.4.1 tout fonctionnait correctement.
