### ISSUE TITLE
Image editor not working

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#1449]
Quand on modifie une image dans l'éditeur d'images, on a l'erreur : "Le contenu a été modifié, veuiller recharger celui-ci avant de faire cette mise à jour." et les modifications ne sont pas enregistrées.

**Comment by 3AD** [comment]
Bonjour Nicolas, vous remarquez ce problème dans quelle version de Rubedo ?

**Comment by nicolasrhone** [comment]
J'ai constaté ce problème sur la v3-dev.

**Comment by 3AD** [comment]
Merci Nicolas, je ne l'avais pas vu !

Erreur lors de l'enregistrement
