### ISSUE TITLE
Page dans le bloc de navigation

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#146]
Bonjour,
A moins que je ne me trompe, il n'est pas possible de mettre une page créé dans la barre de menu (c'est-à-dire la rattacher à la taxonomie Navigation) ?

**Comment by dfanchon** [comment]
Bonjour,
Il faut créer la page comme page fille de la page d'accueil du site. Vous pouvez aussi la déplacer par drag&drop.
La taxonomie de navigation est virtuelle, et générée automatiquement à partir de cette arborescence.
