### ISSUE TITLE
Suppression de taxonomie

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#147]
Si l'on créé une nouvelle taxonomie, et qu'on souhaite la supprimer par la suite, cela est impossible et une erreur apparaît : "can't destroy an object without a version number."

**Comment by jbourdin** [comment]
Confirmé.

Apparemment, cela se produit lorsque l'on vient d'ajouter un terme : celui-ci ne doit pas avoir un ID identifiant de version mis à jour dans l'interface.

**Comment by jerem77** [comment]
Je viens de remarquer que le beug apparaît également quand on souhaite supprimer 2 taxonomies à la suite : pour que ça marche, il faut supprimer d'abord une première taxonomie, fermer la fenêtre, la réouvrir, puis supprimer la seconde.
