### ISSUE TITLE
URLs propres pour page detail

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#149]
Bonjour,
Y a-t-il un moyen pour obtenir une URL propre pour la page d'un article par exemple plutôt que d'avoir une URL de type : detail?content-id=515ee24105c7576d17000005

**Comment by jbourdin** [comment]
C'est dans la roadmap. :)

**Comment by jerem77** [comment]
Savez-vous si cette réécriture d'URL sera disponible dans la prochaine mise à jour de Rubedo ?

**Comment by jbourdin** [comment]
Ce sujet sera traité après le passage à la version 2 de Zend Framework, cette migration imposant la réécriture de la gestion des URL pour coller avec les nouveaux Routeur de Zend.

La migration est prévu pour le début de l'été, la fonctionnalité sera donc postérieure, sauf dans le cas d'un développement financé.

**Comment by jerem77** [comment]
Bonjour à tous,
Je sais que ce ticket date de plus d'un an, mais j'aurais aimé savoir si vous aviez des avancées sur ce sujet ? Nous sommes en version 2.2 (donc migration vers Zend 2 effectuée) et pourtant, si je ne me trompe pas, ce "problème" est toujours présent.
Merci pour votre éclairage sur ce point.
Bon courage !

**Comment by dfanchon** [comment]
Bonjour,
Les url sont depuis le passage en 2.0 de la forme domaine/langue/detail/id_du_contenu/segment_url
ou le dernier segment est par défaut issu du titre et mais également paramétrable contenu par contenu.
A part l'id, qui a priori ne dégrade pas le SEO l'url est "propre". Le seul axe de progression serait de supprimer l'id, mais ça pose plus de problème que ça n'en résout.
