### ISSUE TITLE
Contenu texte riche

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#151]
Dans un bloc de type "Texte riche" situé dans une colonne, dans la rubrique "Masques de page", si l'on veut ajouter du contenu dans ce bloc, rien ne se passe au clic sur le bouton "Publier".

**Comment by jerem77** [comment]
Le problème est le même pour un bloc de type "Texte simple".

**Comment by jbourdin** [comment]
En effet, c'est correctement géré sur les pages mais cela ne l'est pas sur les masques.

**Comment by Alexandru-Dobre** [comment]
Le bug se produit sur quelle version de Rbedo? La version stable 1.0 ou la version Develop ?

**Comment by jerem77** [comment]
Version stable 1.0. Je n'ai pas essayé sur la version Develop

**Comment by Alexandru-Dobre** [comment]
Sur Develop ça à déjà été corrigé.
