### ISSUE TITLE
Modification de requête

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#152]
Dans "Masques de page", il n'est pas possible de modifier une requête déjà enregistrée sur un bloc de type "Liste de contenus" : l'écran "Loading" reste et ne disparaît pas. Il est alors nécessaire de rafraîchir la page.

**Comment by Alexandru-Dobre** [comment]
De quel genre de requête s'agit-il? Simple, manuelle ou avancée?

**Comment by jerem77** [comment]
Aussi bien sur les requêtes simples que sur les requêtes avancées d'après mes tests.

**Comment by Alexandru-Dobre** [comment]
Cela semble arriver lorsque la requête porte sur un vocabulaire qui a été supprimé. Était-ce bien le cas ? Sur quel navigateur avez vous testé? Merci

**Comment by jerem77** [comment]
Non, la requête ne portait pas sur un vocabulaire qui a été supprimé. Quant au navigateur, je suis sous Firefox.
J'ai pu relever le même problème quand j'ai voulu modifier une requête, directement depuis le menu "Requêtes" (dans "Administration")

**Comment by Alexandru-Dobre** [comment]
Ce bug n'a pas pu être reproduit sur la version actuelle de Rubedo. Il a du être corrigé lors de l'évolution de ce module dans la nouvelle release 1.1.0 et la branche develop.
