### ISSUE TITLE
Mise en avant du type de contenu à la sélection d'un article

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#153]
Dans la fenêtre Contenus, mettre en "surbrillance" le type de contenu qui a été sélectionné pour visualiser les contenus associés.

**Comment by Alexandru-Dobre** [comment]
C'est sur quel navigateur qu'il n'y a pas de surbrillance?

**Comment by 3AD** [comment]
Testé sur Firefox

**Comment by Alexandru-Dobre** [comment]
Cette perte de sélection est le résultat du rechargement de la liste des types de contenus suite à  édition dans leur module dedié

**Comment by Alexandru-Dobre** [comment]
Cela fait partie d'un sujet plus général concernant la persistance d'une sélection dans un module lors d'une synchronisation en provenance d'un autre module.
