### ISSUE TITLE
Requête avec limit

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#154]
Est-il possible d'effectuer des requêtes et de limiter le nombre de résultats retournés ? (par exemple n'avoir dans un bloc que les 3 derniers articles créés)

**Comment by goncalvesm** [comment]
Bonjour, vous pouvez effectivement définir une limite au niveau du bloc lui-même dans la section pagination puis taille des pages.

![pagination](https://f.cloud.github.com/assets/2509924/351386/48c461ba-a048-11e2-9969-c46141c97a9b.png)

**Comment by jerem77** [comment]
En effet, merci. Je m'attendais plutôt à définir cette limite lors de l'une des étapes au moment de la construction de la requête.

**Comment by goncalvesm** [comment]
Nous avons décidé de ne pas définir une limite au niveau de la requête car les requêtes avancées sont réutilisables. De ce fait, une requête peut être utilisée plusieurs fois avec une configuration différente.

Nous allons enrichir les options de configuration des blocs pour la prochaine version afin d’éclaircir ce point.

Merci pour votre retour.
