### ISSUE TITLE
Ajout de taxonomie lors de la création d'images

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#163]
Lorsque l'on souhaite ajouter un ou plusieurs termes de taxonomie 
- la liste des termes s'affichent en dehors de la fenêtre de paramétrage du média
- lorsque l'on veut ajouter des termes à une taxonomie située en bas de la fenêtre, la fenêtre remonte au début de la page.

**Comment by Alexandru-Dobre** [comment]
ce bug est du au framework js actuel et sera probablement corrigé lors de la migration Ext 4.1.1 -> Ext 4.2.0
