### ISSUE TITLE
Url des contenus conservent la recherche 

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#170]
Lorsque l’on accède à un contenu à partir de la recherche, l’url de ce contenu est de type : http://demoadmin.rubedo-project.org/recherche?content-id=5166d0142a804f564200006b

**Comment by jbourdin** [comment]
Pour éviter cela, il faut soit définir une page associée au bloc recherche soit que le contenu soit associé à une page dans la taxonomie de navigation.
