### ISSUE TITLE
Modification de la taxonomie d'un média

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#174]
Il n'est pas possible d'éditer une taxonomie sur un média déjà créé : le clic sur le bouton "Enregistrer les modifications" ne réalise aucune action

**Comment by Alexandru-Dobre** [comment]
Pourriez-vous me préciser la version de Rubedo utilisée ainsi que le type de média ? Merci

**Comment by jerem77** [comment]
Version 1.0.0, et il s'agit d'un type de média que j'ai moi-même créé (de type Image)

**Comment by Alexandru-Dobre** [comment]
Ce bug a déjà été corrigé sur la branche develop et donc dans la prochaine release 1.1.0
