### ISSUE TITLE
Lien vers un média

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#179]
Bonjour,
Est-il possible dans un bloc de type "Texte riche" de faire un lien vers un média ?
Exemple d'application  : "Consulter le compte-rendu" -> "compte-rendu" serait un lien qui pointerait vers un document PDF uploadé dans la médiathèque.

**Comment by goncalvesm** [comment]
Bonjour,

Actuellement il n'est pas possible d'ajouter un lien vers un élément de la médiathèque pour le télécharger. Nous travaillons sur plusieurs types de blocs qui le permettrons par la suite.

De plus, la version 1.1.0 de Rubedo sortira le 22 avril et corrigera les bugs que vous nous avez remonté. Nous avons aussi mis en place un forum depuis la semaine dernière, donc si vous avez des questions n'hésitez pas a poster dessus : http://forum.rubedo-project.org/ (la roadmap est proposée dans la section idées & request)

Merci !
