### ISSUE TITLE
Facette "Type de document" dans la médiathèque

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#183]
J'ai 1 vidéo et 15 images dans ma médiathèque (il s'agit types de médias par défaut).
Pourtant, dans la colonne de gauche de la médiathèque, au niveau des facettes "Types de documents", j'ai
- Image (1)
- Image (15)

Le libellé de la 1ère facette est donc faux.

**Comment by Alexandru-Dobre** [comment]
Les noms des facettes son retournés ainsi par le serveur. Dans mon test, un type de média nommé "ImageTest" a comme nom de facette "Image".
