### ISSUE TITLE
Attribut height img

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#184]
Bonjour,
L'attribut "height" de la balise img est mal orthographié : il est écrit "heigth" à la place.
Ce bug apparaît dans un bloc de type "Galerie d'images" qui récupère un ensemble de médias de types Images. 
Cette erreur d'orthographe empêche de plus la bonne validation W3C.

**Comment by goncalvesm** [comment]
Bonjour, merci d'avoir remonté ce bug pas évident à trouver !

C'est corrigé pour la prochaine version !
