### ISSUE TITLE
Import : erreur non remontée

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#191]
Erreur relevée dans la console lors de l'import d'un fichier CSV (l'erreur n'est pas remontée dans l'interface) :

Uncaught Ext.JSON.decode(): You're trying to decode an invalid JSON String: 

```
Application error



non-utf8 string: Rapha�l  






            More info 





            Stack trace:
            #0 C:\projets\rubedo\Core\Rubedo\Mongo\DataAccess.php(564): MongoCollection->insert(Array, Array)
```
#1 C:\projets\rubedo\Core\Rubedo\Mongo\WorkflowDataAccess.php(285): Rubedo\Mongo\DataAccess->create(Array, Array)
#2 C:\projets\rubedo\Core\Rubedo\Collection\AbstractCollection.php(341): Rubedo\Mongo\WorkflowDataAccess->create(Array, Array)
#3 C:\projets\rubedo\Core\Rubedo\Collection\WorkflowAbstractCollection.php(91): Rubedo\Collection\AbstractCollection->create(Array, Array)
#4 C:\projets\rubedo\Core\Rubedo\Collection\Contents.php(234): Rubedo\Collection\WorkflowAbstractCollection->create(Array, Array, false)
#5 C:\projets\rubedo\application\modules\backoffice\controllers\ImportController.php(258): Rubedo\Collection\Contents->create(Array)
#6 C:\projets\rubedo\vendor\bombayworks\zendframework1\library\Zend\Controller\Action.php(516): Backoffice_ImportController->importAction()
#7 C:\projets\rubedo\vendor\bombayworks\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('importAction')
#8 C:\projets\rubedo\vendor\bombayworks\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 C:\projets\rubedo\vendor\bombayworks\zendframework1\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 C:\projets\rubedo\vendor\bombayworks\zendframework1\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 C:\projets\rubedo\public\index.php(60): Zend_Application->run()
#12 {main}

**Comment by jbourdin** [comment]
Les messages d'erreurs sont maintenant corrects, sauf dans le cas, comme-ci dessus, où l'anomalie vient d'un charset faux dans l'import.

Idéalement, il faudrait soit dectecter le charset soit demande de le choisir dans l'assistant.

**Comment by jbourdin** [comment]
a traiter en même temps que la mise à jour du processus d'import

**Comment by jbourdin** [comment]
Fixed
