### ISSUE TITLE
BO : choix taxonomie à la création d'un contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#198]
Lors de la création d'un contenu, lorsque l'on veut ajouter des termes de taxonomie, l'affichage propose des scrollbar

**Comment by 3AD** [comment]
![FireShot Screen Capture 014 - Rubedo - demoadmin_rubedo-project_org_backoffice](https://f.cloud.github.com/assets/3063195/410094/16bb7aa0-ab65-11e2-87f4-66069768775c.png)

**Comment by Alexandru-Dobre** [comment]
J'ai fait un fix sur ce composant.
Ça semble corrigé mais il faudra le tester d’avantage pour en être sur.
