### ISSUE TITLE
Chargement javascript

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#200]
Bonjour,
J'ai installé la nouvelle mise à jour 1.1 Rubedo. Mais depuis, dans le backoffice, à l'ouverture d'une page, le chargement est très lent, et une pop-up navigateur m'indique que le script ne répond plus : j'ai alors le choix de stopper le script ou de continuer. Si je continue, le chargement est ensuite très très lent, si je l'arrête je ne peux plus accéder aux pages.
Script à /components/sencha/extjs/ext-all-debug.js:13224
(J'ai activé le debug mode de ExtJs)

NB : Après avoir réessayer, cette fois ça indique le problème à la ligne 41945 du même fichier
NB2 : Maintenant ligne 37010...

**Comment by Alexandru-Dobre** [comment]
Bonjour. Sous quel navigateur avez-vous testé?

**Comment by jerem77** [comment]
Sous Firefox.
J'ai également testé sous Chrome : il ne m'affiche pas la petite pop-up mais toute l'exécution est très longue aussi...

**Comment by Alexandru-Dobre** [comment]
Le problème est corrigé. Le niveau de zoom est maintenant réglable et le moteur de rendu/sélection est bien plus fluide. Merci d'avoir signalé ce bug.
La correction est disponible sur la branche develop et sera incluse dans la release 1.1 stable avant la fin de la semaine (la mise à jour que vous avez installé est juste la RC1 de la 1.1)
