### ISSUE TITLE
URL absolue d'une image dans un bloc

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#210]
Dans un bloc de type Texte riche, en ajoutant une image à travers CKEditor, après avoir choisi l'image, c'est l'URL absolue de l'image qui est enregistrée, de type : http://nom_de_domaine/image?file-id=...
Seulement, si je migre mon serveur ou que je change de nom de domaine, les URLs sont alors fausses et ne s'affichent plus dans les blocs.

**Comment by jbourdin** [comment]
C'est normalement déjà corrigé dans la version de développement et cela sera dans la 1.1.0. L'URL stockée ne contient pas le nom de domain, seulement le chemin.

Par contre, pour les contenus existant, il faudra malheureusement corriger ceux-ci manuellement.
