### ISSUE TITLE
Enregistrement de certains champs en FO

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#214]
Le workflow n'est pas respecté à l'enregistrement en FO du champ nombre.

Exemple 
- mon contenu a un champ nombre avec la valeur 500
- je modifie en FO, je le passe à 50
- je sauvegarde
- je réaffiche mon contenu, la valeur est bien à 50
- je consulte mon contenu en BO, la valeur est toujours à 500

**Comment by goncalvesm** [comment]
Deux requêtes différentes sont utilisées pour enregistrer un nombre et d'autres champs, de ce fait, la dernière requête réécrit sur les changements apportés par la première. Nous allons faire en sorte de n'utiliser qu'une requête pour mettre à jour un contenu.
