### ISSUE TITLE
Pas de prise en compte du changement de nom d'un utilisateur

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#219]
Lorsqu'un utilisateur change de nom, les contenus conservent l'ancien nom de l'auteur.

**Comment by jbourdin** [comment]
Le nom est stocké au moment de l'écriture. Cela n'est pas une base relationnelle.

En échange on conserve le nom à la suppression du compte

Le 25 avr. 2013 à 13:44, "3AD" <notifications@github.com<mailto:notifications@github.com>> a écrit :

Lorsqu'un utilisateur change de nom, les contenus conservent l'ancien nom de l'auteur.

**Comment by 3AD** [comment]
ok. merci
