### ISSUE TITLE
Comptes et groupes utilisateurs

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#221]
Lorsqu'un groupe est ajouté dans le profil d'un utilisateur, cet utilisateur n'est pas affiché dans le groupe concerné.

**Comment by goncalvesm** [comment]
Je n'ai pas réussi à reproduire ton bug, à réouvrir si ça persiste.

**Comment by goncalvesm** [comment]
Le bug intervient quand on crée un nouveau groupe et qu'on lui affecte un utilisateur avec la fenêtre des utilisateurs ouverte en même temps.

**Comment by Alexandru-Dobre** [comment]
Le plantage de la fentre a été corrigé
