### ISSUE TITLE
Type de contenu événements, pas de durée

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#237]
Les événements nécessitent la prise en compte d'une date de début et d'une date de fin.

**Comment by Alexandru-Dobre** [comment]
Il s'agit d'un bug du twig de rendu ou du module des types de contenus ?

**Comment by 3AD** [comment]
En fait il s'agit de modifier le contenu Événement qui est proposé par défaut dans Rubedo. Et de lui ajouter un champ date de début et un champ date de fin.
La vue calendrier doit également prendre en compte la durée des événements.
