### ISSUE TITLE
Impossible d'enregistrer des modifications à un type de contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#240]
Lors de l'ajout d'une taxonomie à un type de contenu existant, il n'est pas possible d'enregistrer les modifications. 
Il n'y a pas de messages d'erreur.

Site Rubedo-project.org 
Type de contenu : Tutoriels

**Comment by goncalvesm** [comment]
Non reproduit, à réouvrir si tu le rencontre encore.
