### ISSUE TITLE
Champ Texte riche, pas de changement du mode

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#242]
Le mode du RTE  (barre des boutons) est bloqué sur Standard.. Les autres modes ne modifient pas la barre.

**Comment by Alexandru-Dobre** [comment]
Dans quel contexte cela arrive-t-il?

**Comment by 3AD** [comment]
Pour l'édition en front

**Comment by Alexandru-Dobre** [comment]
j'ai testé les trois modes de configuration et cela marche parfaitement en back et en edition front
le problème a du etre corrigé entre l'ouverture du bug et mes tests
