### ISSUE TITLE
URL absolue lien interne

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#243]
En faisant un lien interne vers une autre page du site, l'URL absolue (avec le nom du serveur) est enregistrée : en cas de changement du nom de serveur dans Sites, les URLs ne sont pas modifiées et produisent ainsi des liens morts.

**Comment by jbourdin** [comment]
Effectivement, en l'état, cela est un problème. Celui-ci est connu de notre côté, ainsi que celui de lien vers un contenu qui est encore plus complexe (notion de page d'affichage associée).

Concrètement, nous allons faire une passe de conception sur le sujet puisqu'il ne faut pas stocker le lien mais les informations de relation dans la base de données.

Ce point est dans le backlog du produit, nous le traiterons lorsque cela sera possible.
