### ISSUE TITLE
update content-type fail

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#244]
backoffice/content-types/is-changeable is not responding when there is a lot of contents (> 150000). Reason : Count on content-type is done by getService('Contents')->getListByTypeId retrieve all results ! should be done by ->count() on content type collection

**Comment by jbourdin** [comment]
I'll add this point to the upcoming code-review. It is a bad pattern indeed.

If we need to know if there is some content of this type, we should neither do a find or a count but simply a findOne.

**Comment by Alexandru-Dobre** [comment]
backoffice/content-types/is-changeable also causes notices sometimes while retrieving the read-only status of contents

This actions should not calculate the readOnly status of any content .
