### ISSUE TITLE
Workflow : pas de prise en compte de l'état

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#245]
Les contenus en attente de validation sont affichés en FO.

**Comment by Alexandru-Dobre** [comment]
Bonjour
J'aurais besoin de plus de précisions (type de contenu, bloc utilisé pour l'affichage en front, worlflow utilisé sur le type de contenu, mode draft (ou pas) de la preview). Merci

**Comment by 3AD** [comment]
Tous types de contenu, bloc liste simple ou avancée et le workflow de Rubedo
