### ISSUE TITLE
Questionnaire bouton qui ne s'affiche pas

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#246]
Sur Firefox :
Le bouton + pour ajouter des choix dans les éditeurs de questions n'apparaissent pas.

**Comment by Alexandru-Dobre** [comment]
je n'arrive pas à repoduire ce bug sous firefox
il devrait s'agir d'un problème de cache du navigateur utilisé pour le test.
Vider ce cache devrait sans doute resoudre le problème
