### ISSUE TITLE
Filtres contenu

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#248]
Bonjour,
Est-il possible d'afficher sur le site un système de filtre pour permettre par exemple à un utilisateur de trier une liste de contenus par date (avec des listes déroulantes par mois par exemple) ? 
Il me semble que non, mais j'aurais aimé savoir si cela était prévu ?
Merci

**Comment by Alexandru-Dobre** [comment]
Bonjour,
Pour l'instant il n'est pas prévu de rajouter des filtres ou du tri en front-office pour l'utilisateur dans un bloc "Liste de contenus". Cependant, le bloc "Agenda" propose déjà les fonctionnalité nécessaires pour ce besoin en affichant une liste de contenus pilotée par un calendrier.
