### ISSUE TITLE
Double slash dans l'URL

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#249]
Bonjour,
En effectuant des liens internes vers d'autres pages du site, les URLs construites contiennent 2 slashs à la suite après le nom du serveur : pour quelle raison ?
Cela est problématique avec le formulaire de contact disponible depuis le BO de Rubedo.
Depuis la page d'accueil, je clic grâce à un lien interne vers la page Contact, mon lien sera le suivant : http://rubedo//contact
Or, si j'essaye de valider mon formulaire sur la page contact, avec une URL comme celle-là, cela provoquera une erreur.

**Comment by jbourdin** [comment]
Bonjour,

C'est probablement un bug. On le corrigera dès possible

**Comment by jbourdin** [comment]
fixed
