### ISSUE TITLE
Corriger l'affichage preview-responsive

### ISSUE THREAD

**Issue by jbourdin** [WebTales/rubedo#25]
Les chemins vers les CSS sont brisés
A tester en HTTPS

**Comment by Alexandru-Dobre** [comment]
css ok, https pas encore testé

**Comment by Alexandru-Dobre** [comment]
le site ne s'affiche pas en https (meme en dehors du responsive)
P.S. le notice suivant gene la mise à jour des sites :
 Notice: Undefined index: readOnly in/home/dobrea/Documents/Workspace/rubedo/Core/Rubedo/Collection/Pages.php on line 359
