### ISSUE TITLE
Problème d'accès à un questionnaire

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#257]
De temps en temps, sur Firefox, en étant connecté depuis le back-office, au moment d'accéder en FO à une page contenant un questionnaire une erreur apparaît : 

Forbidden
can't update an object without a version number

Bizarrement, l'erreur n'apparaît pas tout le temps, et n'a pas l'air d'apparaître sous les autres navigateurs...

**Comment by Alexandru-Dobre** [comment]
Bonjour,

Je n'arrive pas à reproduire ce bug sur la branche develop. Pourriez-vous préciser la version de Rubedo utilisée pour le test?
Ce bug pourrait arriver lorsque vous êtes connecté sur plusieurs onglets ou navigateurs et que vous complétez le même questionnaire simultanément. Est-ce le cas?

**Comment by jerem77** [comment]
Pour le test, la version utilisée est la 1.1.
En effet, cela se produisait alors que j'étais connecté au site sur plusieurs navigateurs...

**Comment by Alexandru-Dobre** [comment]
Dans ce cas le fonctionnement est normal au sens de l'Optimistic Locking. Le numéro de version d'une entité est incrémenté à chaque update donc si l'entité est en édition sur plusieurs onglets ou navigateurs cette erreur peut se produire. Dans ce cas, l’entité en question est le résultat du questionnaire. 
Par contre le message d'erreur reçu n'est pas le bon (ce n'est pas le seul cas ou ça arrive, c'est un bug plus général sur la gestion de ce genre d'erreur. Le bon message serait plutot: "Cet élément a déjà été modifié depuis son ouverture. Il est nécessaire de le recharger avant de le modifier à nouveau"
