### ISSUE TITLE
Pourcentage de pertinance en BO

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#259]
En back-office, en effectuant une recherche (avec le formulaire en bas à droite), tous les résultats semblent avoir une pertinence de 100 (dernière colonne) peu importe les filtres, la recherche etc...

**Comment by dfanchon** [comment]
A vérifier, mais c'est le score par défaut remonté par Elastic Search. Pour l'instant seuls les résultats mettant en oeuvre de la recherche full-text sur des fichiers binaires remontent autre chose que 100%. Il est possible de paramétrer finement les critères de pondération du scoring ES, nous traiterons ce point dès que possible.

**Comment by jerem77** [comment]
Effectivement il n'y a pas que des 100% en pertinence... autant pour moi
