### ISSUE TITLE
Edition FO champ Groupe de cases à cocher

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#266]
J'ai un type de contenu avec un champ "Groupe de cases à cocher" obligatoire.
J'édite un contenu de ce type en FO. Je ne coche aucune des cases à cocher.
Au lieu d'avoir un message d'erreur utilisateur lors de la validation pour m'informer que ce champ est obligatoire, j'ai un message "Une erreur est survenue, il est possible que vos modifications soient perdues".

**Comment by Alexandru-Dobre** [comment]
Il s'agit d'un souci général de l'édition front
Il faut appliquer à chaque champs les validateurs nécessaires en se basant sur le type de contenu

**Comment by Alexandru-Dobre** [comment]
Ce bug est inclus dans une tache plus vaste : la restructuration de l'édition front. Ce sera corrigé dans la prochaine release.
