### ISSUE TITLE
Médiathèque : intitulé de colonnes

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#270]
Les intitulés de colonnes "Titre", "Auteur", "Date de création" ne doivent être affichés que si on est en mode d'affichage "Détail".
![media](https://f.cloud.github.com/assets/1919354/547070/34298a32-c2b7-11e2-9b1a-20b1f8483cfd.jpg)

**Comment by Alexandru-Dobre** [comment]
L'affichage de ces colonnes est nécessaire au bon fonctionnement de la grille que que soit son mode d'affichage. Elles permettent d’ailleurs le tri et groupement qui sont intéressants même en vue "Détail"
