### ISSUE TITLE
Libellés non traduits

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#272]
Les libellés suivants n'ont pas été traduits dans le BO :
- Pour les médias, comment gérer les fields de chaque média par défaut comme "alternative textuelle" ?
- Groups : les libellés des groupes créés par défaut lors de l'install ne sont pas traduits
- A la création d'un site, les objets créés ne sont pas traduits (ex. : les pages, les masques, les blocs insérés par défaut dans les pages, ...)
- Users > Information : la liste des valeurs pour la civilité n'est pas traduite
- Media types > Onglet "Edit" > Au survol des icônes [i], on a des tooltips du type "Texte proposé en substitution de l'image"

**Comment by Alexandru-Dobre** [comment]
Les bugs de l'interface ont été corrigés. Ceux qui restent relèvent du serveur ou bien du multilinguisme des données.

**Comment by goncalvesm** [comment]
Les derniers éléments restants ne sont pas localisables actuellement.

**Comment by jbourdin** [comment]
Normalement tout est corrigé en dehors des civilités. Une issue Atlassian traite le sujet.
