### ISSUE TITLE
Workflow refuser contenu

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#286]
Avec un compte valideur, je souhaite refuser un contenu "en attente de validation". Au clic, l'erreur suivante apparaît : "Address in mailbox given [] does not comply with RFC 2822, 3.6.2".
Puis si je retente, l'erreur qui apparaît est "fail to update"

**Comment by jerem77** [comment]
Je viens de m'apercevoir que l'erreur n'apparaît pas quand le serveur SMTP Mail est bien configuré

EDIT : de plus, il est possible de passer un contenu déjà publié en brouillon, son état change dans le BO mais le contenu reste affiché en FO. Le plus logique serait d'enlever les boutons Brouillon et Soumettre une fois le contenu publié.

**Comment by jbourdin** [comment]
L'option "Enable email notifications" dans l'install tool ne doit être activé qu'une fois le SMTP activé dans l'étape "Mailer Configuration" et doit être combinée avec "Sender of notifications". Il y a en effet risque d'erreur sinon.

Pour le second point, attention, on ne repasse un contenu en "brouillon", on créer un brouillon d'une seconde version du contenu. Il y a alors un workflow déclenché pour la nouvelle version. Lors de la publication de la nouvelle version, celle-ci remplacera l'ancienne.
