### ISSUE TITLE
Pas d'uplaod des images en front

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#287]
dans l'édition d'un contenu en front, lorsque l'on souhaite ajouter une image qui n'est pas dans la médiathèque , la fonction envoyer sur le serveur ne fonctionne pas.

**Comment by goncalvesm** [comment]
Nous avons retiré l'onglet en attendent de savoir ce qu'on en fait.

**Comment by 3AD** [comment]
Il reste l'onglet pour l'uplaod en back-office depuis le RTE

**Comment by goncalvesm** [comment]
Je ne retrouve pas l'onglet, où est-il exactement ?

**Comment by 3AD** [comment]
Création ou édition d'un contenu depuis le back. Ajout d'une image.

**Comment by goncalvesm** [comment]
Ah en back ! je cherchais en front !
