### ISSUE TITLE
Pas de persistance des requêtes et non enregistrement

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#291]
Lorsque l'on paramètre une requête simple, celle-ci ne s'enregistre pas.

Lorsque l'on ajoute une requête simple dans une page et qu'on l'enregistre, lorsque l'on revient sur cette page, la requête n'est plus affichée en BO.

**Comment by 3AD** [comment]
Idem pour les autres requêtes

**Comment by Alexandru-Dobre** [comment]
Le bug ne semble pas reproductible. Avec quel compte ces tests ont-ils été effectués?

**Comment by 3AD** [comment]
Testing.
J'ai encore le même bug ce matin.. Page géoloc, création d'une requête simple, on me propose d'enregistrer sans me demander de saisir un titre à la requête.

**Comment by Alexandru-Dobre** [comment]
Les requêtes simples et manuelles n'ont pas de titre. Elles sont liées au bloc. Seules les requêtes avancées ont des titres et peuvent etre utilisées et réutilisées dans plusieurs blocs. 
Il pourrait s'agir d'un problème de droits (pas ledroit de créer/éditer des requêtes) .

**Comment by 3AD** [comment]
ben ça ne marche pas quand même ^^

**Comment by Alexandru-Dobre** [comment]
Ce correctif devrait régler le problème sur les navigateurs lents. Il faudrait retester
