### ISSUE TITLE
Téléchargement de média

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#294]
Lorsque l'on clic sur le bouton de téléchargement, le média s'affiche. Celà ne déclenche pas son téléchargement.

**Comment by goncalvesm** [comment]
Quel est le type de média concerné ? (image, vidéo etc) et sous quel navigateur as-tu rencontrée ce bug ?

**Comment by 3AD** [comment]
pour une image. L'image remplace la page du site sur laquelle le média est proposé

**Comment by goncalvesm** [comment]
C'est corrigé.
