### ISSUE TITLE
default number of column is sometimes forgotten

### ISSUE THREAD

**Issue by jbourdin** [WebTales/rubedo#300]
Some "dived by zero can appear, probably a "cols number" not push in ajax mode

**Comment by goncalvesm** [comment]
Normally fixed 5171559, can you check on your environment ?

**Comment by goncalvesm** [comment]
This bug append when you are not connected but it seems that the value is sent :/. I don't know why the "columns" field disapear betwen the controller en the view when we are not connected. Do you have an idea ?

**Comment by goncalvesm** [comment]
Fixed
