### ISSUE TITLE
User language is not changed after account update

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#303]
Actuellement, lorsqu’un utilisateur change sa langue dans le back, il faut se déconnecter et se reconnecter pour que la méthode getLanguage du service currentUser renvoie la bonne langue. En conséquence, toute l'interface passe dans la nouvelle langue mais la locale Ext (format des champs date notamment) et des libellés en provenance du serveur(Tous les sites, Page courante, etc.) ne passeront pas dans la nouvelle langue sans une déconnexion et une reconnexion.

**Comment by goncalvesm** [comment]
Fixed
