### ISSUE TITLE
Taxonomy facets missing in DAM

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#308]
Si pour un vocabulaire donné seul un de ses termes est affecté à plusieurs médias, la facette de ce vocabulaire ne s'affiche pas dans la DAM. Il suffit d'affecter un autre terme de ce vocabulaire à n'importe quel média pour que la facette devienne visible.

**Comment by Alexandru-Dobre** [comment]
Après quelques tests, je vois la même chose sur les contenus. C'est donc une anomalie de la recherche en général.

**Comment by dfanchon** [comment]
autre test sur la démo : si on ajoute à l'actualité tulipes un terme d'une nouvelle taxonomie (par exemple fruits) le terme ne génère pas de facette dans la recherche (testé seulement en BO)
