### ISSUE TITLE
Problème sur la vue détaillée d'un contenu affiché dans un googleMap

### ISSUE THREAD

**Issue by goncalvesm** [WebTales/rubedo#311]
Le bloc googleMap ne possède pas d'option de configuration pour désigner une page afin d'afficher le détail d'un contenu. Si ce contenu ne possède pas de taxonomie de navigation et que la page n'a pas de colonne principale, le contenu ne s'affiche pas sur la page de détail par défaut du site !

La page se recharge sur la page courante et rien ne se passe.

![image](https://f.cloud.github.com/assets/2509924/631239/58864eba-d1c1-11e2-9b4d-65709b1eb7a2.png)

**Comment by Alexandru-Dobre** [comment]
Le moyen de récupération de l'url est le meme que dans tout le front (le getUrl dans le twig) . Le problème est donc général.
