### ISSUE TITLE
Traduction anglais

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#326]
En étant connecté dans le back-office en version anglaise :
1. En ouvrant la fenêtre "Contents", le bouton "Edit" est bien traduit en anglais.
   Après, si je sélectionne un ou plusieurs contenus, le bouton "Edit" devient "Modifier" alors que les autres boutons restent bien en anglais
2. Dans la partie "Surveys", onglets "Properties" d'un questionnaire, les libellés sont bien traduits en anglais. Cependant si je coche la case "Uniqueness of the answer", un nouveau champ apparaît en dessous et son libellé est en français ('Déjà répondu")
3. Si je souhaite éditer une image, j'accède à l'édition d'images : cette "plate-forme" est en français alors que j'étais en anglais dans le back-office
4. Dans CKEditor, au survol du bouton "Lien interne", le libellé est en français (les autres libellés sont bien traduits)

**Comment by nicolastrenti** [comment]
Point 1 : toujours d'actualité
Point 2 : toujours d'actualité
Point 3 : toujours d'actualité
Point 4 : toujours d'actualité

**Comment by Alexandru-Dobre** [comment]
1 et 2 OK
3 -> le Pixlr utilise la langue du navigateur, il ,n'est pas possible de passer la langue en pramètre
4 -> moteur de localisation de CKE défectueux, il sera réparé lors de la migration pour corriger #404
