### ISSUE TITLE
Pas de changement de format des dates en fonction des langues

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#332]
En front-office, les dates affichées ont le format de la langue par défaut du site.

**Comment by jbourdin** [comment]
Il faut passer le paramètre locale dans l'appel au filtre de lang de twig.

**Comment by goncalvesm** [comment]
La langue est bien passée mais ce n'est pas la bonne qui est récupérée dans le contrôleur. Je reçois toujours "fr" même quand le site est en anglais. Je vais regarder.

En fait la langue envoyée est bien la bonne mais c'est la variable twig qui ne semble pas se mettre à jour !

En effet la variable twig ne se mettait pas à jour pour une raison que j'ignore. Du coup j'ai utilisé la variable language.locale qui elle semble à jour. A valider avec Julien à son retour.

**Comment by 3AD** [comment]
ok, merci

**Comment by jbourdin** [comment]
fixed
