### ISSUE TITLE
La navigation dans l'application Taxonomie n'est pas localisée

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#335]
Les drapeaux ne sont pas affichés, un ? remplace les drapeaux

**Comment by goncalvesm** [comment]
C'est effectivement le cas. Avec un site créé avant le multilinguisme le cas aurait été possible étant donné que les pages n'avaient pas de langue mais même en créant un nouveau site les pages ont un drapeau "?". Apres il est possible que les pages créées par défaut lors de la création d'un site ne soient pas compatibles avec le multilinguisme.

J'ai même essayé de rajouter une traduction mais il n'y a toujours aucun drapeau (les drapeaux sont bien configurés au niveau du multilinguisme et ils fonctionnent sur les autres taxonomies).

**Comment by jbourdin** [comment]
Fixed
