### ISSUE TITLE
Apres la copie d'un contenu, sa modification, le contenu reste en brouillon

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#337]
Lorsque que l'on copie un contenu et que l'on modifie ensuite ce contenu (dont le titre), et qu'on le publie, il reste en état brouillon et le titre affiché dans la liste des contenus est toujours nommé Copie de ...

**Comment by goncalvesm** [comment]
Testé avec la dernière version de dev est le contenu passe bien à l'état publié quand je l'enregistre. Seul bug que j'ai rencontré, c'est que le titre du contenu lors de la copie est "Copie de machin" et lors de la modification, le titre est le même que le contenu copié (le "Copie de" a disparu) donc je pense qu'il y a quand même un problème lors de l'enregistrement de la copie. Sinon j'arrive à ajouter des traductions et mettre à jour le contenu.
