### ISSUE TITLE
Pas d'affichage des contenus classés avec la taxonomie de navigation

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#338]
Lorsqu'un contenu possède une taxonomie de navigation, celui-ci ne s'affiche pas dans une liste de contenu.
Exemple : les événements ont une taxonomie de navigation site 1. Lors de la création d'une requête dans l'agenda en mettant Site1 dans les critères, l'agenda n'affiche aucun résultat.
Si les contenus événements n'ont pas de taxonomie de navigation complétée, alors ils s'affichent

**Comment by goncalvesm** [comment]
J'ai testé avec la dernière version de dev sur chrome et les requêtes sur les termes de navigation semblent fonctionner. J'ai affecté un contenu à la taxonomie "rubedo.local" et créé une requête SIMPLE (peut être que ça bug avec une requête avancée ?) qui va chercher les contenus ayant pour taxonomie de navigation "rubedo.local" et ça fonctionne. Pour l'agenda faire attention aux dates de début/fin car si le contenu a pour date de début le 08/08/2013, il ne s'affiche pas sur la première page de l'agenda ! J'ai testé sur les contenus de la demo.

Dis moi si ça te le fait toujours.

**Comment by 3AD** [comment]
C'est bien avec une requête simple ou avancée. Mais je ne peux pas tester les corrections sur testing ;) ça attendra donc quelques jours

**Comment by jbourdin** [comment]
Apparemment, déjà corrigé.
