### ISSUE TITLE
autocomplete : accents et caractères sépciaux

### ISSUE THREAD

**Issue by jbourdin** [WebTales/rubedo#355]
2  constats :

si le mot "enquête" est présent, taper "enqu" propose le mot mais "enquê" ou "enque" ne le propose pas.

De plus, lors de la saisie, lorsque la saisie correspond à "enqu^", cela provoque une erreur serveur. Injection de caractère propre à Elasticsearch ? Idem, avec un caractère *, le comportement est différent.

**Comment by dfanchon** [comment]
Fixed
