### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by Touzeau** [WebTales/rubedo#365]
J'ai tout bien suivi l'installation jusqu'à l'avant dernière action :

> > > > Lancer la commande phing. 
> > > > Cela me donne les erreurs suivantes :
> > > > ## c:\rubedo>phing
> > > > 
> > > > Warning: require_once(): It is not safe to rely on the system's timezone settings. 
> > > > You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. 
> > > > In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. 
> > > > We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in 
> > > > C:\Program Files (x86)\Zend\ZendServer\bin\PEAR\phing\Phing.php on line 22

Warning: require_once(phing/Project.php): failed to open stream: No such file or directory in 
C:\Program Files (x86)\Zend\ZendServer\bin\PEAR\phing\Phing.php on line 22

Warning: require_once(): It is not safe to rely on the system's timezone settings. 
You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. 
In case you used any of those methods and you are still getting this warning, 
you most likely misspelled the timezone identifier. 
We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in 
C:\Program Files (x86)\Zend\ZendServer\bin\PEAR\phing\Phing.php on line 22

Fatal error: require_once(): Failed opening required 'phing/Project.php' 
(include_path='C:\Program Files (x86)\Zend\ZendServer\bin\PEAR/../classes;.;C:\ProgramFiles (x86)\Zend\ZendServer\share\ZendFramework\library') in 
## C:\Program Files (x86)\Zend\ZendServer\bin\PEAR\phing\Phing.php on line 22

J'ai vérifié que le fichier phing/project.php existe bien.
J'ai ajouté dans le path le lien C:\Program Files (x86)\Zend\ZendServer\bin\PEAR
qui correspond à la localisation des "require_once"
j'ai ajouté dans le php.ini le path vers ce dossier.
Bref rien n'y fait !

Un coup de main ?

J'aimerai bien pouvoir utiliser votre logiciel qui a l'air plein de promesses, 
d'autant que je forme des futurs ingénieurs sur le responsive web design.

Daniel Touzeau

**Comment by nicolastrenti** [comment]
Bonjour,

Pour les problèmes relatifs à l'installation de Rubedo, je vous invite à poster en priorité sur le forum communautaire : http://forum.rubedo-project.org/

Concernant votre souci, avez-vous suivi en détail le guide d'installation que nous avons publié sur cette page : https://rubedo.atlassian.net/wiki/pages/viewpage.action?pageId=1867789 ?

Je pense qu'il pourra vous être utile pour vous aider pas à pas à installer Rubedo.
Si des problèmes subsistent, n'hésitez pas à prolonger la discussion sur le forum.

Bien cordialement,
Nicolas.

**Comment by Touzeau** [comment]
Comme dis plus haut, j'ai bien suivi, pas à pas le guide d'installation.

## Je pense qu'il s'agit d'un problème de path sur la recherche des sources, mais même en ayant regardé le code, mis le path cherché dans le php.ini, 

extrait du php.ini :+1: 
; Windows: "\path1;\path2"
;include_path = ".;c:\php\includes"
include_path = ".;C:/Program Files (x86)/Zend/ZendServer/bin/PEAR"
;--------------------------------------

## ainsi que dans le path de windows7, 

## C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\ActiveState Komodo IDE 6\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\12.0\DLLShared\;C:\Program Files (x86)\Roxio\OEM\AudioCore\;C:\Program Files\Internet Explorer;C:\Program Files (x86)\IDM Computer Solutions\UltraEdit\;C:\Program Files (x86)\Common Files\Apple\Mobile Device Support;C:\Program Files (x86)\Common Files\Apple\Apple Application Support;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Zend\ZendServer\share\ZendFramework\bin;C:\Program Files (x86)\Zend\ZendServer\bin;C:\ProgramData\Composer\bin;C:\Program Files (x86)\Zend\ZendServer\bin\PEAR;c:\rubedo

j'ai toujours ces messages qui laissent penser que le chemin calculé n'est pas le bon !

Etat des dossiers

**Comment by jbourdin** [comment]
Bonjour,

Ce serait plus approprié sur le forum Rubedo : http://forum.rubedo-project.org

Je note toutefois que le message d'erreur fait référence à un chemin "C:\Program Files (x86)\Zend\ZendServer\bin\PEAR/../classes" qui n'est pas présent dans le php.ini que vous modifiez "include_path = ".;C:/Program Files (x86)/Zend/ZendServer/bin/PEAR"

Il est donc possible que vous ayez un conflit avec une précédente version de PHP et donc plusieurs exécutable ou plusieurs php.ini.

**Comment by Touzeau** [comment]
J'ai effectivement un autre php.ini qui provient d'une installation wamp. Mais au moment de l'erreur, le serveur php lancé est celui de Zend.

## De plus cet include provient de phing.php qui contient dans ses premières lignes:

...
// Set any INI options for PHP
// ---------------------------

/\* set include paths */
set_include_path(
            dirname(**FILE**) . '/../classes' .
            PATH_SEPARATOR .
            get_include_path() 
        );

## ...

d'où l'origine du dossier /../classes
Pour être sûr, j'ai éliminé Wamp.
J'ai relancé le serveur Zend sans erreur,
j'ai lancé l'invite de commande en mode administrateur
j'ai lancé la commande phing
mêmes erreurs que précédemment ....

**Comment by dfanchon** [comment]
A suivre sur le forum
