### ISSUE TITLE
Edition champ à champ / champ Date / multilinguisme

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#372]
Pour un champ de type date, en édition FO champ à champ, le calendrier affiché ne tient pas compte de la langue courante du site (ex. : calendrier en français alors que ma langue courante est l'anglais).

**Comment by jbourdin** [comment]
Est-ce que la langue utilisée n'est pas la langue du back-office, comme c'est le cas pour la barre d'administration ?

Le 31 juil. 2013 à 16:55, Nicolas Trenti <notifications@github.com<mailto:notifications@github.com>> a écrit :

Pour un champ de type date, en édition FO champ à champ, le calendrier affiché ne tient pas compte de la langue courante du site (ex. : calendrier en français alors que ma langue courante est l'anglais).

**Comment by nicolastrenti** [comment]
Non, j'ai le calendrier en français même si je passe en anglais comme langue utilisateur.

**Comment by jbourdin** [comment]
Fixed
