### ISSUE TITLE
Edition FO dans une langue non encore existante pour un contenu

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#374]
Contexte:
- site français / anglais
- français en langue par défaut pour le site
- stratégie : avec fallback
- site affiché en langue anglaise

Je me place en FO sur un contenu français non encore traduit en anglais. Je le modifie, et j'enregistre.
D'après "RSP100 - En tant que contributeur frontoffice, l'édition dans une langue non encore existante pour le contenu doit créer la traduction de ce contenu".

Pourtant j'obtiens le message d'erreur : 
You must provide the current language of the content to update it (51e6a5150228972026000015)

Et mes modifications ne sont pas enregistrées (le contenu reste uniquement en français).

**Comment by jbourdin** [comment]
Edition champs à champs ?

**Comment by nicolastrenti** [comment]
Oui, au temps pour moi, j'ai oublié de le précisé. Edition champ en champ.
Et en fait, ça ne marche pas non plus pour un contenu déjà traduit. J'ai toujours même message.

**Comment by nicolastrenti** [comment]
Je n'ai plus le message d'erreur, mais la traduction n'est pas créée : c'est le contenu dans la langue existante qui est modifié (uniquement dans le cas de l'édition inline champ à champ : dans le cas de l'édition complète FO, la traduction est bien créée.)

**Comment by goncalvesm** [comment]
C'est aussi le cas maintenant pour l'édition champs à champs :+1:
