### ISSUE TITLE
Edition d'un contenu dans le FO

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#378]
Dans le FO, j'édite un contenu (via la popin d'édition complète). Mon site est en anglais, mon contenu est anglais, il est bien affiché dans la popin en anglais, à l'exception du titre du haut de la popin, qui correspond au titre du contenu mais en français.

![image](https://f.cloud.github.com/assets/1919354/893568/2b4a158e-faa8-11e2-9759-014ad2993e16.png)

**Comment by Alexandru-Dobre** [comment]
Cela provientt du coté serveur: le contenu n'a pas été fourni avec la bonne langue dans les champs à la racine. Comme le coté Ext effectue lui-meme le merge sur les champs pour le formulaire, il masque l'erreur
