### ISSUE TITLE
Bloc fonctionnel Twitter

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#380]
La description n'est pas la bonne

**Comment by Alexandru-Dobre** [comment]
Le bloc ne semble pas marcher non plus

**Comment by jbourdin** [comment]
A rédiger (description)

**Comment by Alexandru-Dobre** [comment]
En fait le bloc marche très bien. Il y cependant un point essentiel a préciser aux utilisateurs : pour utiliser ce bloc il faut créer une timeline dans son compte Twitter et récupérer un "id de widget" pour le mettre dans le champ correspondant du bloc.

**Comment by 3AD** [comment]
Ajouter l'@ après le champ Nom d'utilisateur ou dans une bulle d'aide svp

**Comment by 3AD** [comment]
Le bloc 'Twitter' permet d’afficher une liste des tweets ou des tweets favoris d'un compte Twitter. Le bloc permet :
-de définir le nombre de tweet à afficher,
-de paramétrer les dimensions du bloc,
-de définir les options de présentation.

**Comment by 3AD** [comment]
Créer une bulle d'aide pour le champ ID : 
Nécessite la création d'un nouveau widget dans le compte Twitter afin de définir un "id de widget".
