### ISSUE TITLE
Tri par auteur sur résultat de recherche

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#382]
Dans la page de résultats de recherche, si je choisis "Tri par auteur", je n'ai plus que 4 résultats alors que j'en avais 10 avant de choisir ce tri (en l'occurrence, je n'ai plus que les images, je perds mes contenus).

**Comment by jbourdin** [comment]
Fixed (renommage du champ dans l'index mais pas dans le paramètre de tri)
