### ISSUE TITLE
Masques 

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#388]
Option "afficher en onglets" d'une ligne. Comportement attendu à préciser, affiche les titres des colonnes en onglet même quand l'affichage de ceux-ci est décoché

**Comment by Alexandru-Dobre** [comment]
Cette option fonctionne correctement. Néanmoins cela rend inutile les notions de span et offset pour les colonnes concernées (c'est potentiellement confus). Le template de rendu front aurait également besoin de tests et de maintien.
