### ISSUE TITLE
Suppression d'un Type de Contenu

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#399]
Visiblement une régression, la suppression est possible même quand il y a des contenus de ce type ???

**Comment by Alexandru-Dobre** [comment]
C'est bien le isTypeUsed du service Contents qui ne trouve pas de contenus de ce type alors qu'il y en a. Le problème semble venir du findOne qui retourne NULL alors que le filtre est bon et il y a un contenu de ce type.
