### ISSUE TITLE
Affichage des champs DAM en front-office

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#40]
Dans un contenu en front-office :
Un clic sur une image affiche l'image en grand sans possibilité de retour au site. Proposer un affichage par défaut en pop up?
Lorsque plusieurs champs DAM sont saisis, seul le premier champ est affiché en front.

Exemple 4 champs DAM sur ce contenu : http://demo.webtales.fr/search?content-id=5140678e57de70250d00005b

**Comment by jbourdin** [comment]
popup ou popin ?

**Comment by 3AD** [comment]
popin svp

**Comment by goncalvesm** [comment]
Le comportement par défaut d'une image dans un détail de contenu ne contient pas de lien et n'utilise pas non plus de popin.

Pour les champs DAM, je n'ai pas de soucis en utilisant un type de contenu que j'ai créé moi même. Si tu as utilisée un type de contenu créé par défaut, c'est normal, le template n'est pas prévu pour afficher une deuxième image.
