### ISSUE TITLE
Recherche back-office, affichage de taxonomie dans différentes langues

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#402]
Avec 2 taxonomie, traduites dans plusieurs langues, la recherche me propose des facettes en français et d'autres en anglais.

**Comment by Alexandru-Dobre** [comment]
Le coté Ext ne fait qu'afficher les libellés reçus du serveur.

**Comment by jbourdin** [comment]
Doit être corrigé. Certaines taxonomies devaient avoir été créée en Anglais et d'autre en FR et la working language n'était pas correctement définie.
