### ISSUE TITLE
Le correcteur orthographique ne fonctionne pas pour l'édition FO en contexte

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#404]
Le bouton n'est pas activable

**Comment by 3AD** [comment]
Ne fonctionne toujours pas pour l'édition en contexte

**Comment by Alexandru-Dobre** [comment]
C'est un bug de notre version de ckeditor : son correcteur orthographique ne marche pas en edition inline

**Comment by Alexandru-Dobre** [comment]
N'est pas réparable avec du bricolage. Nécessite une migration vers une version stable et récente de CKEditor (4.2 au moins)

**Comment by dfanchon** [comment]
Voir si migration possible sous TinyMCE (inline editing + contraintes accessibilité)

**Comment by Alexandru-Dobre** [comment]
version CKE migrée -> a retester

**Comment by 3AD** [comment]
Top!
