### ISSUE TITLE
Masques de page par défaut

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#406]
Il faudrait créer 3 masques supplémentaires par défaut lors de l'installation pour les pages intérieures :

1 colonne
2 colonnes
3 colonnes

Et sélectionner à la création d'une nouvelle page autre chose que la page d'accueil, par exemple le 1 colonne. Ça éviterait des allers-retours à des néophytes.

**Comment by jbourdin** [comment]
Et ça pour le release 1.3 ?

**Comment by dfanchon** [comment]
pour les 3 masques ça me semblait plutôt simple à faire et ce sera un vrai plus à l'installation pour les utilisateurs.

**Comment by jbourdin** [comment]
Done
