### ISSUE TITLE
les termes de taxonomies sont remplacés par des chiffres dans l'assistant de requête

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#421]
Dans une page avec une requête sur des médias pour afficher une galerie d'images.
Pas d'affichage en front des images. En BO l'édition du requêteur fait apparaitre le problème ci-dessous
l![requete](https://f.cloud.github.com/assets/3063195/916958/bebc9d78-fe9a-11e2-851c-a9c3dce8b9da.png)

**Comment by Alexandru-Dobre** [comment]
Non reproduit
Surement une erreur de rendu du champ dans la DOM (le store est bien chargé puisque le résumé de requête affiche les libellés correctes). Cela vient du framework, et des mauvaises performances du navigateur. Il disparaîtra avec d'autres erreurs de rendu lors de la migration 4.2

**Comment by 3AD** [comment]
Bug toujours existant, c'est le requêteur de médias

**Comment by Alexandru-Dobre** [comment]
Un correctif à été fait.
Il faudrait retester sur ton environnement avant de pouvoir fermer ce bug pour de bon.

**Comment by 3AD** [comment]
nickel
