### ISSUE TITLE
Install 1.3rc1 et boucle de redirection

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#424]
Après install de la 1.3rc1, j'ai appelé l'URL http://rubedo13rc1.local/ directement (au lieu de http://rubedo13rc1.local/install/). Je crois que jusqu'à présent, ça redirigeait vers l'install, mais là ça me provoque l'erreur suivante : 

Cette page Web présente une boucle de redirection.
La page Web à l'adresse http://rubedo13rc1.ntrenti/install/index/define-languages a déclenché trop de redirections. Pour résoudre le problème, effacez les cookies de ce site ou autorisez les cookies tiers. Si le problème persiste, il peut être dû à une mauvaise configuration du serveur et n'être aucunement lié à votre ordinateur.
En savoir plus sur ce problème.
Code d'erreur : ERR_TOO_MANY_REDIRECTS.

Aucun souci en tapant directement http://rubedo13rc1.local/install/

**Comment by jbourdin** [comment]
Fixed
