### ISSUE TITLE
Traduction de texte riche en BO impossible

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#429]
Lors de la traduction d'un texte riche depuis l'application page en BO, le formulaire de la nouvelle langue ne permet de saisir de texte
![texte riche](https://f.cloud.github.com/assets/3063195/930624/229671f8-0011-11e3-8960-7a2431db3b08.png)

**Comment by Alexandru-Dobre** [comment]
Ça marche très bien mais il faut mettre à jour la base ou partir d'une base propre.

**Comment by 3AD** [comment]
idem texte simple

**Comment by Alexandru-Dobre** [comment]
Résumé dans #446
