### ISSUE TITLE
Blocs audio : impossible de proposer un média différent

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#431]
Le fichier ne peut être proposé dans différentes langues

**Comment by dfanchon** [comment]
Les fichiers binaires n'étant pas localisables pour l'instant, nous allons traiter dans la 1.3 ce besoin fonctionnel en rajoutant sur tous les blocs des filtres de visibilité par langue. Cela traitera aussi le problème des vidéos/documents.

**Comment by Alexandru-Dobre** [comment]
implementé en BO

**Comment by jbourdin** [comment]
Implémenté en FO
