### ISSUE TITLE
Pas d'affichage FO des images dans les contenus traduits

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#432]
Un contenu est français et traduit dans 2 autres langues. Les pages anglaise et espagnol n'affichent pas l'image alors qu'elle est présente dans le formulaire d'édition complet

**Comment by jbourdin** [comment]
Pas un bug : En l'état, si on est dans une stratégie sans fallback, un media non traduit n'apparait pas. Si le média est traduit dans la médiathèque ou si le contenu est traduit, il apparait sans problème.

Une tâche atlassian est ouverte pour affiner cette question pour la prochaine version
