### ISSUE TITLE
Mail de réception suite à téléchargement de média

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#435]
Intitulé du mail : Téléchargement du votre fichier

Contenu du mail : Hello,
Following your request, we are pleased to send you your download link. This one will be active 48 hours. le lien
Regards 

Le site testing...rubedo-project.org

La langue principale du site est en français, la personne qui a demandé le téléchargement consultait le site en français.

**Comment by goncalvesm** [comment]
La partie FO fait appel au service de traduction mais celui-ci n'a pas de langue et utilise donc celle par défaut (en).

**Comment by jbourdin** [comment]
A vérifier, le xhr est bien appelé avec un paramètre "current-page".

**Comment by goncalvesm** [comment]
Fixed
