### ISSUE TITLE
Le titre n'est pas surchargé à partir du i18n lors de la récupération de contenus

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#438]
Le titre traduit se trouve dans fields/text dans le i18n 
Il n'y a pas de doublon de text à la racine du i18n
Il doit donc surcharger juste les fields et pas le text 
Il faudrait donc prévoir une règle spécifique aux contenus

**Comment by Alexandru-Dobre** [comment]
Je crois qu'il en est de même pour les médias comme le montre le bug #440

**Comment by jbourdin** [comment]
Il ne semble pas y avoir de souci sur ce sujet.
