### ISSUE TITLE
Création de plusieurs contenus avec le même nom

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#44]
Il est possible créer plusieurs fois un contenu avec le même nom, on devrait avoir un message d'erreur ou un numéro qui s'ajoute.

Ex : sur le site de démo le contenu Localisation

**Comment by jbourdin** [comment]
C'est pas une règle de gestion habituelle dans les CMS. 
Si tu veux faire des actualités ayant le même titre, voir une actualité et un événement avec ce titre ?

ça ne pose aucun souci particulier normalement puisqu'il y a les autres champs de différents.

**Comment by 3AD** [comment]
ok
