### ISSUE TITLE
block : gallerie flickr

### ISSUE THREAD

**Issue by jbourdin** [WebTales/rubedo#46]
Rajouter la description dans l'explorateur de blocs
L'affichage plante quand il n'y a pas d'url
Le titre n'est pas rendu si coché (fix)
La pagination ne marche pas à tous les coups
Le nombre de résultats par page et la règle par défaut doivent s'afficher explicitement
'ALL' => 'ET'
'ANY' => 'OU'
Enlever le champ Extra si NYI

**Comment by jbourdin** [comment]
La pagination ne marche pas à tous les coups
=> non reproduit ce soir
Le nombre de résultats par page et la règle par défaut doivent s'afficher explicitement
=> En front office ?

**Comment by dfanchon** [comment]
=> En front office ? non en BO
