### ISSUE TITLE
Limiter les langues interface BO aux langues actives

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#460]
Si on ne le fait pas, l'ajout de champs à un type de contenu fait planter toute l'interface...

Mais que fait-on si la langue activée par défaut n'est ni l'anglais, ni le français ???

**Comment by jbourdin** [comment]
Essayons de brancher les traductions basées sur les langues BO avec la liste des BO langues.

En gros, les champs dans content et dam.
