### ISSUE TITLE
Tri dans des listes sur des champs autres que les champs system

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#461]
Type de contenu Produit: 
Ajout d'un champ "ordre" (nombre)

Données:
Produit A, ordre = 1
Produit B, ordre = 3
Produit C, ordre = 10

Liste avec tri sur ordre, croissant

J'obtiens A / C / B et non A / B / C

Le problème est que le tri est réalisé par ordre alphabétique, et non numérique.

**Comment by goncalvesm** [comment]
Corrigé
