### ISSUE TITLE
Erreur à la création du premier site après install

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#468]
Après installation sur une nouvelle base de la 13rc2, je me connecte au BO et je crée mon premier site.
A la fin de l'assistant, au moment de créer le site, j'ai le message d'erreur "Erreur / Erreur de clé en double".

![image](https://f.cloud.github.com/assets/1919354/961015/8f3bdeb4-04c7-11e3-9793-f2056242a8e0.png)

(A priori, le site est créé malgré tout)

**Comment by nicolastrenti** [comment]
A priori, c'est le nouveau masque ajouté qui est la cause de l'erreur (masque "false")

**Comment by jbourdin** [comment]
Fixed. Il faut refaire l'installation pour récupérer le package rubedo-localization dans sa version corrigée. (il manquait les titres de 3 masques dans le processus)
