### ISSUE TITLE
L'autocompletion ne semble plus fonctionner

### ISSUE THREAD

**Issue by jbourdin** [WebTales/rubedo#475]
Bloc résultat de recherche

**Comment by dfanchon** [comment]
Non reproductible en dev

**Comment by jbourdin** [comment]
Sur la base de données "demo", j'ai un comportement ou seulement certains mots fonctionne et pas d'autres.

Par exemple, "lorem" est bien proposé en autocomplete mais pas lila.
"Luxembourg" mais pas "articles".
