### ISSUE TITLE
L'affichage des images en popup ne fonctionne pas

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#480]
Dans un contenu, lorsque l'on souhaite proposer l'affichage d'une image dans une popup, celle-ci s'affiche dans la page courante.

**Comment by jbourdin** [comment]
Merci de préciser s'il s'agit d'image dans l'éditeur riche, dans un champ image ou autre...

**Comment by goncalvesm** [comment]
Le problème vient des images dans un champ CKE. CKE propose une option sur les images pour déclencher un affichage en popup après un clic sur celles-ci.

**Comment by Alexandru-Dobre** [comment]
Ce sont des options avancés de CKE. Certaines injectent du js qui se fait enlever par le cleanHtml. 
Pour résumer il vaut mieux éviter d'utiliser de telles options du CKE car elles ont des résultats potentiellement imprévisibles. On ne peut malheureusement pas enlever ces options pour le moment.

**Comment by 3AD** [comment]
Comment afficher les images en grand format sans cette option?
