### ISSUE TITLE
Pas de migration des blocs de resource et resource protégée

### ISSUE THREAD

**Issue by Alexandru-Dobre** [WebTales/rubedo#487]
Avant la 1.3, ces blocs contenaient du texte richer directement dans une propriété. Maintenant c'est un contenu de type texte riche (donc un mongoId) que cette propriété contient.Comme la migration de la base ne prend pas cela en compte, il y a une erreur de type id invalide lors de l'affichage de la page concernée

**Comment by dfanchon** [comment]
Y a t-il une action possible sur ce bug ?

**Comment by Alexandru-Dobre** [comment]
la propriété exacte est "introduction"
blocs concernés : resource et protectedResource

**Comment by Alexandru-Dobre** [comment]
cette propriété contenait du texte riche (strinh html) et à partir de la 1.3 c'est un id correspondant à un contenu de type texte riche
