### ISSUE TITLE
Contenus vides lors de suppression de termes de taxonomie

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#488]
Dans un site Rubedo (1.3).
Un type de contenu article utilise plusieurs vocabulaires de taxonomie.
Lorsque l'on supprime une partie des termes d'un vocabulaire, les anciens contenus taggés avec ces anciens termes sont vides lors de leur édition en BO.

**Comment by goncalvesm** [comment]
Non reproduit.

J'ai créé un nouveau terme de taxonomie puis un nouveau contenu tagué avec ce terme et quand je supprime le terme de taxonomie, le contenu reste intacte.

**Comment by Alexandru-Dobre** [comment]
coté interface il ne semble plus y avoir de bug d'affichage
néamoins, des orphelins ont été produits par la suppression des termes de taxonomie 
il faudrait regarder le code serveur concerné

**Comment by Alexandru-Dobre** [comment]
le bug des termes orphelins ne se reproduit pas malgré de nombreux tests
il devrait s'agir d'une erreur mongo ponctuelle

**Comment by Alexandru-Dobre** [comment]
bug bien présent au niveau de la suppression récursive des termes 
aucune erreur serveur reçue

**Comment by Alexandru-Dobre** [comment]
enfin corrigé au niveau du service des taxonomy terms
