### ISSUE TITLE
Description du bloc formulaire de recherche avancée

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#489]
Utilise une autre description

**Comment by dfanchon** [comment]
Proposition :

Le bloc 'Formulaire de recherche avancée' permet d'afficher un formulaire de recherche limité à une ensemble de types de contenus. Le formulaire expose les différents vocabulaires de taxonomie disponibles sous forme de liste déroulantes.

The 'Advanced search form' block displays a search form limitated to one or several content types. The form displays the available vocabularies for choosen content types as combo boxes.
