### ISSUE TITLE
SI j'édite un contenu qui n'a pas été traduit pour le working language, les champs ne sont pas pré-remplis avec les valeurs par défaut.

### ISSUE THREAD

**Issue by goncalvesm** [WebTales/rubedo#493]
![image](https://f.cloud.github.com/assets/2509924/1041677/d1c4c78a-0fd7-11e3-9ca4-f418d1e1dddb.png)

**Comment by jbourdin** [comment]
Peux-tu tester en 1.4 ?

**Comment by goncalvesm** [comment]
L'erreur proviendrait des contenus importés.
