### ISSUE TITLE
image getter for document preview should accept various mime types

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#5]
backoffice/image/get returns 'Not authorized file extension' for PDF file
should not be filtered for :
application/pdf,
application/rtf,
text/html,
text/plain,
text/richtext,
application/msword,
application/vnd.openxmlformats-officedocument.wordprocessingml.document,
application/vnd.ms-excel,
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
application/vnd.ms-powerpoint,
application/vnd.openxmlformats-officedocument.presentationml.presentation,
application/vnd.oasis.opendocument.text,
application/vnd.oasis.opendocument.spreadsheet,
application/vnd.oasis.opendocument.presentation

**Comment by jbourdin** [comment]
backoffice/image/get is for image only.
for other documents, please use backoffice/file/get ...
