### ISSUE TITLE
Language combo (both default languages and languages)

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#527]
New site > 

<b>Notice</b>:  Undefined index: value in <b>C:\Projets\rubedo\module\Rubedo\src\Rubedo\Backoffice\Controller\DataAccessController.php</b> on line <b>145</b><br />
{"success":false,"msg":"value is required","class":"WebTales\MongoFilters\Exception","file":"C:\Projets\rubedo\vendor\webtales\mongo-filters\library\WebTales\MongoFilters\ValueFilter.php","line":31}

**Comment by jbourdin** [comment]
Voir #524 ?
Le 7 oct. 2013 à 14:20, Didier Fanchon <notifications@github.com<mailto:notifications@github.com>>
 a écrit :

New site >

Notice: Undefined index: value in C:\Projets\rubedo\module\Rubedo\src\Rubedo\Backoffice\Controller\DataAccessController.php on line 145

{"success":false,"msg":"value is required","class":"WebTales\MongoFilters\Exception","file":"C:\Projets\rubedo\vendor\webtales\mongo-filters\library\WebTales\MongoFilters\ValueFilter.php","line":31}
