### ISSUE TITLE
Pas de localisation pour les contentLink

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#529]
On ne peut pas proposer un autre lien lors d'une traduction

**Comment by jbourdin** [comment]
Peux-tu détailler ?

Tu parles des champs lien vers un contenu ?

Le 7 oct. 2013 à 17:31, 3AD <notifications@github.com<mailto:notifications@github.com>>
 a écrit :

On ne peut pas proposer un autre lien lors d'une traduction

**Comment by 3AD** [comment]
Dans un contenu avec un champ content link. Si l'on a une traduction de ce contenu, il faudrait pouvoir donner la possibilité de proposer des liens différents ou pas de liens.

**Comment by Alexandru-Dobre** [comment]
la case à cocher à été rajoutée
