### ISSUE TITLE
Block navigation

### ISSUE THREAD

**Issue by jbourdin** [WebTales/rubedo#53]
Rajouter une option pour afficher ou non la page racine : Afficher la page racine ? Par défaut à oui

Le bloc de navigation créé à l'installation ne pointe pas sur la page d'Accueil

Ajouter une option Style  = Horizontal (défaut) ou Vertical et coder le gabarit de présentation (cf Boostrap Stacked pills)

**Comment by Alexandru-Dobre** [comment]
config ext faite
