### ISSUE TITLE
Message en anglais dans interface française pour le changement de mode du back-office

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#533]
This change requires an interface reload in order to fully take effect. Would you like to reload now ?

**Comment by Alexandru-Dobre** [comment]
C'est normal. Les libellés ne sont traduit qu'à la fin de chaque release !

**Comment by 3AD** [comment]
justement c'était la 1.4

**Comment by Alexandru-Dobre** [comment]
sera corrigé lors de la localisation des nouveaux composants de la 2.0
