### ISSUE TITLE
Si url segment correspond à url intuitive, alors pas de prise en compte dans l'adresse

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#535]
Ex : contenu actualité avec url segment "Bettancourt"
l'adresse url affichée pour c e contenu : http://testingv2.rubedo-project.org/en/detail/52530480dbf9ca491700001b/Affaire+Bettencourt+%3A+non-lieu+pour+Sarkozy

**Comment by jbourdin** [comment]
Ceci n'a pas encore été implémenté.
