### ISSUE TITLE
Impossible d'afficher un carrousel en front

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#538]
A tester, bizarre ..

**Comment by jbourdin** [comment]
As-tu précisé le champ image à utiliser ? Ce champs est-il localisable ? (il ne doit pas l'être)

Le 7 oct. 2013 à 21:28, 3AD <notifications@github.com<mailto:notifications@github.com>> a écrit :

A tester, bizarre ..

**Comment by 3AD** [comment]
En effet. J'ai donc proposé que le bloc ne s'affiche que dans le site en français.
Et j'ai une autre erreur : Le bloc carrousel, au niveau du champ Titre il n'y a plus de titre et une icône s'affiche indiquant qu'il y a une erreur de localisation.
Lorsque je veux enregistrer la page j'ai l'erreur suivante : Erreur dans la récupèration de l'url de la page

Le bloc est sur la page Nouvelle.

**Comment by 3AD** [comment]
Ok,  j'ai trouvé. Mon back-office avait perdu la langue de travail. En réactualisant, je n'ai plus les erreurs de localisation.
Toujours Impossible d'afficher le carrousel

**Comment by dfanchon** [comment]
A retester sur testingV2

**Comment by 3AD** [comment]
ok
