### ISSUE TITLE
Perte de connexion en front

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#543]
Connecté en back-office. Lorsque l'on revient sur le front, il est nécessaire de se reconnecter pour pouvoir éditer en front

**Comment by Alexandru-Dobre** [comment]
Cas plus précis: la barre d'administration disparait lorsque j’accède au détail d'un contenu à partir d'une liste de contenus manuelle
Par contre il suffit de revenir sur la page précédente pour retrouver la barre d'admin
Si on reclique sur le même lien "en savoir plus", le bug ne se produit plus
Il fuat vider le cache pour reproduire le bug avec le meme lien

**Comment by Alexandru-Dobre** [comment]
dans ce meme cas , la recuperation de l'utilisateur courant dans le preDispatch ou le postDispatch retourne null
ça n'arrive que pour l'accés à un détail de contenu qui n'est pas encore en cache
