### ISSUE TITLE
Pas de rendu front d'un document en lien dans un contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#544]
Ex : http://testingv2.rubedo-project.org/fr/detail/525308b6dbf9ca491700001f/L%27universit%C3%A9+fran%C3%A7aise+passe+de+l%27amphi+aux+cours+en+ligne#
Dans le type de contenu article il y a un champs Document Celui-ci ne s'affiche pas en front

**Comment by Alexandru-Dobre** [comment]
c'est un effet de cache
le lien fourni semble montrer le bon résultat
