### ISSUE TITLE
Erreur lors de l'enregistrement de modifications

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#551]
![fireshot screen capture 349 - rubedo - testingv2_rubedo-project_org_backoffice](https://f.cloud.github.com/assets/3063195/1296014/54734ba0-30be-11e3-9831-218f717097e4.png)

J'ai eu cette erreur 
-lorsque j'ai enregistré les modifications lors de l'ajout d'un champs lien sur un contenu dans un type de contenu
-lorsque j'ai enregistré mon gabarit crée pour les articles

**Comment by Alexandru-Dobre** [comment]
Ca ne vient pas des types de contenus
Je vois que le module des contenus est également ouvert donc la synchronisation suite à mise à jour a pu déclencher un filtre aberant. 
Je n'arrive pas à le reproduire.
C'est possible d'avoir un cas plus précis avecc l'état exacte des deux modules ouverts?

**Comment by 3AD** [comment]
J'ai refait "lorsque j'ai enregistré les modifications lors de l'ajout d'un champs lien sur un contenu dans un type de contenu" et je n'ai plus le bug

**Comment by Alexandru-Dobre** [comment]
on va dire qu'il n'est pas reproductible
à rouvrir si jamais il revient
