### ISSUE TITLE
Traduction des champs dans type de contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#571]
Lorsque l'on modifie le label d'un champs pour une langue donnée dans un type de contenu, le label est modifié dans toutes les langues

**Comment by Alexandru-Dobre** [comment]
C'est pas vraiment le cas.
Quand on crée un nouveau champ, tant qu'on a pas explicitement saisi la valeur de toutes les langues possibles, quand on saisit une nouvelle valeur, elle est appliquée à toutes les langues non saisies.C'est pour faciliter le cas ou le label est le même dans toutes les langues.
