### ISSUE TITLE
Can't connect with username

### ISSUE THREAD

**Issue by pand-app** [WebTales/rubedo#576]
If I use my email for login, it work, if I use my username, it fail.
We need to test more this bug.

**Comment by jbourdin** [comment]
It could be that there was a mistake between full name and username.

**Comment by pand-app** [comment]
In fact, the login is case sensitive, why ?

**Comment by jbourdin** [comment]
Why shouldn't the login be case sensitive ? I think most login/password strategy are case sensitive on login.

In fact, to find the user, we do a findOne with the login equal to the given username or email. To do otherwise would be inefficient (no index on regex query).

**Comment by Alexandru-Dobre** [comment]
c'est bien plus un atout de sécurité qu'un bug
