### ISSUE TITLE
FO : impossible de faire un lien vers une page

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#588]
Depuis l'édition en front d'un contenu, lorsque l'on souhaite faire un lien vers une page du site, la pop up n'affiche que la Salamandre

**Comment by Alexandru-Dobre** [comment]
C'est réparé MAIS: ce type de lien se casse si le chemin de la page change (modif de nom ou de position de la page ou d'une des pages parentes) ou si la langue change. Une solution permanente est requise qui rentre dans la tache de conception de refactoring des liens dans un CKE.
