### ISSUE TITLE
Persistance d'une ancienne langue

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#608]
Un site a été créé en anglais. L'administrateur souhaite changer la langue du site en français.
L'application Sites indique que le site est uniquement en Français. On ne peut pas décocher la langue anglaise dans l'application Langues. Du coup, on garde les fonctionnalités de traduction même si on a plus qu'une langue

**Comment by Alexandru-Dobre** [comment]
La langue par défaut de la base était l'anglais: elle ne peut pas être désactivée
Ceci est un fonctionnement tout à fait correcte
