### ISSUE TITLE
Champ non traduit

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#610]
Dans l'import des contenus, étape 3 (setting of the taxonomy), les valeurs de la colonne "Mandatory" ne sont pas traduites : on a "oui" / "non" dans l'interface en anglais.

![image](https://f.cloud.github.com/assets/1919354/1662842/f33023d0-5c06-11e3-8928-72d8262ff676.png)

**Comment by Alexandru-Dobre** [comment]
a traiter lors de la passe de localisation finale de la 2.2

**Comment by Alexandru-Dobre** [comment]
de toute évidence déjà corrigé depuis quelque temps
