### ISSUE TITLE
Fil d'ariane en plusieurs langues

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#614]
Dans un site franco-anglais, tous les contenus sont traduits dans les 2 langues. La langue par défaut est le français. Je visualise mon site en anglais.

Le fil d'ariane d'un détail de contenus affiche la navigation en anglais et le titre du contenu en français. Ex

```
Home / Ressources / Documentation / Développement d'extensions pour le CMS Rubedo
```

**Comment by Alexandru-Dobre** [comment]
a retester sur 2.1
