### ISSUE TITLE
Bloc liste de médias

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#618]
Le bloc ne permet pas de restreindre l'affichage des médias en fonction du groupe.
Par exemple, espace privé affiche tous les documents, qu'ils soient classés pour un affichage restreint ou diffusion globale

**Comment by dfanchon** [comment]
Rajouter dans Atlassian : pour la brique collaborative, possibilité de filtrer une requête sur un workspace. idem sur liste de contenus.
