### ISSUE TITLE
Création d'un contenu réservé à un espace

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#619]
Lorsqu'un type de contenu est réservé à un espace, alors il faudrait que lorsque l'on crée un nouveau contenu de ce type, par défaut l'espace de travail soit celui du type.

**Comment by dfanchon** [comment]
Ce n'est pas un bug mais une mauvaise compréhension des mécanismes de droits dans Rubedo. L'espace de travail du type de contenu permet de déterminer les groupes qui vont avoir le droit de lire/modifier le type de contenu, donc la structure du contenu. Cet espace de travail n'a à voir avec les espaces de travail des contenus eux même.
