### ISSUE TITLE
Droits : il faudrait "cacher" les utilisateurs en fonction de leurs espaces

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#638]
Exemple, je souhaite cacher les utilisateurs du site 1 au sous-administrateur du site 2.
Mais je souhaite lui donner la possibilité d'ajouter des utilisateurs à son site.
Là, je suis dans un cas de non utilisation du référentiel des utilisateurs.

Il faudrait pouvoir faire pareil que pour les contenus

**Comment by 3AD** [comment]
Exemple d'utilisation, si sur mon site 2 je souhaite envoyer une newsletter à tous mes inscrits, je ne peux pas différencier les membres de mon site de ceux du premier site

**Comment by dfanchon** [comment]
à déplacer dans atlassian
