### ISSUE TITLE
Droits sur média

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#642]
Mon type de média Z est destiné à un espace de travail privatif. Lorsque j'ajoute un média de ce type, par défaut les espaces de travail sont positionnés à Global à la place du nom de mon espace.

**Comment by dfanchon** [comment]
Ce n'est pas un bug mais une mauvaise compréhension des mécanismes de droits dans Rubedo. L'espace de travail du type de mediapermet de déterminer les groupes qui vont avoir le droit de lire/modifier le type de media, donc la structure du media. Cet espace de travail n'a à voir avec les espaces de travail des medias eux même.
