### ISSUE TITLE
Droits médiathèque

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#643]
Une image dont le type est réservé à un espace 1, dont les droits de diffusion et de contribution sont positionnés à espace 1 est quand même visible sur mon second site (lui-même positionné dans un autre espace).

**Comment by pand-app** [comment]
Je ne parviens pas à reproduire ce bug (Afficher une gallerie sur mon Espace 2, avec la requête piochant mon Type 1 (de l'espace 1 donc))
Il me faudrait donc un peu plus d'informations sur la démarche pour reproduire l'anomalie.
