### ISSUE TITLE
Pas de workspace pour les emails

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#644]
Pour les emails il faudrait pouvoir aussi profiter des workspaces

**Comment by 3AD** [comment]
Idem pour les listes de diffusion aussi. Le fait que la liste soit dans un espace de travail n'influe pas sur sa visibilité ou pas en back-office pour les sites qui sont dans d'autres espaces de travail

**Comment by dfanchon** [comment]
à déplacer dans atlassian
