### ISSUE TITLE
Manque des droits pour l'import des contenus

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#645]
à déplacer dans atlassian

**Comment by dfanchon** [comment]
à déplacer dans atlassian

**Comment by 3AD** [comment]
Manque un rôle pour l'import de contenus

**Comment by pand-app** [comment]
L'attribution du nouveau rôle "Importer des contenus" implique l'attribution des droits d'écriture sur les contents types et contents.
J'attribue la tâche à Alexandru car il reste à ajouter le droit "exe.ui.import" dans la liste des droits donnant accès à l'admin du backoffice. Sinon, le bouton est inacessible.
