### ISSUE TITLE
Can't import on firefox 26.0

### ISSUE THREAD

**Issue by pand-app** [WebTales/rubedo#649]
If I import a .csv through Chrome : It's work.
If I import a .csv through Firefox 26.0, return is success: true but ext say "Erreur dans l'analyse du fichier"

**Comment by Alexandru-Dobre** [comment]
import refait
a retester

**Comment by pand-app** [comment]
I can't import, JS error : 
file http://mrgibson.com/comics.csv
Firefox 30

**Comment by Alexandru-Dobre** [comment]
non reproduit sur 2.2 avec Firefox 30
