### ISSUE TITLE
Migration users 2.0 -> 2.1

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#652]
A partir d'un dump de la demo (2.0), je suis monté en 2.1.
Je n'ai aucun utilisateur visible dans l'appli Users, malgré une réindexation et une réinitialisation des contenus via le wizard d'install.
Pourtant, j'arrive me connecter au BO sans problème, et des utilisateurs admin sont bien visibles dans l'écran Accounts du wizard d'install.

**Comment by pand-app** [comment]
Après différents tests, je ne parviens pas à reproduire le problème (que je sais présent dans des versions antérieures de Rubedo)

A tester et définir le cas d'utilisation où le problème se produit.

Testés : 
- Depuis une 2.0 je vais dans les types d'utilisateur puis dans les utilisateurs, ces derniers ne sont pas visibles, en updatant la base dans supervision, ils apparaissent.
- Depuis une 2.0 je vais dans les utilisateurs, ces derniers ne sont pas visibles, puis dans les types d'utilisateur , en updatant la base dans supervision, ils apparaissent.
- Depuis une 2.0, je vais directement dans supervision, et j'update ma base : les users apparaissent bien.
- Depuis une 2.1 corrompue, je supprime modifie la collection RubedoVersion pour faire croire que je suis en 2.0 et j'update, les users réapparaissent.

**Comment by Alexandru-Dobre** [comment]
a retester
