### ISSUE TITLE
Recherche en mode "checkbox"

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#655]
Dans les recherches en mode checkbox (bloc recherche et bloc Directory), les critères de type "full text search" renseignés n'apparaissent pas au dessus de la recherche. Il est donc impossible de les supprimer.

Idem pour la lettre sur laquelle on a cliqué dans le cas du bloc Directory.

**Comment by Alexandru-Dobre** [comment]
rajouter un bouton permettant de reset ces critères

**Comment by 3AD** [comment]
La fonction n'est pas présente chez moi
