### ISSUE TITLE
Présence des drapeaux dans users type et site monolingue

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#658]
Le site est monolingue. Les drapeaux sont affichés

![users-types](https://f.cloud.github.com/assets/3063195/1886765/95126942-79ee-11e3-9aca-4037ee417bde.gif)

**Comment by Alexandru-Dobre** [comment]
ce sont des libellés multilingues au sens de la langue d'interface et non de langue des données

**Comment by 3AD** [comment]
Ok, merci
