### ISSUE TITLE
Dans application masque de page, on ne peut pas changer les titres des onglets

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#659]
Lorsque l'on applique l'affichage en onglet d'une ligne, les titres des blocs ajoutés ne sont pas pris en compte pour l'affichage en front-office.
Titre reste à la place des titres donnés aux blocs

**Comment by Alexandru-Dobre** [comment]
Les titres concernés dans ce cas sont ceux des colonnes filles de cette ligne. Ça n'a rien à avoir avec des blocs.
