### ISSUE TITLE
Le pourcentage des résultats de recherche dans Directory

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#664]
Le pourcentage affiché ne correspond pas aux résultats. Exemple recherche d'un Yannick (seul Yannick). Le pourcentage de l'unique résultat est 68%

**Comment by dfanchon** [comment]
A tester, modification faite pour ne pas tenir compte du multilinguisme (qui influe sur le scoring ES) dans la recherche d'utilisateurs
