### ISSUE TITLE
Erreur dans la galerie de blocs

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#671]
Lors de l'ajout d'un bloc dans une page, on obtient l'erreur suivante
![fireshot screen capture 504 - rubedo - testing_rubedo-project_org_backoffice](https://f.cloud.github.com/assets/3063195/1920157/63254208-7de3-11e3-9dd2-63710db2379d.gif)

**Comment by Alexandru-Dobre** [comment]
pas un bug
c'est juste l'env de test qui n'est pas à jour avec la localisation
