### ISSUE TITLE
Editeur front ne permet plus de faire des liens interne

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#672]
On ne peut plus faire des liens sur page depuis l'édition fo

**Comment by Alexandru-Dobre** [comment]
je viens de le tester sur l'édition en contexte dans un résumé et sur le CKE de la contribution front et ça marche
ça arrive ou exactement ?

**Comment by 3AD** [comment]
Je viens d’essayer sur testing sur un article.
Je n’arrive pas non à afficher un carrousel de contenus

**Comment by 3AD** [comment]
C’est uniquement dans le détail, sinon ça marche très bien sur le résumé

**Comment by Alexandru-Dobre** [comment]
il s'agit bien d'un champ de type cke dans une vue de detail de contenu ?

**Comment by 3AD** [comment]
Exemple ici : http://testing.rubedo-project.org/fr/Accueil/article/52d3cbd1b69988916c847837/La+M%C3%A9diterran%C3%A9e+autour+du+monde#
Fait avec Firefox

**Comment by Alexandru-Dobre** [comment]
Ça n'a aucun sens.
Chez moi ça marche très bien.
Je soupçonne l’environnement testing d’être défaillant
Pourrais-tu tester ça sur le cloud pour en être sur?

**Comment by Alexandru-Dobre** [comment]
il se peut que le nom du champ en soit la cause si c'est un mot réservé 
à vérifier si un autre champ cke avec un autre nom ne passe pas

**Comment by 3AD** [comment]
En effet, ça marche très bien sur le cloud.
