### ISSUE TITLE
Gallery block : too much pages.

### ISSUE THREAD

**Issue by pand-app** [WebTales/rubedo#677]
When I have 2 workspaces with many images by workspace, I have an empty page as first page.
![screen shot 2014-01-20 at 00 20 04](https://f.cloud.github.com/assets/1492215/1950919/7c66bef6-8160-11e3-97fb-4d99be0e0bb5.png)

**Comment by Alexandru-Dobre** [comment]
non reproduit
à voir si ce n'était pas un soucis de cache (utilisation particulière du cache sur ce block)

**Comment by pand-app** [comment]
le init() était appelé que quand il s'agissait d'une requête xhr. Du coup le workspace n'était pas défini.
