### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#682]
Directory : La facette date ne s’affiche pas en fo. Ex : http://testing.rubedo-project.org/fr/accueil/membres

**Comment by Alexandru-Dobre** [comment]
le back est configuré pour renommer date en lastupdatetime
cela semble nécessaire car sinon la recherche ignore le paramètre
le fonctionnement a l'air aberrant : un nom en entrée et un autre en sortie pour le même param

**Comment by dfanchon** [comment]
jusqu'à présent seul le back-office utilisait le nom des facettes, non signifiantes pour le FO. un léger refactoring devrait permettre d'homogénéiser le nom des variables et d'éviter le renommage par le back
