### ISSUE TITLE
Contenus brouillons

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#683]
• Le mode « afficher aussi les contenus brouillons » dans l’application prévisualisation n’affiche aucun contenu. 
• La case Afficher les contenus brouillons ne permet pas d’afficher les contenus brouillons

**Comment by Alexandru-Dobre** [comment]
cela marche très bien dans un cas classique
dans le cas de testing il y a une chose qui pourrait créer des problèmes: le type de contenu Job n'a pas de workflow

**Comment by Alexandru-Dobre** [comment]
pas reproduit en local avec un tc sans workflow
remarque: le mode sans worflow des tc ne semble rien faire
