### ISSUE TITLE
Switching to Settings > Interface > "Application" does not show top menubar

### ISSUE THREAD

**Issue by ayurmedia** [WebTales/rubedo#687]
In rubedo 2.x switching to InterfaceMode = "simple" the "startmenu" will be hidden. But there is no menubar on top any more. Seems to be a bug in new versions. In some demo i was able to switch to interfaceMode ="simple/Application" and i liked it. 
on rubedocloud its also broken. 
Only way to recover from this bug is, in Firebug-console
Ext.getCmp('entete').show(); 
Ext.getCmp('entete').getComponent(0).show();
which will enable the "startmenu" again, and one can switch back to "Desktop" Mode. 

Also quite annoying programming variables are in french. Should be changed to english, makes debugging much easier. 

i debugged the app a bit and found a timing-race-condition: 
in ACLController.js there is a task.delay(300), which is too short and gets called to early. 
if i set it to 2seconds, the menu-bar shows. seems to be a lazy kind of implementation with delay. 
the loading of the interface with ext.js is already painfully slow, no need to add even more delays. 

Main Problem is "MyPrefData" is not initialized correctly after 300ms 

/public/components/webtales/rubedo-backoffice-ui/www/app/controller/ACLController.js 

success:function(response){
                ACL.interfaceRights=Ext.JSON.decode(response.responseText);
                Ext.getCmp('boutonPincipalInterface').enable();
                var task = new Ext.util.DelayedTask(function(){
                    if(MyPrefData.simpleMode){
                        Ext.getCmp("ViewportPrimaire").insert(0,Ext.widget("simpleModeMainBar"));
                    }
                });
                task.delay(2000);
            },

**Comment by Alexandru-Dobre** [comment]
fixed in 2.1.0

**Comment by ayurmedia** [comment]
sorry maybe i posted in wrong repo, didnt notice you include another repo during install. 
the delay 300, is still there in release "next" 
https://github.com/WebTales/rubedo-backoffice-ui/blob/next/www/app/controller/ACLController.js

to reproduce try to activate firebug, as this bug seems to appear with slow initializing of backend.
