### ISSUE TITLE
Page de résultat et application d'une facette

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#689]
Sur une liste de résultats de recherche, si j'affiche par exemple la dernière page de résultats et que j'applique une facette (qui ne possède que quelques éléments), je n'obtiens plus aucun résultat (car je suis certainement toujours sur la dernière page d'une liste qui n'en contient qu'une seule).

**Comment by Alexandru-Dobre** [comment]
a faire en front sur tout block de recherche paginé
