### ISSUE TITLE
There is no icon for the shortcut "Preview"

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#7]
![FireShot Screen Capture 022 - Rubedo - demo_webtales_fr_backoffice_index](https://f.cloud.github.com/assets/3063195/181385/b6482f88-7c4d-11e2-88b1-2a066c757097.png)
On the BO, when you want to add a shortcut for "Preview", there is no icon on the desktop.

**Comment by Alexandru-Dobre** [comment]
This issue only occurs when using the red theme.
Some icons appear to be missing in 64x64 format in red version.
