### ISSUE TITLE
No record has been updated

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#70]
Cas : ajout d'un bloc sur une page. lors de l'enregistrement, le message s'affiche.
Ne permet pas de comprendre pourquoi ça ne fonctionne pas

**Comment by jbourdin** [comment]
conflit de contribution : le message devrait indiquer "un autre utilisateur à modifier cet élément, veuillez recharger celui-ci".

**Comment by jbourdin** [comment]
Message mis à jour
