### ISSUE TITLE
Wrong file upload error message

### ISSUE THREAD

**Issue by lsPeter** [WebTales/rubedo#702]
Uploading of file with size larger than upload_max_filesize displays a wrong error message.
This happens both with single and bulk file upload.

![rubedo1](https://f.cloud.github.com/assets/1991045/2294790/fedc2e62-a086-11e3-80c4-ef26cafb96ba.png)
![rubedo2](https://f.cloud.github.com/assets/1991045/2294791/fee6e7e4-a086-11e3-9589-bcce3ff8128b.png)
![rubedo3](https://f.cloud.github.com/assets/1991045/2294792/fee9545c-a086-11e3-861b-25b392ccf33f.png)

**Comment by Alexandru-Dobre** [comment]
fixed during 2.2 enhancements
