### ISSUE TITLE
Problème sur bloc Agenda

### ISSUE THREAD

**Issue by nguyenbr** [WebTales/rubedo#712]
Le bloc agenda décale les évenement d'un mois.
L'affichage dans la liste décale la date d'un jour.

![rubedo evaluation - agenda](https://cloud.githubusercontent.com/assets/7235923/2653516/0006778c-bfc4-11e3-9f1d-e4423aed2118.png)

**Comment by pand-app** [comment]
Bonjour,

Merci pour le signalement, cependant je ne parviens pas à reproduire cette anomalie, merci de préciser les étapes pour le reproduire. La date est elle formatée comme le backoffice le demande ?

Cordialement,
Gaël

**Comment by Alexandru-Dobre** [comment]
non reproduit
