### ISSUE TITLE
Pas d'assignation de page par défaut dans une liste de contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#714]
Lorsque l'on paramètre une liste de contenu, si 
- la page ne possède pas de colonne principale
- aucune page n'a été sélectionnée pour l'affichage détail

Alors, la liste doit afficher le détail d'un contenu dans une page Détail par défaut.

**Comment by Alexandru-Dobre** [comment]
a retester
chez moi ça remarche avec ce fix
