### ISSUE TITLE
Lien sur page

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#717]
Lorsque l'on fait un lien sur page dans un contenu, le lien est obligatoirement celui de la page d’accueil.

**Comment by pand-app** [comment]
Non constaté dans les cas suivants : 
- Créer un lien depuis une page existance
- Créer une page puis directement créer un lien vers elle
- Créer un lien depuis la langue de travail différente

Merci de préciser l'anomalie

**Comment by 3AD** [comment]
non reproduit
