### ISSUE TITLE
Pas d'affichage de la liste des types d'utilisateurs pour l'inscription

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#722]
Lorsque l'on ajoute un bloc inscription dans une page, il faut d'abord enregistrer la page pour pouvoir ajouter le type d'utilisateur dans les paramètres du bloc

**Comment by Alexandru-Dobre** [comment]
seuls les user types avec inscription activée doivent apparaître dans cette liste
filtre a reparer

**Comment by Alexandru-Dobre** [comment]
filtre réparé
