### ISSUE TITLE
Pas possible de faire un lien externe dans un contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#723]
Sur IE 11 dès que l'on souhaite faire un lien externe, la fenêtre ci-dessous s'affiche et bloque le back-office
![lien externe](https://cloud.githubusercontent.com/assets/3063195/2764781/af3d0d0a-ca1a-11e3-8faa-588265d1c2e6.png)

**Comment by Alexandru-Dobre** [comment]
la fenetre bloque le back car c'est une modale : fonctionnement normal
quel est le véritable bug : elle refuse de se fermer ou ne met pas le lien correctement ?

**Comment by 3AD** [comment]
A l'affichage de la modale tout est bloqué. Il faut rafraichir le navigateur

**Comment by 3AD** [comment]
ok
