### ISSUE TITLE
Bloc Galerie d'images et multilinguisme

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#726]
Ajout d'un bloc Galerie d'images dans une page multilingue.
Les images ont été importées dans la langue par défaut (l'anglais). Le titre des images a été traduit.
Le bloc affiche le titre des images uniquement dans la langue par défaut.

**Comment by 3AD** [comment]
L'erreur suivante est affichée : Notice: Undefined index: fields in C:\Program Files\rubedo-2.2\module\Rubedo\src\Rubedo\Blocks\Controller\GalleryController.php on line 124
- Ies titres des images ne sont affichés que pour la langue par défaut
- les images non traduites s'affichent
  -lorsque l'on navigue avec le paginateur on obtient l'erreur : Error!+jQuery("body").attr("data-noimageerror")+

Cas de test : un site multilingue, stratégie d'internationalisation avec une seule langue.

**Comment by Alexandru-Dobre** [comment]
fixé 
a retester
