### ISSUE TITLE
Bloc médias externes

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#730]
Ne permet pas d'afficher un blog Wordpress, le projet My opera est fermé

**Comment by Alexandru-Dobre** [comment]
Ce blog intègre tout ce qui est conforme à la norme Oembed. Si certaines choses ne sont pas compatibles avec  cette norme ce n'est pas de notre ressort.

**Comment by 3AD** [comment]
Il est indiqué que la norme est respectée.
