### ISSUE TITLE
Mondial shipping

### ISSUE THREAD

**Issue by pand-app** [WebTales/rubedo#731]
I have a shipper "Express" with two rates : 
- One to mondial (*) for 91€
- One to France for 15€

When I've selected France, it's the same ID and the price in confirmation is 91€

**Comment by Alexandru-Dobre** [comment]
règle à appliquer en cas de possibilité multiple: priorité au plus précis 
impossible de mettre plusieurs sur le même pays précisément

**Comment by Alexandru-Dobre** [comment]
- a enlever

**Comment by Alexandru-Dobre** [comment]
option \* enlevée (attention a ne pas garder des données erronées)
