### ISSUE TITLE
Pixlr Image saving

### ISSUE THREAD

**Issue by dfanchon** [WebTales/rubedo#735]

**Comment by Alexandru-Dobre** [comment]
problem is on pixlr side

**Comment by dfanchon** [comment]
tooks me about 5' to find a workaround : http://support.pixlr.com/pixlr/topics/pixlr_api_not_saving_changes

**Comment by Alexandru-Dobre** [comment]
workaround already known
security risk of get request on update action without CSRF protection (natively implemented on all back office post requests but not on get)
would require some rewriting to implement on controller level 
still searching for cleaner solution

**Comment by Alexandru-Dobre** [comment]
fixed : editor is now only usable on online sites (not usable on local host)

**Comment by Alexandru-Dobre** [comment]
fix confirmed and tested
