### ISSUE TITLE
Bloc liste de contenu ne conserve pas la requête

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#747]
Cas : ajout d'un bloc de liste de contenus dans une page 
- ajoute une requête (avancée, simple)
  lorsque l'on enregistre cette requête, le champ Requête est vide. Il faut aller la sélectionner dans la liste des requêtes enregistrées

-ajoute une requête simple
La liste des contenus disponibles : le type de contenus affiche son identifiant au lieu de son nom

La liste des requêtes disponibles propose toutes les requêtes précédemment réalisées, dont requête simple et avancée

**Comment by Alexandru-Dobre** [comment]
fix à tester

**Comment by 3AD** [comment]
ne fonctionne pas

**Comment by Dixeet** [comment]
Chez moi cela à l'air de fonctionner
