### ISSUE TITLE
Bloc RSS

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#758]
Titre du bloc à renommer ?
Sur Firefox il y a des problèmes d'affichage des paramètres :+1: 
![rss](https://cloud.githubusercontent.com/assets/3063195/3387233/dc64fde0-fc7b-11e3-84f5-e2dd33b0d14b.png)

**Comment by pand-app** [comment]
Le bloc est prévu pour pouvoir localiser les libellés, ce qui n'est pas étendable dans l'état actuel du BO.

**Comment by Alexandru-Dobre** [comment]
problème propre à l'extension et non au générique
