### ISSUE TITLE
Pas d'envoi d'email sur bloc média protégé

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#765]
L'erreur suivante est affichée Cannot send message without a sender address alors que l'adresse mail du sender est bien paramétrée dans l'install

**Comment by Alexandru-Dobre** [comment]
l'adresse mail est paramétrée dans l’etape mail ET dans l'étape finale ?

**Comment by 3AD** [comment]
oui tout à été paramétré

**Comment by 3AD** [comment]
Le texte de succès d'envoi d'email est uniquement en anglais "An email with your download link had been sent to you"
