### ISSUE TITLE
Order review

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#768]
Erreur de calul dans l'order review 

Dans l'exemple ci-dessous il y a 19,6% de taxes sur le transport et il n'y a pas de taxes paramétrées
![order review](https://cloud.githubusercontent.com/assets/3063195/3397988/3b1f054a-fd28-11e3-98f8-a11e6bd788a6.png)

**Comment by 3AD** [comment]
Modifier l'affichage des status :
    Payment means : creditTransfer
    Payment status : pendingPayment

**Comment by pand-app** [comment]
Cette issue implique plusieurs choses : 
- Doit on tronquer ou arrondir le prix ? (Législation suivant le pays ?)
- D'où doivent provenir les traductions des clefs des status et moyens de paiement ? (BO, clefs ?)
- Comment afficher les chiffres en prenant en compte les différents affichages (traditionnels, anglosaxons...)

**Comment by Alexandru-Dobre** [comment]
libellés a revoir?

**Comment by Alexandru-Dobre** [comment]
2 chiffres après la virgule max (tronquer)

**Comment by 3AD** [comment]
A faire aussi sur order review et User orders
