### ISSUE TITLE
Les fonctions e-commerce sont activées par défaut

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#771]
Dans l'application Sites, que la case Activer le e-commerce soit activée ou pas, les fonctionnalités sont présentes en bo

**Comment by Alexandru-Dobre** [comment]
Cette case à cocher ne fait pas ça : elle active juste les champs de catégorie sur les pages
C'est la case en install tool qui bloque tout le e-commerce

**Comment by 3AD** [comment]
Dans ce cas, peut-on renommer l'intitulé de cette case pour que ce soit plus clair

**Comment by Alexandru-Dobre** [comment]
changé, à tester
