### ISSUE TITLE
La panier affiche les produits dans la langue par défaut du site

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#779]
La panier bouton et détail affiche le titre des produits dans la langue par défaut

**Comment by pand-app** [comment]
Le fix de ce bug a été fait dans des couches basses de Rubedo, merci de retester : 
- Le comportement des traductions de contenus
- Le comportement des traductions de produits

Et ce, surtout dans les cas suivants : 
- Affichage de l'article/produit sans aucune traduction pour la langue courante
- Affichage de l'article/produit avec une traduction
