### ISSUE TITLE
L'utilisateur qui a crée son compte n'est pas logué par défaut

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#784]
Lorsqu'un utilisateur crée un compte en front-office, si le bloc authentification est présent, alors celui-ci devrait automatiquement être connecté

**Comment by 3AD** [comment]
Une fois que cet utilisateur s'est connecté par le bloc authentification, le bloc inscription affiche une erreur : Error! Email already in use.

**Comment by Alexandru-Dobre** [comment]
param get a enlever lors du reload de page suite a auth
