### ISSUE TITLE
Pas d'affichage du label dans toutes les langues pour le champ Position

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#785]
Dans un type utilisateur, le label position est traduit dans les deux langues du site.
Le label reste affiché dans la langue principale du site

**Comment by Alexandru-Dobre** [comment]
Ce label ne relève pas de la langue du site mais de celle de l'interface
A traiter directement dans le contrôleur en se basant sur cette dernière langue

**Comment by 3AD** [comment]
Bug persistant
