### ISSUE TITLE
Erreur clé en doucle à la création d'une nouvelle page

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#786]
Arrive uniquement après le rechargement du BO. Une fois la première page crée, il n'y a pas d'erreur pour la seconde page

**Comment by Alexandru-Dobre** [comment]
non reprduit

**Comment by Alexandru-Dobre** [comment]
arrive lors de l'ajout d'une page en tant que fille d'une page qui a déjà d'autres filles mais qui n'est pas dépliée

**Comment by Alexandru-Dobre** [comment]
fix a tester
