### ISSUE TITLE
Le bloc Flickr ne permet pas d'afficher la page

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#795]
Lorsqu'un bloc Flickr est ajouté sur une page, la page ne s'affiche plus.  An error occurred sending request. Status code: 403

**Comment by Alexandru-Dobre** [comment]
Bloc ne marche plus suite à evolution Zendservice Flickr

**Comment by dfanchon** [comment]
Tester le comportement oembed de flikr, si le service Zend n'est pas stable on devra supprimer le bloc.

**Comment by Alexandru-Dobre** [comment]
a desactiver dans la 2.2
