### ISSUE TITLE
Dans la recherche le nombre des contenus privés sont affichés

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#798]
Des contenus d'un type sont réservés à certain utilisateur.
Dans les résultats de recherche, l'utilisateur n'ayant pas les droits de les voir, ne visualise pas le type de contenu mais affiche le nombre de ces contenus.

Un clic sur le nombre permet d'afficher les contenus

**Comment by 3AD** [comment]
Idem en back

**Comment by Alexandru-Dobre** [comment]
le filtrage par workspace ne fonctionnerait donc pas sur elasticsearch ?

**Comment by 3AD** [comment]
Hum, en fait ça marche très bien
