### ISSUE TITLE
Type de champ Quizz dans type de contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#800]
il n'est pas possible d'ajouter des options à ce champ

**Comment by Alexandru-Dobre** [comment]
quelles options ? ce champ peut juste rattacher un quiz au contenu -> il n'y a pas grand chose à paramétrer
bug non lié à la 2.2 générique

**Comment by 3AD** [comment]
Il faut supprimer les options des paramètres du champ

**Comment by Alexandru-Dobre** [comment]
fixed
