### ISSUE TITLE
Pas d'affichage des titres des médias audio dans la recherche

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#802]
Dans les résultats de recherche, lorsqu'un document audio est remonté, le titre du média n'est pas affiché et on ne peut pas le sélectionner

**Comment by Alexandru-Dobre** [comment]
En fait il n'est plus possible de faire remonter des medias dans une recherche front

**Comment by dfanchon** [comment]
Fixed. The "online" filter was to agressive.
