### ISSUE TITLE
Zend Framework

### ISSUE THREAD

**Issue by ksumter** [WebTales/rubedo#808]
It appears that Zend Framework is no longer available for free as a development license.  Is that what you are seeing as well?  Does Rubedo REQUIRE Zend, or will another PHP framework work for it?

**Comment by pand-app** [comment]
Hi,

Please consider this file : https://github.com/zendframework/zf2/blob/master/LICENSE.txt
Zend framework 2 is an opensource product.

Zend framework is not Zend server. Zend server is NOT mandatory to install Rubedo, in production or development.
