### ISSUE TITLE
Pas d'ajout de produit en temps réel

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#811]
Lorsque l'on ajoute un produit au panier, celui-ci ne s'ajoute pas en temps réel. Il faut changer de page pour que le produit s'affiche dans le shopping cart.

Un clic sur View cart affiche l'erreur suivante :
Fatal error: Uncaught exception 'WebTales\MongoFilters\Exception' with message 'Invalid MongoId :Array' in C:\Program Files\rubedo-2.2\vendor\webtales\mongo-filters\library\WebTales\MongoFilters\UidFilter.php:42 Stack trace: #0 C:\Program Files\rubedo-2.2\vendor\webtales\mongo-filters\library\WebTales\MongoFilters\AndFilter.php(15): WebTales\MongoFilters\UidFilter->toArray() #1 C:\Program Files\rubedo-2.2\module\Rubedo\src\Rubedo\Mongo\DataAccess.php(760): WebTales\MongoFilters\AndFilter->toArray() #2 C:\Program Files\rubedo-2.2\module\Rubedo\src\Rubedo\Mongo\DataAccess.php(944): Rubedo\Mongo\DataAccess->findOne(Object(WebTales\MongoFilters\UidFilter)) #3 C:\Program Files\rubedo-2.2\module\Rubedo\src\Rubedo\Collection\AbstractCollection.php(291): Rubedo\Mongo\DataAccess->findById('Array') #4 C:\Program Files\rubedo-2.2\module\Rubedo\src\Rubedo\Collection\AbstractLocalizableCollection.php(161): Rubedo\Collection\AbstractCollection->findById(Array, false) #5 C:\Program Files\rubedo-2.2\module\Rubedo\src\Rubedo\Router\Url.ph in C:\Program Files\rubedo-2.2\vendor\twig\twig\lib\Twig\Template.php on line 294

**Comment by Dixeet** [comment]
Je précise que c'est un produit avec plusieurs types de variation, cependant chez moi tout ce passe bien il faudrait connaitre exactement les blocs présent dans la page de détails de produits.

**Comment by dfanchon** [comment]
Non reproductible
