### ISSUE TITLE
Erreur à la création de nouveau prix dans les livraison

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#812]
Application Shippers
Création d'un nouveau type de livraison
Add a rate
Lors du double clic pour ajouter le pays, une fenêtre d'erreur s'affiche "Ce champs est obligatoire"
La pays est ajouté, ainsi que les autres paramètres. 
La fenêtre est persistante. Pour enregistrer la ligne il faut cliquer sur entrée. Le bouton update n'est pas disponible.

Uniquement sur le champs pays

**Comment by Alexandru-Dobre** [comment]
Non reproduit 
Integrité environement à revoir
