### ISSUE TITLE
Erreur BO sur les prix des produits

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#814]
- Réalisation d'un import de produit.
- Les prix des produits contiennent une virgule
- L'import est réalisé sans soucis
- Lorsque le produit est modifié manuellement en bo, lors de l'enregistrement on obtient une erreur "MapperParsingException[failed to parse [productProperties.variations.price]]; nested: NumberFormatException[For input string: "662,8"]; "

Dans une fiche produit, pour "réparer" ça, il faut ressaisir la virgule pour qu'elle se  transforme en "."

**Comment by Alexandru-Dobre** [comment]
j'ai testé le back : la donnée corrompue ne vient pas de la
le problème se situe très probablement au niveau de l'import

**Comment by dfanchon** [comment]
Fixé au niveau de l'import
