### ISSUE TITLE
Erreur bloc calendrier

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#833]
Je viens de me rendre compte d'un problème sur le bloc Calendrier.
J'ai un type de contenu Event avec un champ de type "Date" dont le name est "Date" (avec un D majuscule). Le name de ce field s'est généré automatiquement au moment de mon import.
Si j'essaye de créer un bloc de type Calendrier en faisant une Simple Query pour récupérer tous les contenus de type Event, la query semble bien fonctionner (mes contenus remontent en faisant une preview de la query), mais mes contenus ne sont à aucun moment rattachés à mon calendrier.

Après investigation, le problème se situe au niveau du fichier /module/Rubedo/src/Rubedo/Blocks/Controller/CalendarController.php :
Ligne 58 : on récupère le nom du champ date mais en se basant sur "dateField", or la clé du tableau s'appelle "date". A remplacer donc par: $dateField = isset($blockConfig['date']) ? $blockConfig['date'] : $this->getParamFromQuery('date-field', 'date');

Ligne 142 : "date" est écrit en dur plutôt que d'utiliser la variable (dynamique) $dateField. A remplacer donc par: if (! is_array($vignette["fields"][$dateField])) {
Ligne 150 : même problème. A remplacer par: if (! is_array($vignette["fields"][$dateField])) {
Ligne 151 : même problème. A remplacer par: $day = date('d', $vignette["fields"][$dateField]);
Ligne 154 : même problème. A remplacer par: foreach ($vignette["fields"][$dateField] as $value) {

**Comment by pand-app** [comment]
Merci pour vos remarques, j'ai vérifié tout ça, vos observations étaient bonnes. J'en ai profité pour faire quelques retouches. J'ai remarqué également que la date de fin n'est pas prise en compte actuellement, ça sera effectif dans la V3.

Vous pouvez profiter des modifications en pullant la branche next, sinon ça sera releasé dans la 2.21
