### ISSUE TITLE
Manque la date dans les listes de contenus

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#837]
Bloc liste de contenus :
- La date des contenus ne s'affiche pas

**Comment by dfanchon** [comment]
La date n'est pas affichée depuis la v2. A revoir dans un contexte plus global d'affichage de détail d'article avec auteur, taxonomies, date, ... etc.

**Comment by 3AD** [comment]
la date s'affiche dans la 2.2 pour les contenus par défaut

**Comment by goncalvesm** [comment]
WebTales/rubedo-frontoffice@03832478ddbf86f8c2d8e6a29253bdab1cfecf97 Corrigé
