### ISSUE TITLE
Problème de tri dans une query

### ISSUE THREAD

**Issue by jerem77** [WebTales/rubedo#839]
Je remonte des contenus de type 'News' (type de contenu qui contient un champ 'Date'), rattaché à une taxonomie Navigation, triés sur le champ 'Date' de manière décroissante : en FO (ou même dans la simulation de la query), les contenus remontés ne sont pas triés correctement (mélangés n'importe comment).
Si j'effectue un var_dump des valeurs des champs Date de ma liste de contenus retournés, voici ce qui est retourné (on voit bien que les timestamp ne sont rangés dans l'ordre décroissant) : 
array (size=5)
  0 => string '1409781600' (length=10)
  1 => string '1412028000' (length=10)
  2 => string '1409176800' (length=10)
  3 => string '1313359200' (length=10)
  4 => string '1410818400' (length=10)

**Comment by pand-app** [comment]
Bonjour,

Je ne parviens pas à reproduire le bug. Merci de préciser le cas d'utilisation.

J'ai créé trois contenus dans le type de contenu "Actualités" : 
- Dans l'ordre suivant : "Test 16/10", "Test 17/10", "Test 15/10".
- Une taxonomie de navigation sur la page d'accueil
- Un champ date comprenant la date dans mon titre

J'ai créé une query triant ces contenus par date croissante , l'obtient bien "Test 15/10", "Test 16/10", "Test 17/10".
J'ai trié ensuite par date décroissante, j'obtient bien "Test 17/10", "Test 16/10", "Test 15/10".

```
Summary
Eligible content types

    Actualités

Taxonomy : Each content must verify at least one of the following rules
Navigation : Contains at least one of the terms

    Accueil

Rules and sorting on content fields

    Date , Sort ascending
```

```
PHP 5.6.0 (built: Sep 13 2014 10:36:37) 
db.version() 2.6.4

```
