### ISSUE TITLE
Pas de passage de connexion entre le FO et le BO

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#843]
Il n'y a pas de passage d'informations de connexion entre le front et le back-office.

**Comment by Dixeet** [comment]
Ce bug n'intervient pas si l'on vient de se connecter. Il apparaît lorsque la connexion est maintenue en front, le back fini par se déconnecter. Ceci doit etre lié au bug de déconnexion du back où l'on doit se log 2 fois d'affilé pour se reconnecter.

**Comment by goncalvesm** [comment]
Doublon #885
