### ISSUE TITLE
Changement d'id pour les images

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#846]
Depuis la médiathèque, lorsque l'on upload une nouvelle image pour remplacer une image existante, l'id de l'image est modifié.

**Comment by goncalvesm** [comment]
Apres étude, il faudrait faire évoluer le backoffice afin que celui-ci envoie l'ID actuel de l'image. De ce fait, nous pourrons la supprimer et la recréer avec la nouvelle image sur le même ID. Pour info, le driver PHP de GridFS (stockage des fichiers dans la base de données) ne contient pas de fonction de mise à jour des fichiers, il faut donc les supprimer et les recréer. Ce comportement n'est donc pas une régression car le noyau permet uniquement de créer/supprimer un fichier dans la BDD.

**Comment by 3AD** [comment]
Les images sont remplacées et conservent le même id dans les versions avant la 3.0

**Comment by goncalvesm** [comment]
La requête ayant changée entre la v3 et les versions antérieures, il faudra ajouter l'ID de l'image à remplacer car actuellement nous n'avons pas l'information (c’était le cas dans les versions précédentes).
