### ISSUE TITLE
Les Query simple sont sauvegardées dans les blocs listes de contenus

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#847]
Dans les listes de contenus, les Query simple sont sauvegardées et listées dans les Query

![content list](https://cloud.githubusercontent.com/assets/3063195/4862852/04d4bcc2-6110-11e4-889e-fdea022a345d.png)

**Comment by Dixeet** [comment]
Ce bug arrive sous firefox et non chrome. Il y a une différence dans l'execution du javascript au moment de l'appuie sur le menu déroulant pour choisir la query. La requete est bien la meme entre firefox et chrome, la liste des queries contient bien toutes les queries possibles. Or sous chrome, il y a un post filtering sur cette liste qui ne doit pas marcher sous firefox

**Comment by 3AD** [comment]
En effet, non reproduit sous Chrome, mais toujours présent sous Firefox et IE 11 . Arrive sur une page qui contient déjà une liste ou qui ne contient pas de liste de contenus. Arrive aussi sur une nouvelle page.
