### ISSUE TITLE
Les ordres de priorité d'affichage ne sont pas utilisés dans les résultats de recherche

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#849]
Dans une recherche, le détail du contenu s'affiche sur la page de détail dans le cas ou aucune page associée n'a été indiquée.

**Comment by 3AD** [comment]
Odre de priorité : http://forum.rubedo-project.org/viewtopic.php?f=24&t=209&p=784&hilit=priorit%C3%A9#p784

**Comment by goncalvesm** [comment]
Ce point à été corrigé mais il faut tout de même le garder dans un coin car pour résoudre le problème nous avons ajouté une requête par contenu rapatrié dans la recherche. Cela implique une régression au niveau des performances de la recherche (temps de réponse plus long).

**Comment by 3AD** [comment]
Lorsque la taxonomie de navigation est complétée, le contenu s'affiche quand même dans une page de détail.

**Comment by Dixeet** [comment]
Chez moi l'ordre est bien respecté : 
1. Si le bloc courant possède une page associée (propriété du bloc), on utilisera cette page
2. Si une des entrées de la taxonomie de navigation appartient au site courant, on utilisera cette page
3. Si la page courante possède une colonne principale, on utilisera cette page
4. A défaut, la « page de détail par défaut » définie au niveau du site est utilisée
