### ISSUE TITLE
le bouton Download du Bloc Media download s'affiche alors que le bloc n'est pas paramétré

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#851]
Dans une page, un bloc Media download à été ajouté. Il n'a pas été paramétré (pas de média, ni d'introduction). Le bouton de téléchargement s'affiche en front-office.

**Comment by 3AD** [comment]
Le texte d'introduction au média ne s'affiche pas en FO

**Comment by goncalvesm** [comment]
Corrigé WebTales/rubedo-frontoffice@77b8b762ee9e683542cf151865f85655b02a632b
