### ISSUE TITLE
Le bloc media gallery affiche une galerie alors qu'il n'est pas paramétré

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#852]
Cas de test : ajout d'un bloc média gallery dans une page. La bloc n'a pas de requête paramétrée. En front-office, une galerie s'affiche avec l'ensemble des image de la DAM.

**Comment by goncalvesm** [comment]
Fixed WebTales/rubedo-frontoffice@b7f9ba2fd136ef0b3fe98b6df711116e0ef3fe17

**Comment by goncalvesm** [comment]
Merci de clôturer le ticket si c'est corrigé.
