### ISSUE TITLE
Le bloc liste de médias affiche des médias alors qu'il n'est pas paramétré

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#853]
Idem bloc Image gallery. Une fois la case "contain to site" décochée, une galerie de médias du site s'affiche alors que le bloc n'a pas de requête paramétrée.

**Comment by goncalvesm** [comment]
Non reproductible : 
![capture du 2014-12-02 10 19 55](https://cloud.githubusercontent.com/assets/2509924/5260262/dd5b71a2-7a0c-11e4-8945-cce475a79b71.png)
![capture du 2014-12-02 10 21 15](https://cloud.githubusercontent.com/assets/2509924/5260276/f99dca36-7a0c-11e4-9dab-abb540caa7db.png)

**Comment by 3AD** [comment]
Test refait sur http://audrey.v3.rubedo-project.org/en/homepage/dam  le bloc n'est pas paramétré en BO et il s'affiche

**Comment by goncalvesm** [comment]
Il semblerait que ce bug a déjà été identifié et corrigé sur la version de dev de la v3 car je n'arrive pas à le reproduire avec la même configuration de block que toi.

**Comment by 3AD** [comment]
Avec la mise à jour des correctifs, voici l'affichage du bloc de liste de médias

Sous chrome 
![media list](https://cloud.githubusercontent.com/assets/3063195/5261908/5479b5ac-7a1f-11e4-814c-ee9dac419dc2.png)

Sous Firefox
![media list firefox](https://cloud.githubusercontent.com/assets/3063195/5261912/5ea3322e-7a1f-11e4-8b14-6652cb4ac6c8.png)

**Comment by 3AD** [comment]
Le bloc Image gallery non paramétré affiche toujours des images

**Comment by goncalvesm** [comment]
Un fix à été appliqué sur le block media list : WebTales/rubedo-frontoffice@8afc94ffc47f9021f5192787f8b24a94c42ab340

Concernant le block de gallery d'image, pour ma part il n'affiche pas d'image lorsqu'il n'est pas configuré.

**Comment by 3AD** [comment]
Bloc Gallery d'image corrigé. En attente des correctifs sur les sites v3 pour tester le bloc media list non paramétré
