### ISSUE TITLE
Problème d'affichage des images dans un bloc de texte riche en fo

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#854]
Cas de test : dans une page avec un bloc de texte riche et un bloc de texte simple en dessous.
Lorsq'une image est ajoutée dans le bloc de texte riche, celle-ci s'affiche "par dessus" le texte simple.

**Comment by goncalvesm** [comment]
Non reproductible : 
![capture du 2014-12-02 10 27 13](https://cloud.githubusercontent.com/assets/2509924/5260347/d996028e-7a0d-11e4-82e8-7433c77cf121.png)
![capture du 2014-12-02 10 27 24](https://cloud.githubusercontent.com/assets/2509924/5260349/daeffeaa-7a0d-11e4-8c0a-9448f031ffce.png)

**Comment by 3AD** [comment]
Exemple ici : http://audrey.v3.rubedo-project.org/en/homepage

**Comment by goncalvesm** [comment]
Le bug se produit quand on applique un alignement à gauche ou à droite sur l'image. C'est maintenant corrigé : WebTales/rubedo-frontoffice@d1285e3f0621faf0491c5568f0e1f3d4cc7171f4
