### ISSUE TITLE
Le Bloc Newsletter subscription s'affiche en FO alors qu'il n'est pas paramétré

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#855]
Le bloc Newsletter subscription s'affiche en fo alors qu'il n'est pas paramétré en back (pas de news rattachée, ni de user type)

**Comment by goncalvesm** [comment]
Corrigé WebTales/rubedo-frontoffice@94c6951ef93936314d7512b5bc68df13a8154fb5
