### ISSUE TITLE
Pas d'enregistrement des options dans listeDeChoix pour les user types

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#857]
Dans un type d'utilisateur, il n'est pas possible d'enregistrer les options des listes de choix

**Comment by goncalvesm** [comment]
Je confirmes :+1:  : 

![capture du 2014-12-02 14 26 59](https://cloud.githubusercontent.com/assets/2509924/5263245/58a9bdb0-7a2f-11e4-8a29-07e5dcd0d949.png)
