### ISSUE TITLE
Affichage des tooltip en front

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#858]
Dans un formulaire d'inscription, les tooltip des champs du "type d'utilisateur" s'affichent en front.
Pas de rendu front des champs : date, image, location

**Comment by goncalvesm** [comment]
Corrigé WebTales/rubedo-frontoffice@d3ae5799ba39822076038025b3670eb7a520cf72

**Comment by 3AD** [comment]
Problème encore présent
![signup](https://cloud.githubusercontent.com/assets/3063195/5378637/cc590bd2-808b-11e4-8d45-2826735db367.gif)

**Comment by goncalvesm** [comment]
Les tooltips aident pour la saisie aussi bien en front qu'en back. Es-tu sure qu'il faut les retirer ?

**Comment by 3AD** [comment]
Normalement les tootip devraient s'afficher en front au survol du picto comme ci-dessous :
![sans titre](https://cloud.githubusercontent.com/assets/3063195/5378905/9dac12aa-808d-11e4-9101-9c1939571967.jpg)

**Comment by goncalvesm** [comment]
Il faudra donc faire un atelier de conception.
