### ISSUE TITLE
Les vidéos Youtube ne s'affichent pas en FO

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#864]
Sur un site de test avec les données de la démo, les vidéos Youtube s'affichent dans la page en FO.
Sur un site sans les données de la démo, les vidéos ne s'affichent pas en FO.

**Comment by goncalvesm** [comment]
il faut renseigner la clé d'API iframely dans les paramètres du site sinon la vidéo ne s'affichera pas.
