### ISSUE TITLE
Stratégie de localisation ne s'applique pas au menu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#865]
A partir d'un site vide. La stratégie de localisation Only one n'est pas appliquée au menu. Les pages qui n'existent pas dans la langue consultée sont affichées et grisées dans le menu.

A partir d'un site utilisant les données de démo. Le changement de stratégie de localisation à Only one affiche une erreur en FO " An error occurred during execution; please try again later".

**Comment by goncalvesm** [comment]
Le problème vient des filtres Mongo paramétrés dans l'API Rubedo. Les filtres pour le mode "OnlyOne" sont appliqués après que la requête qui rapatrie le menu ([readChild()](https://github.com/WebTales/rubedo/blob/v3-dev/module/Rubedo/src/Rubedo/Collection/AbstractLocalizableCollection.php#L258)) soit déclenchée. Voir [initLocaleFilter()](https://github.com/WebTales/rubedo/blob/v3-dev/module/Rubedo/src/Rubedo/Collection/AbstractLocalizableCollection.php#L88), [handler()](https://github.com/WebTales/rubedo/blob/v3-dev/module/RubedoAPI/src/RubedoAPI/Rest/V1/AbstractResource.php#L113) et [injectLocalization()](https://github.com/WebTales/rubedo/blob/v3-dev/module/RubedoAPI/src/RubedoAPI/Services/Internationalization/Current.php#L36).

L'ordre logique devrait être : 
- handler()
- injectLocalization()
- initLocaleFilter()
- readChild()

Hors nous faisons : 
- handler()
- injectLocalization()
- readChild()
- initLocaleFilter()

Donc le readChild() s'effectue avec les mauvais filtres.
