### ISSUE TITLE
Le style CSS par defaut sur les layout sont en gras

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#866]
Lorsque l'on créé un layout pour un type de contenu, tous les champs texte de ce contenu sont en font-weight.

**Comment by 3AD** [comment]
Pour les profil utilisateur aussi

**Comment by goncalvesm** [comment]
Corrigé WebTales/rubedo-frontoffice@25abfaba366d643d073d301984cfd356b7a2096b

**Comment by 3AD** [comment]
Corrigé pour les layout de contenus, mais par pour les utilisateurs

**Comment by goncalvesm** [comment]
Corrigé WebTales/rubedo-frontoffice@9cc14f07551f4ea2d1dbaa55f43bdc80e96e9e5c
