### ISSUE TITLE
Import de contenus : le champs texte riche ne s'affiche pas en FO

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#867]
Cas de test : création d'un nouveau type de contenu avec le module d'import.
Le type de contenu : titre, résumé et body.

En front-office, le champ body (de type texte riche) ne s'affiche pas. Il faut ouvrir le contenu, le publier pour que le champ texte riche soit affiché en front.

**Comment by 3AD** [comment]
Exemple : http://audrey.v3.rubedo-project.org/en/homepage/54637bb3323f7912203dcc08/san-francisco-proposal-would-create-denser-more-affordable-housing

**Comment by 3AD** [comment]
Rien à faire, le champ texte riche reste vide. J'ai l'erreur suivante sur la console FO : Error: Syntax error, unrecognized expression: texte du champs texte riche

**Comment by dfanchon** [comment]
Cause identifiée. Angular n'arrive pas à compiler un contenu HTML non balisé. Après enregistrement via le RTE cela marche car Cke encapsule le texte dans un paragraphe. Fix envisagé : ajouter dynamiquement une balise non signifiante à la compilation.

**Comment by Alexandru-Dobre** [comment]
corrigé
