### ISSUE TITLE
Affichage du résumé des types de contenus

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#870]
Dans la mise en page des types de contenus, le champ résumé n'est jamais affiché en FO, que l'on utilise le template par défaut ou un template personnalisé.

**Comment by Dixeet** [comment]
Le résumé est là en tant que "résumé" à afficher dans une liste de contenus. Dans le détail de contenu , ce résumé n'est effectivement jamais affiché dans le template par défaut. Il y avait effectivement un bug dans le layout, celui-ci a été fixé.
