### ISSUE TITLE
Editeur d'images en ligne

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#872]
Lorsque je veux modifier une image de la médiathèque dans l'éditeur d'images , j'ai un message d'erreur : 

"Une erreur est survenue, veuillez essayer ultérieurement

[IOErrorEvent type="ioError" bubbles=false "

**Comment by Dixeet** [comment]
Ceci est bug de pixelr en local. En effet celui-ci fonctionne grace à un proxy et il doit communiquer avec votre serveur. Or si vous êtes en local, le proxy ne pourra pas communiquer directement avec votre machine, qui est derrière votre routeur. En faisant un test avec sur un serveur rubedo en ligne comme le cloud v3 tout semble fonctionner.
