### ISSUE TITLE
Les pictos de la barre d'édition en FO ne s'affichent pas

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#873]
Sous Firefox v 33.1.1 les icônes de la barre d'édition en front ne s'affichent pas
![barre edition fo](https://cloud.githubusercontent.com/assets/3063195/5230652/081d5602-772a-11e4-8662-205689506fa8.png)

**Comment by goncalvesm** [comment]
Les pictos s'affichent correctement sur Firefox de mon coté : 
![sans titre](https://cloud.githubusercontent.com/assets/2509924/5298133/e95308a6-7bb7-11e4-834b-adf56acb8311.png)

**Comment by 3AD** [comment]
Merci !
