### ISSUE TITLE
Tweets by @ s'affiche alors que le bloc n'est pas paramétré

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#874]
Lorsqu'un bloc Twitter est ajouté dans une page, et qu'il n'est pas paramétré, le FO affiche "Tweets by @ "

**Comment by goncalvesm** [comment]
Corrigé https://github.com/WebTales/rubedo-frontoffice/commit/02c03e631618c188c0a9ff9744e458c7ec11cf58
