### ISSUE TITLE
Content list pas de tri sur Last modified

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#877]
Lorsqu'une Query simple est paramétrée pour un bloc de liste de contenus, si le tri est paramétré à "Last modified", la liste en FO s'affiche par date de création. L'écran de récapitulatif de la query remplace "Last modified" par "Creation".
Idem si le tri est paramétré sur "Date"

**Comment by Dixeet** [comment]
Bug non reproduit avec cette requete :
![image](https://cloud.githubusercontent.com/assets/6210428/5263488/e149a944-7a31-11e4-883f-f16d37d774d0.png)
J'obtiens bien en front une liste avec en premier le dernier contenu modifié.

**Comment by 3AD** [comment]
en effet ça remarche avec la mise à jour des sites. Par contre, l'écran de récapitulatif de la query remplace toujours "Last modified" et "Date" par "Creation".

**Comment by Dixeet** [comment]
Chez moi cet écran est bon : 
![image](https://cloud.githubusercontent.com/assets/6210428/5264099/22fd9606-7a38-11e4-891f-a9354f4b609b.png)

**Comment by 3AD** [comment]
Hum, mon interface est en anglais

**Comment by Dixeet** [comment]
![image](https://cloud.githubusercontent.com/assets/6210428/5264456/1e78a334-7a3b-11e4-8f18-e90f010d70e3.png)

**Comment by 3AD** [comment]
Bug reproduit, ci joint des détails sur le test.
- A la création d'une query simple, je sélectionne mon type de contenu Article. 
- Je sélectionne un tri sur la date de création ascendant,
- je passe à l'écran récapitulatif. Le résumé est ok.
- je reviens à l'écran précédent pour modifier la Date de création par la Date de modification
- je passe à l'écran de récap. Le résumé affiche le paramétrage du précédent paramétrage : "création ascendant" à la place de "date de modification".

Si la requête est enregistrée, alors c'est la première requête  "création ascendant" qui est enregistrée.
Si je souhaite modifier la requête enregistrée, j''édite la requête, mais le résumé ne se modifie pas avec les nouveaux paramètres.
