### ISSUE TITLE
Suppression du contenu d'un champ dans les contenus

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#879]
Sur un type de contenu avec des contenus, lorsque l'on change les propriétés d'un champ pour le rendre "recherchable", alors le contenu de ce champ est supprimé dans les contenus existants.

**Comment by Dixeet** [comment]
Sur quel type de champs? Testé avec un champ texte riche, le bug n'a pas été reproduit

**Comment by 3AD** [comment]
C'était un champ de texte riche

**Comment by Dixeet** [comment]
Je n'ai pas réussi à le reproduire, lorsqu'un champs texte riche est mise à jour à "recherchable", le contenu de ce champs dans les contenus issues de ce type de contenu sont toujours présents.

**Comment by 3AD** [comment]
Je ne parviens plus à le reproduire non plus. Je ferme le bug
