### ISSUE TITLE
Propriété "toolbar" inopérante dans le block "audio"

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#883]
La case à cocher "toolbar" dans les propriétés du block "audio" n'a aucune incidence, il n'y a pas de différence en front selon si elle est cochée au non.

**Comment by goncalvesm** [comment]
De mon coté, sur chrome, la barre du composant n’apparaît pas quand je ne coche pas "Toolbar". En revanche, le block ne fonctionne même pas sur firefox.

**Comment by Dixeet** [comment]
https://github.com/WebTales/rubedo-frontoffice/commit/705756089e5a8bac0e6c6ea026cc164aae8eb97a
