### ISSUE TITLE
Propriété "autocomplete" inopérante dans les recherches

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#884]
La propriété "autocomplete" est actuellement inopérante (que ce soit dans le bloc "search results" ou dans le bloc "Google Maps").
A priori à déplacer dans un nouveau bloc ? Dans ce cas, à supprimer des propriétés des blocs actuels.

**Comment by goncalvesm** [comment]
Propriété à supprimer du bloc de recherche.
