### ISSUE TITLE
Le bloc AddThis Follow ne permet pas de rediriger vers les bonnes url

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#886]
Normalement le bloc doit permettre d'ajouter les username des différents réseaux. En front-office, les icônes des réseaux s'affichent, mais ouvrent le site dans une nouvelle fenêtre à la place des fenêtres des réseaux.

**Comment by goncalvesm** [comment]
Corrigé (testé sur twitter et facebook) https://github.com/WebTales/rubedo-frontoffice/commit/668976a76d6665ec53783fcd24fe8d145d5ffb2e
