### ISSUE TITLE
Erreur sur champs multivalués dans un contenu

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#887]
Dans un type de contenu qui contient un champ de texte riche multivalué.
Une erreur s'affiche à l'enregistrement d'un nouveau contenu quand le "second champ" est complété : "$string doit être une chaîne de caractères "

**Comment by goncalvesm** [comment]
La création de contenu avec un champ texte riche multivalué est maintenant possible. Cependant, le front office ne gère toujours pas cette possibilité en v3. Il faut donc attendre la conception.

**Comment by 3AD** [comment]
Ok, géré en FO
