### ISSUE TITLE
Pas de "switch" de langues sur les contenus

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#889]
Lorsque l'on consulte un contenu multilingue dans un site, l'article et en anglais, on swicth de langue avec le bloc "langues" pour le consulter en français. On est redirigé automatiquement sur la page d'accueil.

**Comment by goncalvesm** [comment]
La redirection est maintenant "corrigée". Il faut cependant organiser un atelier de conception pour ce point afin de prendre en compte toutes les possibilités : 
- En strategie "Only one", doit-on afficher les langues non traduites d'un détail de contenu dans le bloc langue
- Doit-on rediriger l'utilisateur quand il essaye de consulter un contenu non traduit (toujours en stratégie "Only one")
- Afficher des message d'erreur quand le contenu n'est pas traduit
- Afficher le titre dans l'URL de redirection
  ...
  WebTales/rubedo-frontoffice@c5173f46ef8b4ca20638e51f6144b07fe014c0c4
