### ISSUE TITLE
Champ média image non affiché en FO

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#890]
Suite à la mise à jour de la version bêta, les champs "media" de type image n'apparaissent plus en FO.

**Comment by goncalvesm** [comment]
Bonjour,

Nous avons effectué un correctif il y a peu de temps sur les champs média. De ce fait, j'ai mis à jour votre version de Rubedo au cas ou.Normalement vous ne devriez plus rencontrer ce problème mais si le cas persiste, merci de nous fournir plus d'éléments (captures d'écran, URL etc.) si possible.

Merci.

**Comment by nicolasrhone** [comment]
Bonjour,

C'est bon, cela fonctionne à présent ! Merci beaucoup pour votre 
réactivité !

Cordialement

Nicolas Rhoné
