### ISSUE TITLE
Les images d'une "Image gallery" en FO s'affichent dans une nouvelle fenêtre

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#893]
En front, lorsque l'on clique sur une image dans une Image gallery, elle doit s'afficher en popin

**Comment by Dixeet** [comment]
Dans quel cas c'est rencontré? Je viens de tester en utilisant plusieurs paramètres et je n'arrive pas à reproduire ce bug (que ce soit sous chrome, firefox ou ie)
