### ISSUE TITLE
Les newsletters ne s'affichent pas en FO sur le bloc Sign up

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#894]
Le bloc sign up permet de proposer l'abonnement à des newsletters lors de l'inscription. L'abonnement à ces newsletters ne s'affiche pas en FO

**Comment by goncalvesm** [comment]
Corrigé (doublon du bug #856)
![sans titre](https://cloud.githubusercontent.com/assets/2509924/5374737/236c97c8-8063-11e4-9095-8d674c03f252.png)
