### ISSUE TITLE
Bloc texte riche

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#895]
Le bloc de texte riche ne fonctionne plus :lorsqu'on veut ajouter du contenu l'éditeur ne s'affiche pas correctement :
![capture](https://cloud.githubusercontent.com/assets/9321594/5313815/e2839b0c-7c6c-11e4-9f36-c11f73a4000e.PNG)

**Comment by goncalvesm** [comment]
Bonjour,
Les blocs de texte riche semblent fonctionner de mon coté. Il s'agit peut-être d'un bug d'interface du back office. Avez-vous toujours le problème après l'avoir rechargé ?
N'hésitez pas à revenir vers nous si le problème persiste.
![sans titre](https://cloud.githubusercontent.com/assets/2509924/5377513/195c30d4-8083-11e4-965f-14c38e5ae9cf.png)

**Comment by nicolasrhone** [comment]
Bonjour,

En effet, je constate que dans le site de démo, cela fonctionne aussi... 
J'ai essayé de recharger plusieurs fois le backoffice, cela n'a rien 
fait, le problème reste le même

Cela vient peut-être d'un problème dans la configuration de Rubedo ? 
Dans ce cas il suffirait peut-être de le remettre à jour avec la 
dernière version ?

Merci !

**Comment by goncalvesm** [comment]
je viens de mettre à jour votre serveur mais je ne pense pas que le problème y soit lié étant donné que le backoffice n'a pas été modifié récemment. Quel navigateur utilisez-vous ? Car parfois il peut y avoir des problèmes de compatibilité. Je vous propose d'essayer sur un navigateur à jour comme Google Chrome ou Firefox. Le problème peut également provenir d'une modification de configuration du module CKEditor, avez-vous effectué une modification de ce type ?

**Comment by nicolasrhone** [comment]
En effet, cela n'a rien changé.

J'utilise Chrome et Firefox, tous deux à jour... donc cela ne vient pas 
de là.

En fait je me suis rendu compte du problème quand j'ai cherché comment 
personnaliser CKEditor... mais je n'ai pas fait de modifications puisque 
j'ai réalisé à ce moment que le bloc ne fonctionnait pas. Mais peut-être 
que j'ai fait une fausse manipulation sans m'en rendre compte !? Cela 
semble être la seule possibilité...

Est-il possible de remettre à jour le module ?

**Comment by goncalvesm** [comment]
Merci d'envoyer un mail à l'adresse support@webtales.fr afin de trouver une solution au problème.

**Comment by 3AD** [comment]
Bonjour, merci de penser à fermer les bugs lorsque les corrections sont validées. Merci !
