### ISSUE TITLE
Pas d'affichage front des médias multivalués

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#896]
Lorsqu'un type de contenu est composé d'un champ média multivalué, en front-office, il n'est pas possible d'afficher ces médias.

**Comment by Dixeet** [comment]
La multiévaluation n'était pas du tout implémentée, quelque soit le type de champs. Ceci est maintenant fait, cependant il existe toujours quelques bug de "multiévaluation" du à l'enregistrement (à l'édition) (présent dans le BO)
