### ISSUE TITLE
Perte de la navigation sur liste de contenus paginés

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#897]
Cas 
J'ai une page sur 2 colonnes.
- La première colonne propose une liste de contenus paginés
- La seconde colonne est vide car c'est une colonne principale pour afficher le détail des contenus de la liste

Si l'on navigue dans la liste, par exemple sur la page 2. On affiche le détail d'un contenu. La liste de contenu de la première colonne est modifiée et retourne automatiquement sur la page 1 de la liste.

**Comment by goncalvesm** [comment]
Atelier de conception à prévoir.

**Comment by Dixeet** [comment]
Tout ceci sera implémenté à partir du moment où nous auront créé la "liaison" inter bloc. Il n'y aura plus de rechargement de page, la navigation sera donc préservée.
