### ISSUE TITLE
Bloc contact

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#899]
Dans le bloc contact, on ne peut pas indiquer une adresse mail mais une mailing list ? 
Puis, lorsqu'on veut utiliser le bloc pour envoyer un mail, on a l'erreur :
" Error ! Aucun smtp défini dans la configuration "

**Comment by goncalvesm** [comment]
Bonjour Nicolas,

Premièrement, il faut configurer le serveur mail SMTP afin que l'application puisse envoyer des mails (configuration à faire dans l'install tool).
![sans titre](https://cloud.githubusercontent.com/assets/2509924/5377801/954d568a-8085-11e4-8dbb-ee10d277c4bd.png)

Une fois que ce sera fait, l'application sera désormais capable d'envoyer des mails. L'adresse ou vous recevrez les e-mails est l'adresse configurée dans le champ "Reply address" de la mailing list configurée dans le bloc.
![sans titre](https://cloud.githubusercontent.com/assets/2509924/5377907/86a7a260-8086-11e4-98a8-bfdbaa38b883.png)

**Comment by nicolasrhone** [comment]
Bien sûr ! Désolé pour cette erreur, en effet on j'avais passé sur cette 
étape dans la configuration... sans penser que je souhaiterais plus tard 
pouvoir envoyer des mails par le site...

Merci,

Cordialement
