### ISSUE TITLE
Masque de page unique pour accueil, recherche et détail

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#90]
Etant donné qu'il n'est pas possible a posteriori de modifier le masque de page d'une page, c'est potentiellement problématique que, lors de la création d'un site, le même masque de page soit utilisé pour l'accueil, la recherche et le détail (qui auront dans 90% des cas des gabarits différents)

**Comment by goncalvesm** [comment]
commit 001ae93
