### ISSUE TITLE
Pas de traduction des champs par défaut dans le bloc Signup

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#900]
Dans un site en 2 langues, anglais et français, les champs Name, Email et password ne sont pas traduits en français.
Les champs affichés restent dans la langue dans laquelle ils ont été saisis, même si ils sont traduits.
Cas : dans un type utilisateur j'ai crée un champ "zoneDeTexte"dans mon site en anglais. J'ai ensuite traduit la page et les labels de mon type d'utilisateur pour qu'ils soient en EN et EN. Mon champ affiche par défaut "zoneDeTexte" dans les 2 langues

**Comment by goncalvesm** [comment]
Sauf erreur de ma part, les champs Name, Email et Password ne sont pas traduisibles en backoffice d'ou le problème que tu rencontre. Il faudra faire un atelier de conception pour ce point.
