### ISSUE TITLE
Le bloc menu s'affiche alors qu'il n'y a pas de page à afficher

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#902]
Cas : un bloc menu paramétré sur un masque.
Fallback root : current
Base level : 1

La page créé sur ce masque ne dispose pas de pages filles dans l'arborescence. Le bloc s'affiche en FO et il est vide

**Comment by goncalvesm** [comment]
Ce point est un problème de configuration et non un bug car effectivement dans ton cas rien ne s'affiche mais si je coche l'option "Afficher la racine" il y a bien une page dans le menu.
