### ISSUE TITLE
Le bloc plan de site utilise le titre SEO

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#904]
Le plan du site devrait utiliser le titre des pages et non le titre SEO

**Comment by goncalvesm** [comment]
Corrigé WebTales/rubedo-frontoffice@f36e8b0d1eacc8ee223f48b9b697e84b21335a13

**Comment by 3AD** [comment]
Sur mon site de test, tous les niveaux hors accueil utilisent le titre SEO

**Comment by goncalvesm** [comment]
Corrigé  WebTales/rubedo-frontoffice@a70ec0f3f64e587284de1c64135389c642adc682
