### ISSUE TITLE
Perte de l'adresse localisée sur bloc Google map

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#920]
Sur une page, un bloc G map avec la géolocalisation de contenus. La carte est géolocalisée sur une adresse.
On sélectionne un contenu pour voir son détail.
Lorsque l'on revient sur la page avec la map, celle-ci n'est plus centrée sur l'adresse paramétrée en bo.

**Comment by goncalvesm** [comment]
De mon coté le bloc google map revient bien sur la position paramétrée en backoffice lorsque je clique sur un contenu et que j'appuis sur le bouton "précédent" du navigateur pour revenir sur la carte.
