### ISSUE TITLE
Recherche FO : facette Date de modification

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#922]
Cette facette n'est pas présente en BO et en FO

**Comment by goncalvesm** [comment]
La facette est bien présente de mon coté: 
![sans titre](https://cloud.githubusercontent.com/assets/2509924/5501968/5a325d18-8763-11e4-964f-804069bb1046.png)

**Comment by 3AD** [comment]
Plusieurs points
- le nombre de contenus n'est pas affiché sur la facette "Modification date"
  ![recherche fo](https://cloud.githubusercontent.com/assets/3063195/5502122/b9510ea0-8765-11e4-8430-dcf047d63d66.png)
- l'affichage de la facette "Modification date " est différente en mode standard et en mode case à cocher. 
  en mode case à cocher, toutes les périodes de dates sont affichées.
  en mode standard la date "moins de 24h s'affiche" et la période "Moins d'une semaine" ne s'affiche pas

**Comment by Dixeet** [comment]
Je n'ai pas réussi à le reproduire. Peux-tu retester voir si tu rencontres toujours le problème ?
