### ISSUE TITLE
BO : liens sur contenus

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#923]
Dans le BO, j'ai un type de contenu avec un champ lien sur contenus.
1-le contributeur rédige un contenu
2- il clic sur le champ Lien sur page
3- la page de résultats de recherche s'affiche
4- il double clic sur un contenu 
5- une fenêtre s'ouvre (la fenêtre devrait afficher le détail du contenu) et bloc le back-office
un redémarrage de l'interface est alors nécessaire

**Comment by dfanchon** [comment]
double-click choisit le contenu et ferme la fenêtre
même comportement sur le picker de médias
