### ISSUE TITLE
Recherche FO et BO : affichage dans la langue anglaise

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#925]
En FO et BO la facette Type de données propose les médias, contenus et utilisateurs uniquement en langue anglaise, il n'y a pas de traduction

**Comment by goncalvesm** [comment]
Ces facettes sont bien traduites dans le noyau de Rubedo mais il semblerait que les règles métier ne soient pas respectées : 
- Quand un utilisateur est connecté, la langue utilisée est celle de l'utilisateur (et non celle de l'interface du BO)
  ![sans titre](https://cloud.githubusercontent.com/assets/2509924/5504507/7307d1e8-8785-11e4-8d45-b16b33abf798.png)
- Quand il s'agit d'un utilisateur anonyme, la langue par défaut est l'anglais
  ![sans titre](https://cloud.githubusercontent.com/assets/2509924/5504524/b495910e-8785-11e4-8934-9253fee5b3b4.png)

Il n'y a donc aucune interaction avec la langue du site !

Merci de déterminer dans ce ticket si le comportement est correcte ou si il faut le modifier (atelier de conception).

**Comment by 3AD** [comment]
Ces facettes doivent utiliser la langue du site en FO

**Comment by 3AD** [comment]
L'erreur est toujours présente en FO sur mon site de test

**Comment by goncalvesm** [comment]
Les facettes sont bien corrigées de mon coté. J'en ai profité pour corriger deux autres libellés.
