### ISSUE TITLE
Affichage non traduit d'un bloc recherche en FO

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#934]
Les tris disponibles (pertinence, date, auteur) dans un bloc page de recherche ne sont pas traduits 
Le champ recherche propose un placeholder en anglais, pas de traduction

**Comment by goncalvesm** [comment]
Ces libellés sont maintenant traduits sauf pour le libellé qui indique le trie appliqué car les libellés "relevance", "date", "author" etc. viennent de l'API. Pour que les autres libellés qui n'apparaissent pas en français, il faut mettre à jour CrowdIn et les traduire !
