### ISSUE TITLE
Sites : impossible de modifier le titre du site

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#949]
Le default title, description et mots clés ne sont pas enregistrés dans Sites.
Pour pouvoir les enregistrer, il faut traduire Site dans une seconde langue. Après, il est possible de saisir et d'enregistrer les informations dans les 2 langues

**Comment by Dixeet** [comment]
Impossible à reproduire : j'ai créer un nouveau Rubedo, j'ai fait un nouveau site. J'ai ajouté une langue afin d'avoir 2 langues mais sans traduire le site. Je modifie le titre du site/description/mots clés. Mes changements sont bien enregistrés
