### ISSUE TITLE
Modification du mot de passe

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#95]
Dans Paramètres > Accès, si je souhaite modifier mon mot de passe et que je me trompe dans mon mot de passe actuel, j'ai une fenêtre "Erreur" qui s'ouvre sans aucun texte.

De plus, en cas de succès, la popin de notification "Mot de passe changé" n'est pas en cohérence avec les autres popin (affichage dans le coin en haut à droite).

**Comment by Alexandru-Dobre** [comment]
notif règlée
pour le premier point, l'erreur serveur est vide (pas de msg)
