### ISSUE TITLE
Classer les medias dans le media picker

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#950]
Pour simplifier le travail des contributeurs ça serait bien que les dernières images uploadées soit classées en sens inverse, c'est à dire les plus récentes en premier

**Comment by dfanchon** [comment]
Le problème c'est que nous sommes dans le cadre d'une recherche avec un ordre de tri par pertinence par défaut. Il faudrait définir des règles dynamiques de tri en fonction du contexte et de l'action, ce qui parait compliqué. Dans tous les cas il est simple de trier par date. A revoir en 3.1

**Comment by Alexandru-Dobre** [comment]
Si le sort est par défaut sur le lastUpdateTime il le reste ensuite sur toutes les fenetres de recherche du BO -> persisté dans les states du store et pas de reset sans double requette par la suite. C'est si grave que ce ne soit pas par défaut étant donné qu'en eun clic sur la colonne le sort est fait ?

**Comment by 3AD** [comment]
moi ça me va en last update time

**Comment by Alexandru-Dobre** [comment]
done

**Comment by 3AD** [comment]
ok
