### ISSUE TITLE
Pas de style css dans les tableaux wysiwyg

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#956]
En édition front
Lorsqu'un tableau est ajouté dans un texte riche, si celui-ci contient du texte avec un style (H2, H3, ...), ces styles apparaissent en mode édition, mais ils sont supprimés après l'enregistrement de la page

**Comment by 3AD** [comment]
Les bordures des tableaux ne s'affichent pas

**Comment by dfanchon** [comment]
Il s'agit du comportement des css bootstrap 3 par défaut.
Par exemple pour afficher les bordures d'un tableau ajouter la classe table-bordered
