### ISSUE TITLE
Message d'erreur dans Install Tool > Mailer

### ISSUE THREAD

**Issue by nicolastrenti** [WebTales/rubedo#959]
Dans l'onglet Mailer de l'Install Tool, on a le message d'erreur suivant lorsqu'aucun serveur SMTP n'est paramétré:

Rubedo can't connect to SMTP server : Connection could not be established with host [L�adresse demand�e n�est pas valide dans son contexte. #10049]
- Problème de jeu de caractère
- Message en français alors que tout l'install tool est en anglais

**Comment by goncalvesm** [comment]
Je pense que ce message ne vient pas de Rubedo mais du SMTP auquel on tente de se connecter. Peux-tu me fournir les informations que tu as saisies pour obtenir ce message afin que je vérifie cette hypothèse ?
