### ISSUE TITLE
Gestion des droits : l'espace de travail en lecture donne les droits de modification

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#966]
Cas de test
- j'ai 2 sites, le site dans l'espace de travail A et le site 2 dans l'espace de travail B
- J'ai crée un groupe qui sera administrateur du site 2

Ce groupe à les droits suivants 
- en lecture sur l'espace de travail A et l'espace de travail B, 
- droits en contribution que pour l'espace B
- Son espace de travail par défaut est l'espace B
- l'administration est positionnée dans l'espace de travail B
- rôles : tous les rôles sauf celui d'administrer la plateforme

Les utilisateurs de ce groupe peuvent modifier tous les éléments dans les 2 espaces de travail. 
Si par contre, on supprime le droit de lecture sur l'espace A, alors les utilisateurs ne peuvent modifier que les éléments de l'espace B.
Il y a donc incohérence sur les droits de lecture qui donnent accès au droit de contribution/modification.

**Comment by dfanchon** [comment]
à préciser : quels sont les éléments modifiés

**Comment by 3AD** [comment]
Sans doute un souci de cache, bug non reproduit
