### ISSUE TITLE
Content detail block and rights management

### ISSUE THREAD

**Issue by nicolasrhone** [WebTales/rubedo#967]
Dans un espace de travail avec tous les droits, saut l'administration de la plate-forme, la recherche de contenu liée au bloc "détail de contenu" ne fonctionne pas, il y a un message d'erreur : "Impossible d'accéder à execute.controller.elasticsearchcontent.index.backoffice".
Pour y arriver, il faut donner le droit d'administrer la plate forme. Mais alors la recherche affiche tous les contenus, et ceux provenants d'espaces de travail non accessibles en lecture ou modification s'affichent avec comme nom "null".
![capture](https://cloud.githubusercontent.com/assets/9321594/5998215/2d79e234-aac5-11e4-8146-8c95f22cc5a4.PNG)

**Comment by Alexandru-Dobre** [comment]
corrigé
