### ISSUE TITLE
Impossible de supprimer un groupe

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#968]
Cas de test 
- création d'un espace de travail "Test"
- création d'un groupe d'utilisateurs "Mon groupe". Ce groupe à les droits de lecture sur Global, d'écriture sur "Test" et l'administration de ce groupe sera réalisé par l'administrateur de l'espace de travail "test".
- l'espace de travail est supprimé.

L'administrateur central ne peut plus éditer le groupe "Mon groupe" car celui-ci est grisé.
En effet Rubedo ne peut pas résoudre les droits d'accès à cet espace qui n'existe plus.

Solutions : 
- Lors de la suppression d'un Espace de travail : afficher une alerte qui indique que des groupes sont administrés sous cet espace et que le groupe ne peut être supprimé.
  ou
- donner la possibilité à l'administrateur central de pouvoir appliquer un nouvel espace de travail en administration.

**Comment by goncalvesm** [comment]
Corrigé -> L'admin centrale peut maintenant supprimer ces groupes ou leur modifier le workspace
