### ISSUE TITLE
Security Issue : CSRF on demo website

### ISSUE THREAD

**Issue by imnarendrabhati** [WebTales/rubedo#975]

**Comment by goncalvesm** [comment]
Hi narendrabhati,

Thanks for your feeback. I've tested your script and i think that you've done a little mistake. I'll resume step by step your test case : 

- You start your favorite web browser
- You go to the page : http://demo.rubedo-project.org/
- You log in with the admin account

- You create a html file wich contain your form
- You execute this file with the same web browser

Result : The account informations has changed.

Why ? Because you tested on the same browser and by the way the cookies/session were set. Then it's normal, you make an HTTP request like us with the good parameters and you are logged in for the app.

Now try this : 
- You start your favorite web browser
- You go to the page : http://demo.rubedo-project.org/
- You log in with the admin account

- Start another web browser
- You create a html file wich contain your form
- You execute this file in the second web browser

Result : Nothing has changed.

Why ? Because on the second browser you are not logged in for the app.

Tell me if i've missed something in your example and don't hesitate to share with us more potential security failures.

**Comment by narendrabhati** [comment]
You done a lots of mistake !

CSRF attack required an authentication session to execute :)

Now how an attacker will attack ! we will see step by step ok
1. Suppose admin is logged in his favorite web browser
2. An user known as attacker post a comment on post with containts a link !
3. Now when admin will see that comment and willing to open that link
4. After executing the link the admin info will be changed

Read Here For more information https://www.owasp.org/index.php/CSRF
And if you want to see the real attack scenario then go through this link -
http://websecgeeks.com/modx-csrf-and-xss/

On Fri, Feb 20, 2015 at 9:11 PM, Goncalves Mickael <notifications@github.com
> wrote:

> Hi narendrabhati,
>
> Thanks for your feeback. I've tested your script and i think that you've
> done a little mistake. I'll resume step by step your test case :
>
>    - You start your favorite web browser
>    - You go to the page : http://demo.rubedo-project.org/
>    -
>
>    You log in with the admin account
>    -
>
>    You create a html file wich contain your form
>    - You execute this file with the same web browser
>
> Result : The account informations has changed.
>
> Why ? Because you tested on the same browser and by the way the
> cookies/session were set. Then it's normal, you make an HTTP request like
> us with the good parameters and you are logged in for the app.
>
> Now try this :
>
>    - You start your favorite web browser
>    - You go to the page : http://demo.rubedo-project.org/
>    -
>
>    You log in with the admin account
>    -
>
>    Start another web browser
>    - You create a html file wich contain your form
>    - You execute this file in the second web browser
>
> Result : Nothing has changed.
>
> Why ? Because on the second browser you are not logged in for the app.
>
> Tell me if i've missed something in your example and don't hesitate to
> share with us more potential security failures.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/WebTales/rubedo/issues/975#issuecomment-75258423>.
>



-- 
*Narendra Bhati "CEH" **( Facebook
<http://www.facebook.com/narendradewsoft> , Twitter
<http://www.twitter.com/NarendraBhatiB> , LinkedIn
<https://www.linkedin.com/profile/view?id=115146074> , Personal Blog
<http://hacktivity.websecgeeks.com> )*
*Security Analyst - IT Risk & Security Management Services*
Suma Soft Pvt. Ltd. | Suma Center | Near Mangeshkar Hospital | Erandawane
Pune: 411004 | *+919923397301*

*======================================================================*

**Comment by jhamkutest** [comment]
test comment

**Comment by narendrabhati** [comment]
test comment

**Comment by jhamkutest** [comment]
test comment

**Comment by narendrabhati** [comment]
test

On Fri, Feb 20, 2015 at 9:33 PM, jhamkutest <notifications@github.com>
wrote:

> test comment
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/WebTales/rubedo/issues/975#issuecomment-75262590>.
>



-- 
*Narendra Bhati "CEH" **( Facebook
<http://www.facebook.com/narendradewsoft> , Twitter
<http://www.twitter.com/NarendraBhatiB> , LinkedIn
<https://www.linkedin.com/profile/view?id=115146074> , Personal Blog
<http://hacktivity.websecgeeks.com> )*
*Security Analyst - IT Risk & Security Management Services*
Suma Soft Pvt. Ltd. | Suma Center | Near Mangeshkar Hospital | Erandawane
Pune: 411004 | *+919923397301*

*======================================================================*

**Comment by goncalvesm** [comment]
I invite you to create a site on the last version of Rubedo : http://www.rubedocloud.com/en/

Then create a working example and give us your site URL.

Write actions to the database from the API are protected with a token.

**Comment by imnarendrabhati** [comment]
ok wait a for some minute let me give a try

On Fri, Feb 20, 2015 at 9:47 PM, Goncalves Mickael <notifications@github.com

> wrote:
> 
> I invite you to create a site on the last version of Rubedo :
> http://www.rubedocloud.com/en/
> 
> Then create a working example and give us your site URL.
> 
> With the last version, write actions to the database from the API are
> protected with a token. Then your fake form has to know this token to
> perform an intrusion.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/WebTales/rubedo/issues/975#issuecomment-75265067.

## 

_Narendra Bhati "CEH" *_( Facebook
http://www.facebook.com/narendradewsoft , Twitter
http://www.twitter.com/NarendraBhatiB , LinkedIn
https://www.linkedin.com/profile/view?id=115146074 , Personal Blog
http://hacktivity.websecgeeks.com )*
_Security Analyst - IT Risk & Security Management Services_
Suma Soft Pvt. Ltd. | Suma Center | Near Mangeshkar Hospital | Erandawane
Pune: 411004 | _+919923397301_

_======================================================================_

**Comment by imnarendrabhati** [comment]
Your cloud application is secured with a token thats look great , i was
hopping for the same token ;)

**Comment by Alexandru-Dobre** [comment]
Issue only present on deprecated demo website. It is not adressed as the site database is reset every hour.
