### ISSUE TITLE
Configuration Backoffice

### ISSUE THREAD

**Issue by anthofremion** [WebTales/rubedo#983]
Bonjour,

Est-il possible de configurer sur un bloc de backoffice un champ permettant une sélection multiple de page dans l'arbo ? (Comme le fait la taxo de navigation)

Quelque chose qui pourrait ressembler à :

```
"champsConfig":{
    "simple":[
        {
            "categorie": "Contenu",
            "champs": [
                {
                    "type": "Ext.ux.treemultipicker",
                    "config": {
                        "fieldLabel":"Navigation",
                        "name":"ContentsNavTaxo"
                    }
                }
            ]
        }
    ]
}
```

Merci,
Cordialement,
Antho

**Comment by Alexandru-Dobre** [comment]
Le champ classique de sélection de page peut recevoir une config avec "multiSelect":true

**Comment by anthofremion** [comment]
Je viens de tester : 

```
{
    "type": "Ext.ux.TreePicker",
    "config": {
        "fieldLabel": "Pages",
        "name": "pages",
        "multiSelect":true
    }
}
```

Mais cela ne fonctionne pas de mon coté, manque t'il un paramètre ?

**Comment by Alexandru-Dobre** [comment]
Le composant tiers utilisé ne semble pas implémenter cette option.
Le tree multipicker n'est pas implémenté par défaut sur les champs de config de blocks en BO
