### ISSUE TITLE
Front-end editing : title field

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#986]
En front, dans une liste de contenu, lorsque le titre est édité et que l'on enregistre les modifications, on a une alerte qui indique qu'il y a une erreur à l'enregistrement.
La page affiche ensuite une erreur à la place du champs.
![error front edit title](https://cloud.githubusercontent.com/assets/3063195/6388975/d7f62208-bd9f-11e4-9598-151fae2c2775.png)

**Comment by Alexandru-Dobre** [comment]
fixed

**Comment by 3AD** [comment]
Encore constaté. Maj de l'environnement à vérifier

**Comment by Alexandru-Dobre** [comment]
Non reproduit
