### ISSUE TITLE
Modification d'agencement des informations dans Order detail

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#988]
Lorsque l'on finalise la commande, si le paiement est réalisé par chèque, le texte d'accompagnement (saisi dans moyen de paiement) est affiché sous l'order detail.
Il faudrait déplacer les information de statut et de paiement avant
Payment
    Payment means : check
    Payment status : pendingPayment
(Message saisi pour ce moyen de paiement) Merci d'envoyer votre paiement à notre adresse ...

**Comment by Alexandru-Dobre** [comment]
fixed
