### ISSUE TITLE
Pas d'affichage du champ Date dans le checkout

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#989]
Dans le step 2 Contact informations, si le type utilisateur contient un champ date, celui-ci ne s'affiche pas en front dans le checkout

**Comment by goncalvesm** [comment]
Aucun soucis pour moi : 

![image](https://cloud.githubusercontent.com/assets/2509924/8596698/24ca2092-2651-11e5-8006-d4ee7d8a579a.png)

Il faut savoir que si tu es connectée, le type d'utilisateur utilisé pour générer le formulaire est le tiens et non celui configuré en back.
