### ISSUE TITLE
Etre redirigé automatiquement sur sa page profil à la connexion

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#992]
Afin de guider plus facilement les utilisateurs lors de leur connexion sur un site, il faudrait pouvoir rediriger les utilisateurs sur leur page profil dès qu'ils sont connectés.

**Comment by goncalvesm** [comment]
nous avons ajouté une option "Redirect on connection" qui, quand elle est cochée, redirige l'utilisateur vers sa page de profile (si elle est configurée également dans le block)

**Comment by 3AD** [comment]
Merci de penser aux clés de traduction

-------- Message d'origine --------
De : Goncalves Mickael notifications@github.com 
Date :  
A : WebTales/rubedo rubedo@noreply.github.com 
Cc : 3AD audrey.dumas@webtales.fr 
Objet : Re: [rubedo] Etre redirigé automatiquement sur sa page profil à la connexion (#992) 

nous avons ajouté une option "Redirect on connection" qui, quand elle est cochée, redirige l'utilisateur vers sa page de profile (si elle est configurée également dans le block)
