### ISSUE TITLE
Changer l'emplacement de I have read and agree to the Terms and Conditions

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#995]
Actuellement, l'accord est demandé sur Contact information. Si la personne a déjà passé une commande, l'activation de l'accord n'est pas redemandé. Il faudrait que cette case soit présentée à chaque commande, même pour un client connu.
Pourrait-on déplacer cet élément au niveau du choix du transporteur ou du paiement ?

**Comment by Alexandru-Dobre** [comment]
fixed
