### ISSUE TITLE
Modifier le comportement lors d'une erreur de workspace

### ISSUE THREAD

**Issue by 3AD** [WebTales/rubedo#999]
Lorsqu'un utilisateur saisi un contenu et que l'utilisateur n'a pas les droit sur le workspace de ce type de contenu il obtient à la soumission :
"Erreur You can not assign this content type to this workspace" . Le contenu saisi est perdu.
Le même message apparait lorsque l'utilisateur n'a pas sélectionné le bon workspace.

Pour simplifier 
- lorsque l'utilisateur n'a pas de droit de saisir un contenu qui est uniquement pour un espace de travail pour lequel il n'a pas les droits : Ne pas lui donner la possibilité de créer un nouveau contenu.
- lorsque l'utilisateur, qui a les droits sur plusieurs espaces, n'a pas sélectionné le bon espace de diffusion, il obtient l'erreur et il perd son contenu. Il faudrait qu'il puisse modifier le workspace.

**Comment by Alexandru-Dobre** [comment]
@ca9114e4

**Comment by Alexandru-Dobre** [comment]
Ajouté bloqueur pour le premier point

**Comment by 3AD** [comment]
et pour le second ?

**Comment by dfanchon** [comment]
Le cas ne se produit qu'à l'intersection d'un workspace sur lequel l'utilisateur a les droits mais dans lequel le type de contenu ne peut pas être diffusé. Faire la vérification avant la soumission de la requête qui se produit a la fermeture de la fenêtre serait complexe. A revoir lors de la migration BO.
